### ISSUE TITLE
ZigBee2MQTT Network Formation and End Device Joining

### ISSUE THREAD

**Issue by Aimen-Hammou** [Koenkk/zigbee2mqtt#10125]
Hi, 

I opened a discussion about it, but it got ghosted.
I, urgently, need help regarding this so bear with me.

I'm using a CC2531EMK dongle to test some stuff and while trying to create the network, via ZTool< i stumbled upon the problem of how to handle an end device join.

ZStack version: 3.0.X

To form the network:

1)SYS_OSAL_NV_WRITE to 0x03 as value 0x03
2)SYS_RESET "SOFT RESET"
3)SYS_OSAL_NV_WRITE to 0x87 as value 0 (to set dongle as coordinator)
4)BDB_SET_CHANNEL to channel 11 ( 0x800)
5)BDB_START_COMMISSIONING as NETWORK FORMATION to form network
6)SYS_OSAL_NV_WRITE to 0x8F as value 0x01

Once the network is formed:
7) BDB_START_COMMISSIONIG as NETWORK STEERING
8) ZDO_MGMT_PERMIT_JOIN_REQUEST to 180 seconds.

But my end device ( Danfoss radiator thermostat 014G2461) doesn't seem to join.
It is supposed to send some beacons and the network should handle all the joining, but doesn't seem like working

My question is: How does ZigBee2MQTT form the network and handle the device joining? Fresh new network

**Comment by Koenkk** [comment]
You can find all commands send by zigbee herdsman to the ZNP by runnig z2m with `DEBUG=zigbee-herdsman* npm start` and the startup code can be found here: https://github.com/Koenkk/zigbee-herdsman/blob/1bcdef4526b89e3eab137df48e8b3a4dd86e03d1/src/adapter/z-stack/adapter/manager.ts#L257

I will close this since it is not a z2m issue.
