### ISSUE TITLE
Moes BRT-100-TRV does not respond after a faulty OTA update.

### ISSUE THREAD

**Issue by vladi1234** [Koenkk/zigbee2mqtt#10140]
## What happened
Moes BRT-100-TRV thermostat doesn't have its own firmware update yet, but Thermostat has received a wrong firmware update from a completely different Tuya thermostat.
Because of this, many thermostats were beefashed out of order

## This fixed the problem and TVR no longer received an incorrect OTA update.
https://github.com/Koenkk/zigbee-OTA/issues/48
https://github.com/Koenkk/zigbee-OTA/pull/50#issuecomment-913736281

## What did you expect to happen
Many users now want to restore broken thermostats.
If someone has ideas, or important information, write here in this topic, because others are already closed.

## Well-known issues that are unfortunately already closed.
https://github.com/Koenkk/zigbee2mqtt/issues/7941
https://github.com/Koenkk/zigbee2mqtt/issues/7941#issuecomment-907148068

https://github.com/Koenkk/zigbee-herdsman-converters/issues/2932
https://github.com/Koenkk/zigbee-herdsman-converters/issues/3317

## Maybe someone can use it.
https://github.com/Koenkk/zigbee-herdsman-converters/issues/2937

########################################################################################
![BRT-100-TRV](https://user-images.githubusercontent.com/45510877/145679802-bfe0c166-a444-4719-b8c3-366bb2871319.jpg)
![IMG_20210827_155612](https://user-images.githubusercontent.com/45510877/145679827-2fea4b1a-6c0a-4123-a16a-6ebbdf136cbe.jpg)
![IMG_20210827_155903](https://user-images.githubusercontent.com/45510877/145679850-56df00d2-c162-4a2c-a223-043075a74206.jpg)

![IMG_20210827_160127](https://user-images.githubusercontent.com/45510877/145679859-2a6bd530-e170-4182-9469-040585b3c34b.jpg)
![IMG_20210827_160616](https://user-images.githubusercontent.com/45510877/145679871-260db0ca-17f6-4e44-ae65-c48a564709a0.jpg)
![IMG_20210827_160511](https://user-images.githubusercontent.com/45510877/145679881-e7e0b40c-abc2-4e9e-8c5b-08ef57e4b5fe.jpg)

![IMG_20210827_160616](https://user-images.githubusercontent.com/45510877/145680059-964a0c7d-da11-4ff3-a459-10f4fd953858.jpg)

![image](https://user-images.githubusercontent.com/45510877/147968529-dabde7eb-2713-4db0-83ad-20df5ebd808d.png)

**Comment by vladi1234** [comment]
>@MattWestb commented on 27 Aug
>
>You need one SWD / J-Link probe (if its one EFR32MG21 chip you need one real J-Link) for reading the flash of the Zigbee >module and if can dumping the internal flash pleas also dumping the "user data" that can having device specific setting for the >device.
>
>One working method: https://github.com/MattWestb/IKEA-TRADFRI-ICC-A-1-Module/tree/master/Flashing-MG
>
>I have dumped the tuya ZBGW (ist one EFR32MG1B) and one tuya LED Strip controller with EFR32MG21 and they was not >debug locked so dumping was working OK :-))

Best regards.
vladi1234

**Comment by MattWestb** [comment]
Some very brave Z2M and ZHA (and very likels no deCONZ) have rebricking ther IKEA remotes from bad firmware in this thred https://github.com/zigpy/zigpy/discussions/660#discussioncomment-1565541.


If some have one OK TRV then dump the main flash and userdata of the Zigbee module and you can flashing them on other devices with and its working great.

Only need one ESP or STM32 board and loading SWD probe firmware on it or is having one real J-Link probe.

**Comment by YoannLe** [comment]
Hi,

Did someone could dump the original firmware of Moes BRT-100-TRV?
If not I'll need to buy a new one with hope to save my 3 TRV with wrong OTA... But I'm not shure to success.

If the original firmware is dumped, do you now if it could bu push by OTA to faulty TRV?
Or will be need to be flashed manualy on each unit?
Does you know if the same full dumped image could reflashed or it will needed to edit some specifics values for each TRV?

I'll try to help ;)

BR,
Yoann

**Comment by vladi1234** [comment]
> If the original firmware is dumped, do you now if it could bu push by OTA to faulty TRV?
Or will be need to be flashed manualy on each unit?

Hi,
I think it has to be flashed manually because the defective ones are no longer paired with z2m.

**Comment by davrodfer** [comment]
Hi, I have new devices. How can I dump the original firmware and try to recover the brickeds devices?

**Comment by MattWestb** [comment]
More working method its depends what SWD / J-Tag you is having and the program you like using https://github.com/MattWestb/IKEA-TRADFRI-ICC-A-1-Module/tree/master/Flashing-MG.

The pads on the module is in the tuya space in the post before.

Normally only needed dumping the main flash but user data can being good to have if tuya have putting somthing in it.

**Comment by YoannLe** [comment]
> Hi, I have new devices. How can I dump the original firmware and try to recover the brickeds devices?

Got a new one today too, I'll try to dump the firmware and share my progress

**Comment by YoannLe** [comment]
![IMG_20220103_195420](https://user-images.githubusercontent.com/5211190/147968656-0f2a22a7-3af8-4a40-9af9-a52404c6b68a.jpg)
![IMG_20220103_195440](https://user-images.githubusercontent.com/5211190/147968663-ad1bf2e4-9e96-4353-9d9e-c2d15c191401.jpg)
Not easy to unglue without breaking the front acrylic glass....

**Comment by vladi1234** [comment]
Wiring inserted, see above:

https://github.com/Koenkk/zigbee2mqtt/issues/10140#issue-1077552450

**Comment by TomaszBich** [comment]
Fingers crossed!!!

**Comment by YoannLe** [comment]
Dump done, need to check them and reflash data/app dump on a break TRV.  Maybe tomorrow.

**Comment by MattWestb** [comment]
## Great !!
You need converting the bin file to elf if using GDB or with Silabs commander to s37 files.
The "user data" is also interesting but shall not being needed if restoring one device of the same type.

**Comment by YoannLe** [comment]
First, I use:
https://github.com/Jason2866/blackmagic-espidf
https://github.com/MattWestb/IKEA-TRADFRI-ICC-A-1-Module/tree/master/Flashing-MG

Best way to open the TRV: Small holes to get the srews 

Then open, get access to the tuya module:

 
`"c:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gdb.exe"
C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gdb.exe: warning: Couldn't determine a path for the index cache directory.
GNU gdb (GNU Arm Embedded Toolchain 10.3-2021.10) 10.2.90.20210621-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=i686-w64-mingw32 --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) target extended-remote 192.168.4.1:2022
Remote debugging using 192.168.4.1:2022
(gdb) mon sw
Target voltage: 3459mV
Available Targets:
No. Att Driver
 1      EFR32MG13P 220 F512 Mighty Gecko M3/M4
(gdb) att 1
Attaching to Remote target
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0x0002b2b2 in ?? ()
(gdb) mon efm_info
DI version 1 (silabs remix?) base 0x0fe08000

EFR32MG13P 220 F512 = Mighty Gecko 512kiB flash, 64kiB ram
Device says flash page size is 2048 bytes, we're using 2048 bytes

Radio si65535

(gdb) info mem
Using memory regions provided by the target.
Num Enb Low Addr   High Addr  Attrs
0   y   0x00000000 0x00080000 flash blocksize 0x800 nocache
1   y   0x0fe00000 0x0fe00800 flash blocksize 0x800 nocache
2   y   0x0fe10000 0x0fe14000 flash blocksize 0x800 nocache
3   y   0x20000000 0x20010000 rw nocache
(gdb)`

Then dump everything:

`dump memory BRT100_main.bin 0x00000000 0x00080000   
dump memory BRT100_user.bin 0x0fe00000 0x0fe00800  
dump memory BRT100_boot_bis.bin 0x0fe10000 0x0fe14000  
dump memory BRT100_ram.bin 0x20000000 0x20010000 `

Convert bin to elf:

`.\objcopy.exe --input-target binary --output-target elf32-little BRT100_main.bin BRT100_main.elf
.\objcopy.exe --input-target binary --output-target elf32-little BRT100_user.bin BRT100_user.elf`

We need the user config because GPIO are not good on the bricked TRV.

Load elf to a bricked TRV:
`(gdb) target extended-remote 192.168.4.1:2022
Remote debugging using 192.168.4.1:2022
(gdb) mon sw
Target voltage: 3462mV
Available Targets:
No. Att Driver
 1      EFR32MG13P 220 F512 Mighty Gecko M3/M4
(gdb) att 1
Attaching to Remote target
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0x0002b2b2 in ?? ()
(gdb) mon efm_info
DI version 1 (silabs remix?) base 0x0fe08000

EFR32MG13P 220 F512 = Mighty Gecko 512kiB flash, 64kiB ram
Device says flash page size is 2048 bytes, we're using 2048 bytes

(gdb) info mem
Using memory regions provided by the target.
Num Enb Low Addr   High Addr  Attrs
0   y   0x00000000 0x00080000 flash blocksize 0x800 nocache
1   y   0x0fe00000 0x0fe00800 flash blocksize 0x800 nocache
2   y   0x0fe10000 0x0fe14000 flash blocksize 0x800 nocache
3   y   0x20000000 0x20010000 rw nocache

(gdb) load BRT100_main.elf 0x0
Loading section .data, size 0x80000 lma 0x0
Start address 0x00000000, load size 524288
Transfer rate: 15 KB/sec, 987 bytes/write.
(gdb) load BRT100_user.elf 0x0fe00000
Loading section .data, size 0x800 lma 0xfe00000
Start address 0x00000000, load size 2048
Transfer rate: 11 KB/sec, 682 bytes/write.
`
TRV back to life and working fine now!

I share all dumps, and will add picts.
[Dumps.zip](https://github.com/Koenkk/zigbee2mqtt/files/7824268/Dumps.zip)

**Comment by vladi1234** [comment]
Great job!

**Comment by MattWestb** [comment]
## Great work done !!
If using Silabs Commander and converting it to s37 file is easier for users flashing it then its having all the offsets inside the file and can being flashed with most flash prebes and programs.
I was doing that with all IKEA remotes that was broken after bad OTA files in there test feed in the summer.

I taking on fast look in the user data file if its some interesting information :-))

**Comment by TomaszBich** [comment]
I'm impressed @YoannLe

**Comment by YoannLe** [comment]
> I'm impressed @YoannLe

Thanks to @vladi1234 @MattWestb  !
I only fallowed their advices and GitHub 🙂

**Comment by Styx85** [comment]
Only one question remains, if someone has a better way to open it than to drill holes into the front glass. @vladi1234  how did you open it? In your pictures, it looks like an intact front without holes.

**Comment by MattWestb** [comment]
Heating is normally working on glued plastic things but not too much !!

**Comment by vladi1234** [comment]
![10159Dc7vzy6mEJsAJ](https://user-images.githubusercontent.com/45510877/149595127-0b277e3f-a684-4481-9272-0bd0e50e993b.jpg)

I opened with a cutter knife. You have to make a long blade about 5cm and just carefully slide it in between the touch screen and the housing, but don't bend it away! Otherwise breaks. Afterwards you can glue them together again.

**Comment by Styx85** [comment]
Ok, thank you very much. It is done and unbricked. I attached some photos, because the cutter was a little bit rough for me. I used a hair dryer to warm up the glue and then a thinner credit card type cardboard (calendar that you get gifted by banks) and a toll I got decades ago to fit GU10 halogen lights. See the photos.
![IMG_20220115_195058](https://user-images.githubusercontent.com/32103696/149639271-550598db-cc89-49bb-b047-0b435d708a4c.jpg)
![IMG_20220115_195106](https://user-images.githubusercontent.com/32103696/149639273-fd69742c-55a1-4104-87fc-26008f98c87e.jpg)
![IMG_20220115_200555](https://user-images.githubusercontent.com/32103696/149639274-6eb2d275-0786-47cf-aec3-041a88a5da41.jpg)
![IMG_20220115_200605](https://user-images.githubusercontent.com/32103696/149639275-5a711150-af81-4787-9a05-303ceca48bec.jpg)

**Comment by vladi1234** [comment]
> What kind of glue @vladi1234 did you use to fix it again?

I took 4 small pieces of transparent Tesafilm 4 x 10 mm and glued them over the edge.
You can hardly see it, and in case you have to open it again, don't break it.



![IMG_20220116_094549](https://user-images.githubusercontent.com/45510877/149653417-d3d18866-967e-4d20-94ca-80130fdd568d.jpg)
![IMG_20220116_094647](https://user-images.githubusercontent.com/45510877/149653422-bc4425f2-6824-4b0d-b90f-1d323ab48313.jpg)

**Comment by Styx85** [comment]
Well, sounds like a solution, too. I just used some waterproof wood glue and pressurized the RV with some heavy books overnight.  Hope I do not have to open it again.

**Comment by TomaszBich** [comment]
Hi Guys,

Where I have to place the YoannLe's dumps? Which windows path?
![image](https://user-images.githubusercontent.com/74622130/150091042-83d0ab2d-3a07-4345-8593-727e8216faff.png)

**Comment by MattWestb** [comment]
If you dont providing one path in the load command its shall being in the same directory you was starting GDB. For making it easier you can doing one copy with name 1234.elf and its going faster writing ;-)

**Comment by TomaszBich** [comment]
Thank you @MattWestb - fixed!!!

**Comment by vladi1234** [comment]
Hello,
Plastic hooks on my TRV broke off by themselves, so TRV cannot regulate the temperature down.

![IMG_20220219_080359](https://user-images.githubusercontent.com/45510877/154790808-a16b903e-aa42-4ad2-90e4-3a98ae973bcf.jpg)

**Comment by sgilyin** [comment]
> First, I use: https://github.com/Jason2866/blackmagic-espidf https://github.com/MattWestb/IKEA-TRADFRI-ICC-A-1-Module/tree/master/Flashing-MG
> 
> Best way to open the TRV: Small holes to get the srews
> 
> ![IMG_20220106_073705](https://user-images.githubusercontent.com/5211190/148440911-828fb0f6-0bf5-48bc-a613-707639e7bf14.jpg) ![IMG_20220106_073641](https://user-images.githubusercontent.com/5211190/148440916-79a4b2c7-2a9c-4b54-b598-37c6bb0ad0d2.jpg) ![IMG_20220106_073626](https://user-images.githubusercontent.com/5211190/148440919-44ff3fdb-a08d-480b-9029-8e7d60a6afbe.jpg)
> 
> Then open, get access to the tuya module:
> 
> ![IMG_20220106_065206](https://user-images.githubusercontent.com/5211190/148440979-2b122cac-8405-422d-937c-ce01202d8d6a.jpg) ![IMG_20220105_204236](https://user-images.githubusercontent.com/5211190/148440984-bf9833d4-2b6c-4b37-8509-ab0bbd1575a6.jpg)
> 
> ```
>  
> `"c:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gdb.exe"
> C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gdb.exe: warning: Couldn't determine a path for the index cache directory.
> GNU gdb (GNU Arm Embedded Toolchain 10.3-2021.10) 10.2.90.20210621-git
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> Type "show copying" and "show warranty" for details.
> This GDB was configured as "--host=i686-w64-mingw32 --target=arm-none-eabi".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <https://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
>     <http://www.gnu.org/software/gdb/documentation/>.
> 
> For help, type "help".
> Type "apropos word" to search for commands related to "word".
> (gdb) target extended-remote 192.168.4.1:2022
> Remote debugging using 192.168.4.1:2022
> (gdb) mon sw
> Target voltage: 3459mV
> Available Targets:
> No. Att Driver
>  1      EFR32MG13P 220 F512 Mighty Gecko M3/M4
> (gdb) att 1
> Attaching to Remote target
> warning: No executable has been specified and target does not support
> determining executable automatically.  Try using the "file" command.
> 0x0002b2b2 in ?? ()
> (gdb) mon efm_info
> DI version 1 (silabs remix?) base 0x0fe08000
> 
> EFR32MG13P 220 F512 = Mighty Gecko 512kiB flash, 64kiB ram
> Device says flash page size is 2048 bytes, we're using 2048 bytes
> 
> Radio si65535
> 
> (gdb) info mem
> Using memory regions provided by the target.
> Num Enb Low Addr   High Addr  Attrs
> 0   y   0x00000000 0x00080000 flash blocksize 0x800 nocache
> 1   y   0x0fe00000 0x0fe00800 flash blocksize 0x800 nocache
> 2   y   0x0fe10000 0x0fe14000 flash blocksize 0x800 nocache
> 3   y   0x20000000 0x20010000 rw nocache
> (gdb)`
> ```
> 
> Then dump everything:
> 
> `dump memory BRT100_main.bin 0x00000000 0x00080000 dump memory BRT100_user.bin 0x0fe00000 0x0fe00800 dump memory BRT100_boot_bis.bin 0x0fe10000 0x0fe14000 dump memory BRT100_ram.bin 0x20000000 0x20010000 `
> 
> Convert bin to elf:
> 
> `.\objcopy.exe --input-target binary --output-target elf32-little BRT100_main.bin BRT100_main.elf .\objcopy.exe --input-target binary --output-target elf32-little BRT100_user.bin BRT100_user.elf`
> 
> We need the user config because GPIO are not good on the bricked TRV.
> 
> Load elf to a bricked TRV:
> 
> ```
> `(gdb) target extended-remote 192.168.4.1:2022
> Remote debugging using 192.168.4.1:2022
> (gdb) mon sw
> Target voltage: 3462mV
> Available Targets:
> No. Att Driver
>  1      EFR32MG13P 220 F512 Mighty Gecko M3/M4
> (gdb) att 1
> Attaching to Remote target
> warning: No executable has been specified and target does not support
> determining executable automatically.  Try using the "file" command.
> 0x0002b2b2 in ?? ()
> (gdb) mon efm_info
> DI version 1 (silabs remix?) base 0x0fe08000
> 
> EFR32MG13P 220 F512 = Mighty Gecko 512kiB flash, 64kiB ram
> Device says flash page size is 2048 bytes, we're using 2048 bytes
> 
> (gdb) info mem
> Using memory regions provided by the target.
> Num Enb Low Addr   High Addr  Attrs
> 0   y   0x00000000 0x00080000 flash blocksize 0x800 nocache
> 1   y   0x0fe00000 0x0fe00800 flash blocksize 0x800 nocache
> 2   y   0x0fe10000 0x0fe14000 flash blocksize 0x800 nocache
> 3   y   0x20000000 0x20010000 rw nocache
> 
> 
> (gdb) load BRT100_main.elf 0x0
> Loading section .data, size 0x80000 lma 0x0
> Start address 0x00000000, load size 524288
> Transfer rate: 15 KB/sec, 987 bytes/write.
> (gdb) load BRT100_user.elf 0x0fe00000
> Loading section .data, size 0x800 lma 0xfe00000
> Start address 0x00000000, load size 2048
> Transfer rate: 11 KB/sec, 682 bytes/write.
> ```
> 
> TRV back to life and working fine now!
> 
> I share all dumps, and will add picts. [Dumps.zip](https://github.com/Koenkk/zigbee2mqtt/files/7824268/Dumps.zip)

How can I do that with esp32?

**Comment by phyesix** [comment]
I'm pretty new at this myself. I have an ESP32 board. I don't know how to flash it. Is there anyone who can prepare a detailed guide? @Styx85 @MattWestb @YoannLe 😇

**Comment by chuntin** [comment]
Can someone explain for dummies how to fix the trv's!

**Comment by paulandrewcrouch** [comment]
Does anyone have a copy of the original firmware?   I have some on version -1 and some on version 67, with only those on 67 asking for to upgrade to 192.   It's all very puzzling.   I can't seem to control all of them either, but it seems to be a mixture.   Worrying given the money I've spent on them.   v67 appears to work.

**Comment by jonathan-gatard** [comment]
Hi everybody,

Solution can be found here [https://github.com/Koenkk/zigbee2mqtt/issues/19173](url)
