### ISSUE TITLE
Help, suddenly it didn't work anymore

### ISSUE THREAD

**Issue by leardinet** [Koenkk/zigbee2mqtt#10155]
suddenly it didn't work anymore

my configuration
Home Assistant OS 7.0
Home Assistant 2021.12.0
Zigbee2mqtt
Current version: 1.22.1-1
lumi.gateway.mgl03 ZNDMWG03LM
da Xiaomi
Firmware: 1.5.1_0032 

my configuration
`data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: tcp://192.168.1.86:8888
  adapter: ezsp
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
`

log:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[16:07:54] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[16:07:54] INFO: MQTT available, fetching server detail ...
[16:07:54] INFO: MQTT server settings not configured, trying to auto-discovering ...
[16:07:54] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[16:07:54] INFO: MQTT credentials not configured, trying to auto-discovering ...
[16:07:54] INFO: Configuring'addons' mqtt user
[16:07:54] INFO: Previous config file found, checking backup
[16:07:54] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[16:07:54] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:07:54] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.1 start
> node index.js
Zigbee2MQTT:info  2021-12-12 16:07:56: Logging to console and directory: '/config/zigbee2mqtt/log/2021-12-12.16-07-55' filename: log.txt
Zigbee2MQTT:info  2021-12-12 16:07:56: Starting Zigbee2MQTT version 1.22.1 (commit #unknown)
Zigbee2MQTT:info  2021-12-12 16:07:56: Starting zigbee-herdsman (0.13.176)`

**Comment by Hedda** [comment]
> lumi.gateway.mgl03 ZNDMWG03LM

Are you running it in "zigbee2mqtt mode" (Z2M native on Xiaomi Gateway 3) or "zigbee home automation-mode" (serial stream server as pass-through remote Zigbee adapter to a seperate stand-alone Z2M installation somewhere else on the local network)?

https://github.com/AlexxIT/XiaomiGateway3#zigbee2mqtt-mode

https://github.com/AlexxIT/XiaomiGateway3#zigbee-home-automation-mode

Anyway, you need to understand that EZSP support is still in a very experimental phase so if it looks more likly the issue is directly related to the "EZSP" implementation in zigbee-herdsman and not other Z2M issue then you should post your feedback here:

https://github.com/Koenkk/zigbee-herdsman/issues/319

I am not even sure if developer(s) is currently actively working on improving or maintaining that experimental EZSP support(?).

Only clear tips is to try upgrade EmberZNet NCP UART EZSP firmware Zigbee firmware version 6.7.9 or later and test dev branch (a.k.a. Edge):

https://github.com/arendst/Tasmota/tree/development/tools/fw_SonoffZigbeeBridge_ezsp

https://github.com/Koenkk/zigbee2mqtt/tree/dev

There looks to be some ezsp related fixes in the zigbee-herdsman dependency that might have not yet made it into Z2M dev/edge yet:

https://github.com/Koenkk/zigbee-herdsman/

Regardless you still want to direct most if not all feedback and issues to subscribers of the WIP discussion in the zigbee-herdsman repo:

https://github.com/Koenkk/zigbee-herdsman/issues/319

Also, please take note that WiFi based Zigbee bridges like ITead Sonoff ZBBridge are generally not recommended with the EZSP protocol. See the warnings about it:

https://www.zigbee2mqtt.io/guide/adapters/#notes

WiFi-based Serial-to-IP bridges are not recommended for Silicon Labs EZSP adapters as the serial protocol does not have enough fault-tolerance to handle packet loss or latency delays that can normally occur over WiFi connections. If cannot use a locally connected USB or UART/GPIO adapter then the recommendation is to use remote adapter that connected via Ethernet (wired) to avoid issues with EZSP caused by WiFi connections.

https://www.zigbee2mqtt.io/advanced/remote-adapter/connect_to_a_remote_adapter.html

WiFi-based Serial-to-IP bridges are not recommended for Silicon Labs EZSP adapters as the serial protocol does not have enough fault-tolerance to handle packet loss or latency delays that can normally occur over WiFi connections.

More warning about Zigbee to WiFi bridges for EZSP is not recommended for production as it does not do well with packed loss:

https://github.com/zigpy/bellows#warning-about-zigbee-to-wifi-bridges

https://www.home-assistant.io/integrations/zha/#warning-about-wi-fi-based-zigbee-to-serial-bridgesgateways

FYI, I also understand that the EFR32 board antenna design of the "SM-011 V1.0" Zigbee module used inside ITead's Sonoff ZBBridge have very high receive sensitivity to electromagnetic interference (EMI) / radio-frequency interference. This means that it will be extra important to keep it away from any other electronic devices or appliances that may generate an electromagnetic field (EM Field) or send our interfering radio signals. That includes the computer that you run your home automation application software on as well as any devices such as for example external harddrives or storage devices, power-supplies, etc., and of course any Wi-Fi access points or routers nearby.

Note! The new ITead Zigbee 3.0 USB Dongle Model: 9888010100045 (Hardware Revision Version 1.3) circuit board share the same type of antenna design so its radio is as well extremely sensitive to signal interference on its receiving end. The current recommendation for using it is to connect it via a long USB extension cable and try to move it as far away from all electronics and other possible sources of signal interference.

PS: Another general tip that always applies when building a Zigbee network is to begin by adding a few good mains-powered Zigbee router devices so that they will make use a stable baseline. Many start by buying three "IKEA TRADFRI Signal Repeater" (E1746).

https://zigbee.blakadder.com/Ikea_E1746.html

https://www.ikea.com/us/en/p/tradfri-signal-repeater-30400407/

https://www.ikea.com/gb/en/p/tradfri-signal-repeater-80424255/

https://www.ikea.com/se/sv/p/tradfri-signalfoerstaerkare-10400408/
