### ISSUE TITLE
Error reporting in MQTT message

### ISSUE THREAD

**Issue by pepp86** [Koenkk/zigbee2mqtt#1123]
Hi,

is it possible to report error from devices within the MQTT message? For example if the server responds with "Mac no ack" while trying to switch a device?

If so, my home automation can trigger on that and report the issue to me or try to switch on/off again.

**Comment by andreasbrett** [comment]
Great idea! Would be very helpful. Not sure if it's better to have this on a per-device basis or globally. For my use-case it would be better to have an error message in the log subtree rather than having one additional error attribute for each device (as I would have to configure my home automation system to watch for ALL of them).

**Comment by Koenkk** [comment]
Implemented, example of the message published to MQTT: https://hastebin.com/lakubupume.apache

**Comment by andreasbrett** [comment]
Looks good, will use that in my smart home setup. Thanks for this rapid implementation!

**Comment by pepp86** [comment]
Great! Awesome fast Implementation. 

Now I only need to get the dev tree up and running on my environment :-)
