### ISSUE TITLE
Serve device icons locally

### ISSUE THREAD

**Issue by nohn** [Koenkk/zigbee2mqtt#11908]
### What happened?

Since updating to 1.24.0-dev commit: 02bc325, device Icons are wrong:

![image](https://user-images.githubusercontent.com/113465/159153815-d1603cb0-2428-4686-97be-b3f589194c79.png)

### Zigbee2MQTT version

 1.24.0-dev commit: 02bc325

### Adapter firmware version

20210708

### Adapter

Slaesh's CC2652RB Stick

**Comment by mpuff** [comment]
I have this problem also with the stable version 1.24.0

**Comment by GerdRuetten** [comment]
The webserver under https://www.zigbee2mtqq.io is down and this response to wrong devie icons

**Comment by nohn** [comment]
Is there a reason, the icons aren't distributed with the software and loaded locally?

**Comment by GerdRuetten** [comment]
> Is there a reason, the icons aren't distributed with the software and loaded locally?

Imho the reason is the fast integration of new devices.

So it's easier to serve the images and other informations from a central server, than allways update a local instance.

**Comment by nohn** [comment]
That doesn't make sense to me: For new device support the local instance has to be updated anyway.

**Comment by sjorge** [comment]
Having the option to fetch the icons locally, say by installing an extra npm module or something would indeed be great.
Even if the missing icons don't bother you, the delay before it gives up trying to fetch them slows down the entire frontend.

**Comment by Koenkk** [comment]
zigbee2mqtt.io seems up again so this should be fixed.

**Comment by itec78** [comment]
I think that getting images from zigbee2mqtt.io could be used for tracking and a profiling users and devices.
It would be better to have all the files locally.

**Comment by itec78** [comment]
I don't know what are the next steps to follow.
Maybe a new issue can be created, asking to serve images locally instead of using zigbee2mqtt.io website?
I found that there are 2054 images, for a total of 12,4 MB. I think it's not a problem serving them locally.
https://github.com/Koenkk/zigbee2mqtt.io/tree/master/public/images/devices

**Comment by WoLpH** [comment]
Another vote here for serving them locally...

The current implementation is quite annoying in my case:
My modem is near the cable connection which is outside of my house. To be able to power cycle the device remotely, I've connected it to a zigbee switchable plug. As you can probably guess... this needs to happen when my internet is down so I can't reach the server at that point and the web interface stalls for a few minutes because of it.

As a workaround I've blocked the image url with umatrix, but that's just annoying :)

**Comment by WoLpH** [comment]
bump for a fix that only includes local resources

**Comment by itec78** [comment]
I found that the code that points to external address is here:
https://github.com/nurikk/zigbee2mqtt-frontend/blob/dev/src/components/device-image/index.tsx#L19
Is ok to have the issue here, or is it better to open it in frontend? (https://github.com/nurikk/zigbee2mqtt-frontend)

I think that 2 steps are required:
1) copy the images from https://github.com/Koenkk/zigbee2mqtt.io/tree/master/public/images/devices to local path. (could be done somewhere here https://github.com/nurikk/zigbee2mqtt-frontend/blob/dev/.github/workflows/release.yml)
2) change the getZ2mDeviceImage variable to point local resources

After that the changes will be deployed to zigbee2mqtt automatically
https://github.com/Koenkk/zigbee2mqtt/blob/master/.github/workflows/update_frontend.yml#L17

Am I wrong?

**Comment by nohn** [comment]
There is already an issue open and the frontend project: https://github.com/nurikk/zigbee2mqtt-frontend/issues/1477

**Comment by WoLpH** [comment]
@nohn does the other issue make this one obsolete?

**Comment by nohn** [comment]
.

**Comment by itec78** [comment]
I think this issue is never obsolete until it will be solved. There's a privacy problem. And doesn't make sense to have remote contents on a fully local application.

**Comment by nohn** [comment]
@itec78 you are 100% correct. But technically speaking this isn't an issue in zigbee2mqtt and can't be fixed there but needs to be fixed in [zigbee2mqtt-frontend](https://github.com/nurikk/zigbee2mqtt-frontend): https://github.com/nurikk/zigbee2mqtt-frontend/issues/1477

**Comment by Hypfer** [comment]
https://github.com/nurikk/zigbee2mqtt-frontend/blob/a2e3dc31110b33aa5fe38e5e8ec7970aabf315bf/src/components/device-image/index.tsx#L19

What's stopping anyone from extending this function (that already exists!) to take an optional configuration parameter into account where you can specify a custom asset host?
That can't be more annoying than fighting with the stale bot
