### ISSUE TITLE
new Nyce and Smartthings devices added

### ISSUE THREAD

**Issue by ReneHonig** [Koenkk/zigbee2mqtt#1215]
Hi Koen,

I have created a pull request for a number of new devices (Nyce and Smartthings).
I have also created the mappings for HA integration (see below).
I have not created a pull request for those, as only '3305-S' and '3300-S' seem to work (don't know why)
Any ideas?

Best, Rene

    '3043': [
        configurations.binary_sensor_occupancy, configurations.sensor_temperature,
        configurations.sensor_battery, configurations.binary_sensor_battery_low,
    ],
    'motionv4': [
        configurations.binary_sensor_occupancy, configurations.sensor_temperature,
        configurations.sensor_battery, configurations.binary_sensor_battery_low,
    ],
    '3305-S': [
        configurations.binary_sensor_occupancy, configurations.sensor_temperature,
        configurations.sensor_battery, configurations.binary_sensor_battery_low,
    ],
    '3300-S': [
        configurations.sensor_temperature, configurations.binary_sensor_contact,
        configurations.sensor_battery, configurations.binary_sensor_battery_low,
    ],

**Comment by Koenkk** [comment]
Hi Rene!

In `homeassistant.js` the `model` should be used, not the `zigbeeModel`.

Anyway, I've update zigbee2mqtt to use the latest zigbee-shepherd-converters (which also forces me to add the home assistant configuration, otherwise tests fails).

All devices are supported in the dev branch now :smile: 

Thanks!
