### ISSUE TITLE
Devices that are switched off block the network

### ISSUE THREAD

**Issue by schattenkrieger** [Koenkk/zigbee2mqtt#12243]
### What happened?

When a device that is still part of the zigbee network and is reciving commands get switched off after a while the whole network gets blocked.

mostly my network consists of lightbulbs behind "dumb" wall switches and motion sensors. I have a adaptive light solution running, so around every 15 minute my lights get a command to change the color temperature. that all works great and mostly flawless.
the problems start when someone switches off a light with the wall switch instead of relaying on the automation. after a few hours the whole networks gets slower and slower up to the point where it is not reacting at all anymore. 
when the light gets switched on after a few days or even weeks, it looks like all the blocked commands get send in rapid succession. 
when i look in the logs it looks like zigbee2mqtt is so busy tring to resend the messages to the switched off device(s) that it is unable to process new commands.
is there any way to tell zigbee2mqtt to stop trying to resend, or even ignore unreachable devices?

sadly right now i am not at home and have no easy way of accessing the installation. so i cant post detailed version numbers or logs.
i am running zigbee2mqtt:latest-dev via docker und update it regulary with watchtower. so i assume i run the most recent version 

### Zigbee2MQTT version

1.25.0-dev

### Adapter firmware version

20190619

### Adapter

CC2532

**Comment by Midifreakz** [comment]
I know the issue is closed, but I wanted to share my experience for anyone passing by.

I also have seen this behavior when devices are still listed but not powered. Like when switching out light bulbs, stop using an extender, switching batteries. I would advise anyone to just kick unused devices of the network. I feel like this improves stability.

@schattenkrieger > Maybe switch out the dumb wall switches for something like zigbee remotes or smart switches. Having dumb switches wired to smart bulbs is always a recipe for frustration.
