### ISSUE TITLE
Flash cc2531 with raspberry

### ISSUE THREAD

**Issue by jmichault** [Koenkk/zigbee2mqtt#1289]
Hello,
I have successfully flashed my CC2531 directly connected to my Raspberry pi3.
For those interested, software and code is available at https://github.com/jmichault/flash_cc2531.

**Comment by tb-killa** [comment]
Hi nice, does this mean we could use the rpi serial for data transfer too?
@Koenkk this could help build some sort of update routine inside zigbee2mqtt.
I think about something like a mqtt topic where we could bring the device to bootloader and flash, after reset we run with the Z2M instance again.

**Comment by Koenkk** [comment]
@jmichault awesome! would you mind adding this to the docs? https://github.com/Koenkk/zigbee2mqtt.io/blob/master/information/alternative_flashing_methods.md

@tb-killa this is the same as using the CC debugger (but now without the debugger), you also need to connect DC and DD pins. In order to have such a function updating should be possible without connecting this (only via USB port).

**Comment by keitetran** [comment]
I tried and succeeded. No need to have hardware debuger
Please update your pin map.

**Comment by VincentMasselis** [comment]
I'm trying but my CC2531 green led turns off when I call `./cc_chipid`.

![IMG_20190323_163236](https://user-images.githubusercontent.com/6769250/54868125-61e88f00-4d89-11e9-9b02-128e6e707a24.jpg)

I figured out that my chip led also turns off when I press the "reset" button on my CC Debugger.

Any idea ?

**Comment by timdonovanuk** [comment]
Out of interest, how long does it take to flash using a Pi? Absolutely amazing work, well done :) 👍
