### ISSUE TITLE
Woox R7060 : Battery information are not returned

### ISSUE THREAD

**Issue by pganansia** [Koenkk/zigbee2mqtt#13626]
### What happened?

In the frontend of Zigbee2MQTT or in Home assistant integration, battery level information is not retrieved.

Type d'appareil             EndDevice
Modèle Zigbee              TS0101
Constructeur Zigbee    _TZ3210_eymunffl
Description                   Smart garden irrigation control
Supporté                       Supporté
Adresse IEEE                0x50325ffffe3620a0
Adresse réseau            0xC669
Constructeur                [Woox](https://www.zigbee2mqtt.io/supported-devices/#v=Woox)
Modèle                          [R7060](https://www.zigbee2mqtt.io/devices/R7060.html#woox-r7060)
**Alimentation                 %**
Entretien terminé.        Vrai

### What did you expect to happen?

Having battery information

### Zigbee2MQTT version

1.27.0 commit: a9b8808

### Adapter firmware version

20211217

### Adapter

SONOFF zStack3x0

### Debug log

{
    "linkquality": 83,
    "state": "OFF",
    "battery": null,
    "device": {
        "applicationVersion": 69,
        "dateCode": "",
        "friendlyName": "robinet_jardin_lavandes",
        "hardwareVersion": 1,
        "ieeeAddr": "0x50325ffffe3620a0",
        "manufacturerID": 4098,
        "manufacturerName": "_TZ3210_eymunffl",
        "model": "R7060",
        "networkAddress": 50793,
        "powerSource": "Battery",
        "stackVersion": 0,
        "type": "EndDevice",
        "zclVersion": 3
    }
}

**Comment by Remko76** [comment]
I initially had this problem as well. At some point I managed to use the dev console and query the device which returned the battery information. But...I had to resetup my network and repair all the devices, and ever since, I am not able to retrieve the correct battery status. If I use the dev console to query the Battery percentage remaining, I get this:
![image](https://user-images.githubusercontent.com/75678314/187182999-ff2411ee-24d3-4beb-9c4e-07bd48908735.png)

Also, in the "exposes" tab, it shows one less entry as in the past, in the past it also showed Battery Voltage.
![image](https://user-images.githubusercontent.com/75678314/187183107-a4e2da8a-bdb1-436a-b2f6-4294a5f0c746.png)

I am running the latest Dev Build of Z2M (I think it is 1.25.2-dev). Just reinstalled and used the latest available.
