### ISSUE TITLE
"Adapter disconnected, stopping" for CC2652 Gio-dot Z-Bee-Duo

### ISSUE THREAD

**Issue by Picchios** [Koenkk/zigbee2mqtt#13931]
### What happened?

I have 2 zigbee coordinator in the same local network (one in home, one in the garage, but at a great distance from each other).
They are configured with static IP (.31 and .32) with 2 container in QNAP system (zigbee2mqtt-garage and zigbee2mqtt-soggiorno), I have HA Core installed on docker (2022.7 version).
Sometimes, randomly, one container crashes and fall off. So I must restart the container and it works properly, until it crashes again and so on. This fact happens about 1-2 times a day for the coordinator of the garage and 1 time every 2-3 days for the coordinator of the home. I tried to change channel (even if the two zb net are far), but the problem remains (now I have ch 11 for the garage and ch 15 for the home). The broker obviously is the same and the thing that change is the port of the frontend, so I can reach the page of the two z2m.

I even tried to erase and redo the containers, with no results. I don't know what to do...
Thanks for the help.

### What did you expect to happen?

I expect that they work without crashing

### How to reproduce it (minimal and precise)

It's totally random.

### Zigbee2MQTT version

1.27.0

### Adapter firmware version

20211217 (soggiorno) and 20220219 (garage)

### Adapter

Z-Bee-Duo

### Debug log

![fail](https://user-images.githubusercontent.com/97951117/189279726-fce1fe14-043c-45fe-a4c2-225b49724688.JPG)

**Comment by andreasbrett** [comment]
Having the same issue. Once a day Z2M quits because of the adapter is disconnected. Unfortunately the Z2M docker container does NOT come back up again on its own although it is configured to "restart: always". This is really annoying since simply restarting the container fixes everything.

Here's the log output:

error 2022-11-01 11:23:31: Adapter disconnected, stopping
info  2022-11-01 11:23:31: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
info  2022-11-01 11:23:31: Disconnecting from MQTT server 2022-11-01 11:23:31: Stopping zigbee-herdsman...
error 2022-11-01 11:23:31: Failed to stop Zigbee2MQTT
