### ISSUE TITLE
Linking Tradfri bulb and dimmer in HA

### ISSUE THREAD

**Issue by eflemingtra** [Koenkk/zigbee2mqtt#1404]
Hi,

Got both a Tradfri Bulb and Tradfri wireless dimmer into Home Assistant via zigbee2mqtt no problems.  I first got the dimmer paired to HA, then the bulb, then paired the dimmer to the bulb as per IKEA's instructions.

However, physically using the dimmer is not updating the state of the bulb in HA. I can turn the bulb off/on in HA and change colour/brightness fine. But if I dim the bulb with the physical dimmer or switch the light off with the dimmer, that is not reflected in HA.

Is there some further configuration I need to do, or is this just how this is at the moment?

**Comment by andreasbrett** [comment]
Zigbee2MQTT won't know about those changes as both devices are talking directly to each other. There are 2 ways to get what you want:

1) enable reporting so that the IKEA bulb will report to the coordinator that its value(s) changed. Not sure though if reporting works with IKEA bulbs. 

2) don't bind the dimmer to the bulb itself but rather pair it with the coordinator. You would then need to create a rule in HA that would react upon changes in the dimmer and send the corresponding changes to the bulb. I'm an openHAB user so I don't know HA very well. Not sure how you would do this in HA but there should be some logic to react upon state changes in one device and apply some settings on another device.

**Comment by andreasbrett** [comment]
Check those 2 FAQ entries for binding and reporting. Binding is what you manually did (=pairing 2 devices directly without coordinator). Reporting is the feature where devices report state changes to the coordinator.

https://www.zigbee2mqtt.io/information/binding.html
https://www.zigbee2mqtt.io/information/report.html

**Comment by eflemingtra** [comment]
Thanks for that, makes perfect sense. I'll look into it and see what the best (easiest) solution will be for me.

**Comment by eflemingtra** [comment]
Just an update if anyone else is in my position, yes, reporting does work with the TRADFRI bulb. Follow the guide from the link https://www.zigbee2mqtt.io/information/report.html, restart Zigbee2MQTT and it works to report the state of the bulb to Home Assistant whenever you use the physical dimmer.
