### ISSUE TITLE
Identified as wrong device

### ISSUE THREAD

**Issue by Dustin36** [Koenkk/zigbee2mqtt#14274]
### What happened?

I recently bought the GIDEALED ZC05M from Amazon, but z2m identifies it as GIDERWEL ZCRGB012.
Is there any to correct this?

### Zigbee2MQTT version

1.28.0

### Adapter firmware version

6.10.3.0 build 297

### Adapter

SONOFF Zigbee Gateway, ZBDongle-E

**Comment by danieledwardgeorgehitchcock** [comment]
I am looking at the device converters for these units in the Z2M source and they appear to have two different fingerprints. 2 questions:

1) Can you trust that the Amazon source has sent you what you actually purchased?
2) Could you post up the database.db entry for the device so that we can investigate further?

Functionally, they look very similar so, you shouldn't have much of an issue with the control / difference in units - it may well be that the brand has switched to whitelabeling another device..
