### ISSUE TITLE
Philips Hue Buckram spotlight 929003048301 not recognized

### ISSUE THREAD

**Issue by thbe51** [Koenkk/zigbee2mqtt#14455]
### Link

https://www.philips-hue.com/en-gb/p/hue-white-ambiance-buckram-quadruple-spotlight/8719514339163#specifications

### Database entry

?

### Comments

This seems to be "Generation 2" of Philips 5047430P6. Same hardwavre but unrecognized. Other bulbs perhaps?

**Comment by danieledwardgeorgehitchcock** [comment]
I've created a PR - the difference appears to be Bluetooth. The modern model generations also seem to differ between device color. I have kept it generic for now, but the description may change if the model id differs between white and black fixtures

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

I am not sure what you are trying to do here.

In order to use the change that was merged, you need to swap to the Dev branch of Z2M following [this guide](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

I am using this branch with many Philips Hue products so, I can confirm that the paths don't need to be modified from being relative to full which is what you appear to be doing above.

I also see that you mention that your fixture has 3 bulbs whereas the link you copied above is a quad unit - the model number also corresponds with a quad unit.

Please try switching to the Dev branch first and see if that resolves your issues
