### ISSUE TITLE
[New device support]: TRÄDFRI bulb E14 WS globe 470lm

### ISSUE THREAD

**Issue by brunocrvlh** [Koenkk/zigbee2mqtt#14593]
### Link

https://www.ikea.com/pt/en/p/tradfri-led-bulb-e14-470-lumen-smart-wireless-dimmable-white-spectrum-globe-70518179/

### Database entry

I don't know how to see that

### Comments

I just bought a new bulb from ikea but for some reason it shows up as "not supported". Tried to reset the bulb multiple times but nothing changed.

### Supported color modes

Adjustable white tones

**Comment by Koenkk** [comment]
Can you make a screenshot of the z2m frontend -> device page? I need the modelID of this bulb.

**Comment by brunocrvlh** [comment]
sure! this? 
![D971A58F-C4F2-4A0A-BA3D-D4DD32D59854](https://user-images.githubusercontent.com/69170600/197389317-bed7b405-a84d-4752-bb18-cb62c72fcaa6.png)

**Comment by Koenkk** [comment]
Should be supported in z2m 1.28.0

**Comment by brunocrvlh** [comment]
Thanks! btw, is there any documentation on how to see my z2m version and how to upgrade it?

**Comment by Koenkk** [comment]
Version is under frontend -> settings -> about.
Regarding upgrading it depends on how you run z2m. For e.g. bare metal installation see https://www.zigbee2mqtt.io/guide/installation/01_linux.html#for-later-update-zigbee2mqtt-to-the-latest-version

Since this device is already supported in the latest z2m I will close this.
