### ISSUE TITLE
TV02-Zigbee local_temperature_calibration

### ISSUE THREAD

**Issue by iksrd** [Koenkk/zigbee2mqtt#14814]
### What happened?

TV02-Zigbee local_temperature_calibration passes values independently
![Снимок экрана от 2022-11-04 23-15-581](https://user-images.githubusercontent.com/81743791/200067533-512e5e42-ddc2-441a-8a36-1680f652f4c0.png)

### What did you expect to happen?

If I set "0" then "0" will remain

### How to reproduce it (minimal and precise)

Set "0" and just watch for a while

### Zigbee2MQTT version

1.28.1

### Adapter firmware version

20211217

### Adapter

zStack3x0

**Comment by vladyspavlov** [comment]
I can't reproduce it on my TRV.
Here's a history for the last 5 days, there are no issues.
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/16994749/200134411-b8b46d25-7bb6-4b2a-a375-76dc9b14972a.png)
</details>

Do you have any automations for this entity? Are you sure that it doesn't change because of any automation?
Could you provide the manufacturer ID of the device, please?

**Comment by misha1183** [comment]
Здравствуйте. Можно увеличить значение Local temperature colibration до значений от -15 до 15? TV02 стоит на радиаторе отопления и калибровка нужна на бОльшие значения. Сейчас необходимо -9,2 градуса.
