### ISSUE TITLE
Zemismart ZM25TQ Not showing correct Power Info

### ISSUE THREAD

**Issue by dsduarte** [Koenkk/zigbee2mqtt#14869]
### What happened?

I have recently added 2 new tubular motor on my network and one of them is not showing the power icon properly (as showing on image).
I have tryied to remove/add several times and got the same result.
![z2m-motor](https://user-images.githubusercontent.com/19639490/200435447-5d951d17-1a9c-4ca8-b840-f4062d6c3e6f.png)

### What did you expect to happen?

Both devices should apears with correct power info.

### How to reproduce it (minimal and precise)

by adding ZM25TQ devices.

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

20211217

### Adapter

Sonoff Zigbee Dongle

**Comment by mdehaas** [comment]
Please refer to [Supporting new devices](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html) to help collect the information or even provide the external filter to add this information to the relevant project. 
Otherwise post the debug logs containing cluster information here.
