### ISSUE TITLE
BRT-100-TRV no system_mode off available

### ISSUE THREAD

**Issue by Heire** [Koenkk/zigbee2mqtt#15462]
### What happened?

Since one of the last updates there was an issue with the system_mode that got fixed however the options to adapt system_mode to "off" is gone. It used to work as i had an automation to stop the TRV to work during the night.

### What did you expect to happen?

system_mode should have at least the options "off|auto|heat"

### How to reproduce it (minimal and precise)

Since latest release

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

20211217

### Adapter

zStack3x0

**Comment by mhoogenbosch** [comment]
Is there a reason this feature request isn't taken into account? Because it look 'ugly' on the dashboard.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/36899598/f760ca29-89fb-4794-a0f3-cfafea3b3cdf)

Even though it is turned to 5 degrees, which is the only way to turn it 'off' it is still heating, which is obvious because it is in heating mode. The valve is closed.
