### ISSUE TITLE
Z2M downloaded wrong firmware updates ?

### ISSUE THREAD

**Issue by purposestesting** [Koenkk/zigbee2mqtt#15649]
### What happened?

I bought a few popp 701721 (similar to danfoss ally) thermostat valves and integrated them to home assistant. They allow ota updates which i did. They all had initial the firmware "01.12.0008 01.12". Now a few trv´s have version "01.18.0008 01.18" with firmware-date "20220928" which is the latest, some other have an unknown version "AAAABBBBCCCCDDDD" with firmware-date "20220928". I already tried to change the state.json file, change the firmware-version "AAAABBBBCCCCDDDD" to the initial 1.12 one and update again, but that did not work.

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

20210708

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

### Debug log

![danfoss-ally-firmwares](https://user-images.githubusercontent.com/119529394/208475988-0afa202c-3c73-4190-8879-ea9715e20281.png)

![home-assistant_z2m](https://user-images.githubusercontent.com/119529394/208476000-ea557c5a-7d6a-48b8-b59e-8a4c0950d6c6.png)

[config_entry-hassio-117a26895d5aad91aae05fdb853929e2.json.txt](https://github.com/Koenkk/zigbee2mqtt/files/10261083/config_entry-hassio-117a26895d5aad91aae05fdb853929e2.json.txt)

[state.json.txt](https://github.com/Koenkk/zigbee2mqtt/files/10261086/state.json.txt)

**Comment by lux73** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/11049

in short: remove them from z2m & do a fresh pairing should do the Trick

**Comment by purposestesting** [comment]
I updated the Sonoff  Stick to "CC1352P2_CC2652P_launchpad_coordinator_20220219" firmware. I deleted "Wohnzimmer Nord" and "Wohnzimmer Süd" and paired them again. That did not do the trick, the same different firmware versions will be displayed.

**Comment by stefangehn** [comment]
You may need to restart z2m after removing the device. Apparently the firmware info even survives a device removal in z2m.

I've got 5 Danfoss Ally (same device as the Popp one) and both the firmware version as well as the firmware date was not updated after a successful OTA update (the topmost one is new and was not updated to 01.18 yet):

![image](https://user-images.githubusercontent.com/6630737/209306746-975e5807-0239-438a-b0da-c6950659cf8c.png)

I guess this is rather a caching/display problem in z2m and the firmware on the device is likely to be alright. The tricky thing would be debugging this since once you've updated the firmware you cannot retry the same update easily.

**Comment by twinkie0101** [comment]
I am having a similar issue but with my phillips hue bulbs.  My bulbs are on the latest firmware but says I have an update available.  Tried updating and got the following error message:

...
2022-12-23 19:16:32Update of 'Phillips Hue - Movie Room - Closet Storage' failed (Image padding contains invalid bytes)
...

But looking at the [philips hue support ](https://www.philips-hue.com/en-us/support/release-notes/lamps)page my lights have the most current firmware 1.93.11

**Comment by purposestesting** [comment]
Thank you very much @stefangehn . I removed the TRV`s and then i shut down home assistant. After restart and reintegration it worked very well.
