### ISSUE TITLE
Not possible to set a schedule _TZE200_e9ba97vf 

### ISSUE THREAD

**Issue by Truddel** [Koenkk/zigbee2mqtt#15666]
### What happened?

Hi all,

when trying to set a schedule over the web it does not work, button is just greyed out:
![image](https://user-images.githubusercontent.com/3052370/208734274-ed0d4181-4364-4289-9ae6-3d156dcac3e9.png)

Trying to send it over MQTT: 
![image](https://user-images.githubusercontent.com/3052370/208734349-6e78297f-7844-499b-9a20-c5d969dc1066.png)
Leads to this in the log: 
![image](https://user-images.githubusercontent.com/3052370/208734427-e8721b4f-b934-4fe4-aa75-1440e3ba90ce.png)

### What did you expect to happen?

Set schedule properly.

### How to reproduce it (minimal and precise)

try to set schedule via UI or MQTT.

### Zigbee2MQTT version

1.28.4-dev commit: 3796084

### Adapter firmware version

20211217

### Adapter

Sonoff Stick

**Comment by vladi1234** [comment]
Hi,
As far as I know, this has never worked in the new Tuya format.

My Schedule variant in old Tuya format is much simpler and works very well. https://github.com/Koenkk/zigbee2mqtt/issues/15164#issuecomment-1326817667

**Comment by trikidiki** [comment]
I was able to alter the schedule until a couple of weeks ago. Now I cannot change it via the Zigbee2MQTT interface or directly publishing from MQTT Explorer (which looks to be the same as the original poster is using.

I was struggling with switching between auto and manual which appeared to be resolved in:

Heating is completely broken right now (At least for TV02 thermostats) #15164

then with the updates that seem to have resolved that issue came this new problem of inability to change the schedule. The schedule I had set prior to this was a rough setup to get things working but needs tuning. Now my only option is to set to manual and alter the target temperature.

This has made the automatic valves redundant, it is quicker to go around the house and physically alter them.
