### ISSUE TITLE
BlitzWolf BW-SHP13 no stable wattage, goes back to 0

### ISSUE THREAD

**Issue by Step-han** [Koenkk/zigbee2mqtt#16120]
### What happened?

I have a BlitzWolf BW-SHP13, in HomeAssistant and in Zigbee2mqtt if I look there the plug don't gives a stable wattage. It goes to 0 and then back to ~1300 watt. See below. Its a new plug.

The wattage is stable with other plug.

![image](https://user-images.githubusercontent.com/54219681/212085189-1c87b90a-639c-48ec-9cdd-3b11019a0307.png)

![image](https://user-images.githubusercontent.com/54219681/212086187-1cfa3dfc-2b50-4f04-a721-9c6e8dadfb91.png)

### Zigbee2MQTT version

 1.28.4

### Adapter firmware version

20220219

### Adapter

CC2652RB

**Comment by meganiekje** [comment]
I think this plug has an old zigbee chipset. This chipset does not read the output of measurment chip correctly. This is a hardware problem, and can not be solved. 
It can also be, that the plug starts switching off at random, because it reads the voltage incorrect.
Send it back to the seller, if you can.
