### ISSUE TITLE
[Feature request]: Retain of action message

### ISSUE THREAD

**Issue by daddvok** [Koenkk/zigbee2mqtt#16331]
### Is your feature request related to a problem? Please describe

When using wireless switches and buttons with the retain flag, the action message is remembered only until the device sends a new message about the battery status or linkquality. This causes the problem that if the device was recently pressed and z2m restarted, it will send an action, and if not, it will not send. 

### Describe the solution you'd like

Exclude the action parameter from retain or make it an option for the device in configuration.yaml.
or better:
for devices with the action parameter, if there is no action itself, add to any new message without action {action: none}/{action: null}/{action: false} or any other value.

### Describe alternatives you've considered

Оther alternative: To add an action from memory to any new message without action, but this will provoke a lot of false positives
I can simply disable retain for switches, but then I won't get the battery, switched status and other params after restarting.

### Additional context

![изображение](https://user-images.githubusercontent.com/47695947/214307000-415f4abe-7091-4800-b614-180e303712ec.png)
![изображение](https://user-images.githubusercontent.com/47695947/214307982-93bacee1-c78e-4987-b298-89849c4ffa0d.png)

**Comment by junosuarez** [comment]
To summarize:

When using `retain` setting on a device, if the last message from the device was an action (instead of an attribute report), that device state will not be retained by mqtt.

A challenge here is that zigbee2mqtt combines momentary events (which don't make sense to retain) with overall device state (which does make sense to retain in some use cases) in the same topic. 

Possible solutions (changing zigbee2mqtt):

1. Publish separate "action" and "state update" messages in the same topic. When the device sends an action, zigbee2mqtt would send 2 messages, back to back, like (roughly):
```
zigbee2mqtt/deviceA

{"action": "click", "battery": 100, ...}
```
```
zigbee2mqtt/deviceA, retain

{"battery": 100, ...}
```

2. Create a separate topic for retained state. No changes to current main device topic behavior, to maximize compatibility. But also publish retained messages to their own separate topic, without action data. Roughly:
```
zigbee2mqtt/deviceA

{"action": "click", "battery": 100, ...}
```
```
zigbee2mqtt/deviceA/state, retain

{"battery": 100, ...}
```

Possible solutions (no changes required to zigbee2mqtt):
1. Use a zigbee2mqtt External Extension to listen for `publishEntityState` events and then re-publish your own mqtt messages exactly how you want (eg pick one of the above approaches). This requires some custom programming but does not require core changes to zigbee2mqtt.
2. if your mqtt broker supports it, set the QOS to 1 or 2 for guaranteed delivery, and combine it with stateful sessions. This way, when your client reconnects, you'll get all the messages that were sent while it was disconnected. Search "mqtt stateful session" for more information.

Just riffing!
