### ISSUE TITLE
WS-EUK04 Hold and Release actions

### ISSUE THREAD

**Issue by svenjochems** [Koenkk/zigbee2mqtt#16658]
### What happened?

The Aquara wall switches WS-EUK01, WS-EUK02, WS-EUK03 and WS-EUK04 are missing the actions 'Hold' and 'Release'.

### What did you expect to happen?

I would expect those actions would be available like most other aqara wall switches.

### How to reproduce it (minimal and precise)

Long press the switch, no 'hold' or 'release' action is registered.

### Zigbee2MQTT version

1.30.0

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff ZBDongle-E EZSP v8

### Debug log

Let me know if I can do something to test or debug!

**Comment by EarthEclipse** [comment]
In case someone else stumbles upon this issue, the WS-EUK04 switch doesn't support hold and release in Zigbee2MQTT because the device is lacking the capabilities.

See the following links for more details:
- [double rocker with neutral - WS-EUK04 capabilities](https://zigbee.blakadder.com/Aqara_WS-EUK04.html
)
- [double rocker with neutral - QBKG12LM capabilities](https://zigbee.blakadder.com/Aqara_QBKG12LM.html)
