### ISSUE TITLE
Simplification / detection Zigbee version for prevent spamming log-output

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee2mqtt#1688]
To prevent spamming of the log files regarding the ``Succesfully reenabled joining`` issues, a distinction should be made within the zigbee2mqtt version between the normal Zigbee version and the 3.0 version.
Only if a 3.0 coordinator is used, the mechanism for the recurring activation should be used and only then the corresponding output into the log should take place.

@Koenkk Can we query the version on the basis of a certain characteristic whether 3.0 or not ?

**Comment by Koenkk** [comment]
Even for zigbee 1.2 there is a reason to periodically resend the enable joining command to be sure the network is open, e.g. devices could lose the permit joining state due to being turned off.

I don't see the problem of the `Succesfully reenabled joining` spamming
- It's only logged every 250 seconds
- When your network is in production, you should have `permit_join: false` so you won't see this message anyway.
