### ISSUE TITLE
IKEA controller E2001/E2002 binding to LED1924G9 problem: no cycling through colours and silences the controller  

### ISSUE THREAD

**Issue by hnykda** [Koenkk/zigbee2mqtt#17111]
### What happened?

When binding this controller to this RGBW bulb, only ON/OFF works, but I cannot cycle through colors (including White). It used to work on older firmware/versions of z2m (but I don't know when it broke exactly). Also, once I bind the controller to the light bulb, I no longer see any messages in z2m topic from this remote, I cannot unbind, nothing - it seems it's "invisible" from z2m from that point. I have to force remove the controller and pair it again.

```
Light:
Firmware build date: 2019062886LEL08N
Firmware version: 1.0.021
Manufacturer: [IKEA](https://www.zigbee2mqtt.io/supported-devices/#v=IKEA)
Model: [LED1924G9](https://www.zigbee2mqtt.io/devices/LED1924G9.html#ikea-led1924g9)

Controller:
Firmware build date: 20200708
Firmware version: 1.0.024
Manufacturer: [IKEA](https://www.zigbee2mqtt.io/supported-devices/#v=IKEA)
Model: [E2001/E2002](https://www.zigbee2mqtt.io/devices/E2001_E2002.html#ikea-e2001%252Fe2002)
```

### What did you expect to happen?

1. Binding the controller to the light would control the colors. 
2. Binding wouldn't make the controller invisible from z2m POV

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

20221226

### Adapter

Slaesh

**Comment by mamrai1** [comment]
i have the same problem with same light/controller... 
the arrows cycle the color only when controller is not paired.

**Comment by rospe** [comment]
Same here.
On/off and brightness works, but left/right arrows do not change colors. Adapter ist sonoff e here, though.

**Comment by hnykda** [comment]
This is still an issue

**Comment by bronkoo** [comment]
Same here.
On/off and brightness works, but left/right arrows do not change colors. Adapter is Conbee II.

**Comment by hnykda** [comment]
Don't do it github-actions

**Comment by bronkoo** [comment]
still alive...

**Comment by Tonio16** [comment]
Hello

The same for me with an hue iris bulb.

Antoine

**Comment by MattWestb** [comment]
@Tonio16 This function is only working with IKEA lights and need adding IKEAs default scenes in the device or doing one firmware upgrade of it and its creating them until the device is being reseed.

**Comment by MattWestb** [comment]
You can do wot you like with other devices then IKEA is sending the commands as manufacture tagged and its only IKEA devices that shall reacting on them if they is Zigbee certified..
Do normal automation for others but they is not working if the host system is not online as it so with correct setup IKEA scenes.

Read more in earlier post of the magic IKEA scene if you like getting it working OK with IKEA scene controllers.

**Comment by Naguz** [comment]
> [@Tonio16](https://github.com/Tonio16) This function is only working with IKEA lights and need adding IKEAs default scenes in the device or doing one firmware upgrade of it and its creating them until the device is being reseed.

This issue is also definitely there with both IKEA remotes and bulbs too, though. I have the same remote and bulb as OP, and can confirm the same problem:
1: The left/right button on the remote used to change scenes
2: This no longer works. Ie. something has been  broken.

The z2m documentation for the remote mentions adding some newer bulbs to a special group and create scenes in that group to be necessary to be  able to control scenes. it should not be necessary with the LED1924G9 as the bulb use to work with the E2001/E2002 running an older firmware. I have tried this with the LED1924G9 anyway, adding the bulb to a group with gid 65289 amd creating scenes in the group. The bulb  still does not cycle through any scenes with the arrow buttons on the remote pressed.

This issue only recently occured  for me after upgrading the remote firmware, to 2.4.16 / 20240708, before this it was never updated. While this is a much newer firmware than OP had, I think it's safe to say that it's related to firmware updates and not z2m updates, considering the years between the OP and now.

Still this is a bug, as the current documentation for the bug claims switching  scenes with IKEA bulbs should work, it does not. 

I can also confirm that binding the remote to a group and then unbinding it from the controllers , as the documentation states should work, does indeed *not* work, instead causing the remotes to not respond or control anything at all, mandating a pairing from scratch, just as OP states. But IMO that should be a separate bug. I'll see if I get around to that.

**Comment by andrei-lazarov** [comment]
Hi. I wrote the Z2M documentation for STYRBAR, tested everything on the E2313 with v2.4.17.
I was expecting the E2001/E2002 with v2.4.16 to behave the same. Will also test those in a few days and come back with a reply

**Comment by andrei-lazarov** [comment]
Tested the E2002 on initial firmware v1.0.024. It can bind to both devices and groups.
Binding a single cluster (onOff) enables all actions: on/off, dim up/down, cycle scenes.

The bug is with the LED1924G9 v1.0.021. It does not react to direct cycle scenes commands. Only group cycle commands work. Other bulbs react correctly to both.

Will update the remote and test group binding

**Comment by andrei-lazarov** [comment]
Updated to v2.4.16, binding to group works as written in the docs.
Bind `genBasic` to group, **then** unbind `genOnOff`, `genLevelCtrl`, `genScenes` from Coordinator.

<img width="589" height="376" alt="Image" src="https://github.com/user-attachments/assets/2a05ed43-e1fa-450e-a395-a82fc23fea0f" />
