### ISSUE TITLE
Allow to configure binding via `configuration.yaml`

### ISSUE THREAD

**Issue by Koenkk** [Koenkk/zigbee2mqtt#1716]
Similar to allow configuring of groups via `configuration.yaml`, we should also allow it for bindings.

**Comment by directman66** [comment]
We are looking forward to the decision, I would also like to receive the result through the MQTT query

**Comment by directman66** [comment]
Are there any updates on this topic?

**Comment by Koenkk** [comment]
Not yet.

**Comment by BudBundi** [comment]
I little feature request from my side, because we have no light link and can't transfer binding groups from remote to remote.
At the moment to control a lamp or group with more than one remote you have to, sniff the group to which the remote sends (IKEA), create a group for every remote and at the lamp to every group.

Maybe it would possible to change

'13':
    friendly_name: group_1
'41':
    friendly_name: group_2
'71':
    friendly_name: group_3

to

'13','41','71':
    friendly_name: group

**Comment by directman66** [comment]
the issue is not resolved?

**Comment by Koenkk** [comment]
Unstale

**Comment by zsiti** [comment]
This would absolutely fantastic! Is it still on the roadmap?

**Comment by snowytoxa** [comment]
+1
