### ISSUE TITLE
No more 14 modules

### ISSUE THREAD

**Issue by romainalca** [Koenkk/zigbee2mqtt#1757]
Hi,

Using zigbee2mqtt with docker on my Synology DS216+ for many months i can't add new modules (supported). I have 14 modules : Xiaomi door, movement, temperature and flood.
I tried to add Osram smart+ plug to extend zigbee network but nothing appears.
No log, no info : nothing !
Precision : did not forget to permit join and reset the plug (hold power button for 10 seconds until "click").

Sorry for my poor english !

**Comment by Koenkk** [comment]
Because you haven't paired any routers you are probably running into the device limit, I would recommend switching to https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/default which allows for 20 devices. You should be able to pair your router.

Feel free to ask any other question on the forum: http://zigbee2mqtt.discourse.group/
