### ISSUE TITLE
Moes MS-108ZR Position Problem

### ISSUE THREAD

**Issue by klio-klio** [Koenkk/zigbee2mqtt#17998]
### What happened?

I have a small problem with my roller shutters. I operate them using the Moes MS-108ZR. Everything seems to work fine, but when I close the roller shutters about 3/4 of the way and then try to open them again, they don't fully go up, even though the visualization shows them as open at 100 percent. I have noticed that there is a delay in the position display when I command the roller shutters to close.

### Zigbee2MQTT version

1.31.2

### Adapter firmware version

20201010

### Adapter

zStack30x

**Comment by jomuc** [comment]
Hallo klio-klio.
I'm using [Lonsonho QS-Zigbee-CP03](https://www.zigbee2mqtt.io/devices/QS-Zigbee-C03.html#lonsonho-qs-zigbee-c03) 
and have the same problem.

But I don't think, that's caused by Zigbee2MQTT.
If I shutdown the zigbee2mqtt service (just to be sure, that zigbee2mqtt doesn't do any interactions) and operate the shutter over the electric buttons, the same problem appears.
Bringing down the shutter to 2/3 and then open it. It will stop near to the upper position, but it will not be completely opened.
I'm not sure, what causes the problem, because I did calibrate my qs-zigbee-cp03. Maybe the calibration changes after a certain time (just a guess).
