### ISSUE TITLE
BRT-100 useless after OTA update

### ISSUE THREAD

**Issue by carlos-algms** [Koenkk/zigbee2mqtt#18840]
### What happened?

I was suggested to update my device from version `67` to `192`.
After the update succeeded the device stopped working via the web UI. 

Zigbee model: `TS0601`
Zigbee Manufacturer: `_TZE200_b6wax7g0` (Moes)

I tried to force remove it to add it again, but holding the `-` (minus) button doesn't make the antenna icon blink, (pairing mode), but instead, it keeps reducing the target temperature. 
Also, the LEDs don't turn off, just dim. 

A second device had a similar issue, the antenna icon remains still after holding `-`, but it doesn't register, and the screen turns off normally. 

### What did you expect to happen?

the update to happen, and the device to work normally. 

### How to reproduce it (minimal and precise)

just update the device. 

### Zigbee2MQTT version

1.33.0

### Adapter firmware version

20221226

### Adapter

Sonoff Zigbee dongle plus

**Comment by carlos-algms** [comment]
Bump to keep this alive. 
It's a pretty expensive issue to happen as it kills the device.

**Comment by Koenkk** [comment]
Removed OTA support for this device, thanks for reporting.

**Comment by gyver** [comment]
As it seems to be a recurrent problem when the manufacturer change revisions, may I suggest updating the https://www.zigbee2mqtt.io/devices/BRT-100-TRV.html page ? A warning that firmware updates have been known to be risky would go a long way to protect users with perhaps more details (the problem might occur both with new devices and old devices with old versions of Z2M if I understand correctly) ?

To give more context...

Before purchasing any Zigbee device I check the device pages for compatibility and any quirks. I did it for my recent purchases of BRT-100-TRV, didn't see any warning and started updating their firmware recently.
This killed 2 out of my 5 (2 were probably OK because they were an older version and I didn't try to update the last one). I thought I had a lemon with the first one to fail as updating a firmware is normally something safe to do (not sure about Zigbee specifically but in other domains usually devices refuse to flash incompatible firmwares). I only looked for people with similar problems after bricking the second device and here am I...

**Comment by Impact123** [comment]
> may I suggest updating the https://www.zigbee2mqtt.io/devices/BRT-100-TRV.html page

Every docs' page has a edit button at the bottom.
![image](https://github.com/Koenkk/zigbee2mqtt/assets/899193/ac8fe5d3-d444-4733-b444-8c906c41c0a1)

You could create a PR with a warning linking to this issue.
