### ISSUE TITLE
OTA - Ikea Tradfri LED1949C5 OTA Fail

### ISSUE THREAD

**Issue by shanelord01** [Koenkk/zigbee2mqtt#18904]
### What happened?

Globe model: https://www.zigbee2mqtt.io/devices/LED1949C5.html#ikea-led1949c5

All of my other globes of the same model and type (LED1949C5) have updated from 1.0.032 to 1.1.003 successfully. One of them required me to remove it from Z2M, reset it and re-add it for it to detect and load correctly.

I have tried to reset/re-add this last one multiple times and it has not worked.

### What did you expect to happen?

The globe to be updated.

### How to reproduce it (minimal and precise)

Restart the whole Home Assistant sever. Go to Z2M OTA tab and ask the globe to check for updates.

### Zigbee2MQTT version

1.33.0

### Adapter firmware version

6.10.3.0 build 297

### Adapter

HA Yellow (EZSP v8)

### Debug log

Debug 2023-09-08 16:49:00Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/check' with data '{"id":"IKEA Globe 6","transaction":"1j6cd-2"}'

Info 2023-09-08 16:50:00MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"IKEA Globe 6"},"error":"Failed to check if update available for 'IKEA Globe 6' (Device didn't respond to OTA request)","status":"error","transaction":"1j6cd-2"}'

Error 2023-09-08 16:50:00Failed to check if update available for 'IKEA Globe 6' (Device didn't respond to OTA request)

Debug 2023-09-08 16:50:00Error: Device didn't respond to OTA request at requestOTA (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:202:15) at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:259:25) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:203:45)

**Comment by mikeg-de** [comment]
I am facing the same issue but with the IKEA TRADFRI 5 Buttome Remote (Type E1524/E1810). Upon further investigation other users, since a long time, reported the same issue and suggested to push any button to prevent the device going into sleep right before and once every second or so. Though, to no avail.

Using the Test Servers as suggested in the docs doesn't help either: https://www.zigbee2mqtt.io/guide/usage/ota_updates.html#using-the-ikea-tradfri-test-server

Per [IKEAs release notes](https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html) the latest update of my remotes is from January 2023:

```
Release Version: 1.23.1
25th Jan 2023
New features and changes in Accessories:
TRÅDFRI remote control and TRÅDFRI motion sensor 1.0 (24.4.5)
Product ID: E1524, E1810, E1525
◆ Optimised battery performance.
◆ Stability improvements.
```

In order to attempt to load the firmware locally ([read the docs](https://www.zigbee2mqtt.io/guide/usage/ota_updates.html#local-ota-index-and-firmware-files)), I was searching for the download and contacted IKEA. I also tried to back engineer the URLs or find them inm the code. Finally, thanks to the [deConz Rrepository](https://github.com/zigpy/zigpy/discussions/660) I found:

1. https://fw.ota.homesmart.ikea.net/feed/version_info.json
2. https://fw.test.ota.homesmart.ikea.net/feed/version_info.json

However, the first is responding with an unusual 434 response code:

<img width="543" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/604842/d6433ab2-778b-4a7c-a204-ac0df72b19cb">

Downloading any referenced firmware file from the test server works. However, adjusting the URL for the regular one fails indicating the IKEA S3 or Cloudfront is basically faulty.

Test Server: http://fw.test.ota.homesmart.ikea.net/global/GW1.0/01.11.047/bin/10047227-1.2-TRADFRI-cv-cct-unified-2.3.050.ota.ota.signed

Normal Feed File: http://fw.ota.homesmart.ikea.net/global/GW1.0/01.11.047/bin/10047227-1.2-TRADFRI-cv-cct-unified-2.3.050.ota.ota.signed

This begs a few question like:
1. Are the correct feed URLs referenced?
2. Can the lack of SSL cause any issues?
3. Why isn't the test server not working (Like not up to date as Last-Modified is Fri, 17 Sep 2021 08:15:45 GMT)?
4. Which file, if any, from the test server could be used to locally reference the firmware update file?

Last Modified Response Header from Test Server
<img width="909" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/604842/19f9ef6b-e83b-4d51-9398-63e4ed37af85">

I will also attempt to contact the [domain admin](https://www.whois.com/whois/ikea.net) to omit contacting the IKEA support as they clearly are the wrong contact point.
