### ISSUE TITLE
[New device support]: Neo NAS-AB02B02 will not connect to Zigbee2MQTT in home assistant.

### ISSUE THREAD

**Issue by wilfriedbaars** [Koenkk/zigbee2mqtt#19099]
### Link

https://nl.aliexpress.com/item/1005003658351897.html?spm=a2g0o.order_list.order_list_main.22.21ef79d2HhaEBd&gatewayAdapt=glo2nld

### Database entry

none

### Comments

I try to pair the Neo NAS-AB02B02 but it will not pair. so no database entry or so. the Neo NAS-AB02B2 is supported.

There is only a reset button and description say reset device and connect to the ZigBee network. so short or long press on reset it will not join the zigbee2mqtt network in my home assistant.

please help with NAS-AB02B02 to connect to the zigbee2mqtt in home assistant.

Thanks in advance.

Wilfried

**Comment by CodeWilliamson** [comment]
I'm trying to pair this device as well and no luck. When I press and hold the reset button, I see a log message that the device has left but it never joined successfully to begin with so I'm confused.

**Comment by CodeWilliamson** [comment]
@wilfriedbaars have you had any luck getting this device to pair ?

**Comment by wilfriedbaars** [comment]
Hello CodeWilliamson,

I'm sorry but until now not able to pair :( also not many suggestions of how to pair.

Maybe you can help?

Regards,

Wilfried

**Comment by brjhaverkamp** [comment]
I added a  NAS-AB02B2 successfully to my network a few months ago. 
Then it ended up in a drawer while Io updated my home automation and moved to home assistant.
Initially on the new device I was not able to make it appear again. 
But then I also had problems pairing an aqara button. That had never happened before. And I have several.
 I added a USB cable between my raspberry and the dongle because I read some posts about possible interference. 
And behold. Bothd devices joined without a hitch. I can recommend trying this out. Maybe it works for you as well.

**Comment by woutput** [comment]
Hi all, sorry for adding to this closed issue, but to me, it doesn't look like the issue is solved.

I bought [this device](https://nl.aliexpress.com/item/1005003693237953.html) which, according to multiple reviews, should work with Zigbee2MQTT. When I open it up, it looks exactly the same as the photo in this post: https://github.com/Koenkk/zigbee2mqtt/issues/10348#issue-1088532963 According to that issue, the device should be supported by Z2M; also [this page](https://www.zigbee2mqtt.io/devices/NAS-AB02B2.html) shows that is should be supported.
Unfortunately, [that page](https://www.zigbee2mqtt.io/devices/NAS-AB02B2.html) doesn't describe the pairing procedure. Also the badly written paper manual that came with it isn't very clear.
I tried multiple ways to get it to pair (after removing the back cover of the device and after clicking Permit join - All and monitoring Z2M logging with log level config: info)
1. Try 1: no effect at all: no light, no messages in Z2M logging
  a. Power the device
  b. Shortly press the reset button on the back
2. Try 2: no effect at all: no light, no messages in Z2M logging
  a. Power the device
  b. Long press the reset button on the back
3. Try 3: lights turn steady on, lights turn off, single beep, silence, double beep, silence, quickly blinking lights, lights turn off; but no messages in Z2M logging.
  a. Disconnect power
  b. Hold reset button
  c. Connect power while holding reset button
  d. Release reset button

Could somebody share the pairing instructions, please? And preferably update [the device page](https://www.zigbee2mqtt.io/devices/NAS-AB02B2.html)

Maybe @elperepat @nighthawkii @ririck0 @SimonSezKossel @KaHeMu @jerrm @stephenjamieson @ChronoWerX82 @CodeWilliamson  @brjhaverkamp  @wilfriedbaars or @asdkjasdfla ?
