### ISSUE TITLE
Zigbee Rename, History not migrated. HA 2023.4 already have it

### ISSUE THREAD

**Issue by MaxLinSG** [Koenkk/zigbee2mqtt#19312]
### What happened?

https://github.com/home-assistant/core/pull/89963

With HA 2023.4, history are kept when entity name is renamed. However if i use rename function in zigbee2mqtt, the history is gone. 

![image](https://github.com/Koenkk/zigbee2mqtt/assets/12879322/79983414-c75c-4b12-b95e-d23fab8c2dcc)

![image](https://github.com/Koenkk/zigbee2mqtt/assets/12879322/53a20e67-1936-48c5-9149-ff44d3040e0f)

### What did you expect to happen?

The Entity renamed should carry the history of the device over.

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

20220219

### Adapter

Sonoff Usb3.0 Zigbee

**Comment by Koenkk** [comment]
In order to rename an Home Assistant entity from MQTT:
- It first has to be removed from HA <- this is where history gets lost and isn't done when you uncheck `Update Home Assistant entity ID`
- The device is rediscovered

Therefore this currenlty cannot be fixed from Zigbee2MQTT, I suggest to make a feature request to Home Assistant to allow entity renaming without having to remove it first.
