### ISSUE TITLE
PSBZS A1: reset_frost_lock not working

### ISSUE THREAD

**Issue by obelix05** [Koenkk/zigbee2mqtt#19320]
### What happened?

The frost lock was activated and i want to reset it with the reset frost lock button but nothing happens

### What did you expect to happen?

I expected that the frost lock is resetted after pressing the reset button

### How to reproduce it (minimal and precise)

wait for <=5°C outside temperature so that the frost lock is activated
wait for > 5°C outside temperature so that the frost lock could be deactivated
try to reset the frost lock by pressing the RESET button in the UI and/or with the texttable in Home Assistant

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

0x26580700

### Adapter

ConBee2

**Comment by zinserjan** [comment]
Ooops! 
I think I made a mistake converting my external converter to the new tuya format. There is a difference between these two (sending number instead of enum).

I'm already testing a potential fix: https://github.com/Koenkk/zigbee-herdsman-converters/commit/06cd6d3e57b8e9a8a8a709cc7df5f2d968ad3dd5
