### ISSUE TITLE
Cannot get last state of device by publish mqtt message zigbee2mqtt/[DEVICE_ID]/get

### ISSUE THREAD

**Issue by thachphongphong** [Koenkk/zigbee2mqtt#1943]
## A question?
How can i get last state data from devices (xiaomi sensor). I tried with 
**topic**: zigbee2mqtt/[DEVICE_ID]/get
**data**: {"state":""}
got this error
**error**: zigbee2mqtt:error 9/9/2019, 6:59:29 PM No converter available for 'state' ()
Maybe its not a bug. But Is there any way to get all device state when we want just not listen. My concept: I write a python service to get data from sensor and control other devices not use Homeassistant. 

## What happened
Publish date {"state":""} via mqtt topic: zigbee2mqtt/xxxx/get
**error**: zigbee2mqtt:error 9/9/2019, 6:59:29 PM No converter available for 'state' ()
tried with {"temperature":""}
## What did you expect to happen
Receive xxxx data via mqtt topic: zigbee2mqtt/xxxx

## Debug Info
zigbee2mqtt version: 1.5.1 (#ac3b924)
CC253X firmware version: 20190425

**Comment by Koenkk** [comment]
`/get` will try to retrieve the actual value from the device (read it). This fails for a Xiaomi sensor because it is sleeping.

If you want to get the last state known by zigbee2mqtt, you should set `retain: true` for that device. When connecting with your self made script to MQTT you will get all last known values.

Closing this at it is not an issue.
