### ISSUE TITLE
scene_add fails in 1.34.0 with Error: undefined is not a object, got undefined (undefined

### ISSUE THREAD

**Issue by jafrouk** [Koenkk/zigbee2mqtt#20001]
### What happened?

In 1.34.0, Attempting to add a new scene as per https://www.zigbee2mqtt.io/guide/usage/scenes.html#using-transitions-in-scenes fails, no scene is added.

In 1.33.2, the scene is created as expected, though transition_time not honoured as per https://github.com/Koenkk/zigbee2mqtt/issues/20002

### What did you expect to happen?

A blank scene would be created, This worked in 1.33.2

### How to reproduce it (minimal and precise)

Create a group called "new_group" with some lights in.
Send an MQTT message to zigbee2mqtt/new_group/set/scene_add' 
with Payload: 
```
{
        "ID": 206,
        "transition_time": 15
    }
```

Note - I tried with an without quotes around the numbers, and also sending to "set" with "scene_add" in the payload.

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Home assistant yellow (not sure which adapter you mean or where to find it)

### Debug log

1.34.0:
```
debug 2023-12-03 11:05:02: Received MQTT message on 'zigbee2mqtt/new_group/set/scene_add' with data '{
        "ID": 206,
        "transition_time": 15
    }'
debug 2023-12-03 11:05:02: Publishing 'set' 'scene_add' to 'new_group'
error 2023-12-03 11:05:03: Publish 'set' 'scene_add' to 'new_group' failed: 'Error: undefined is not a object, got undefined (undefined)'
debug 2023-12-03 11:05:03: Error: undefined is not a object, got undefined (undefined)
    at Object.assertObject (/app/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:511:15)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:4300:19)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:248:36)
debug 2023-12-03 11:05:03: Clearing Home Assistant scene discovery topics for 'Coordinator'
debug 2023-12-03 11:05:03: Clearing Home Assistant scene discovery topics for 'LC mid R'
```
1.33.2:
```
debug 2023-12-03 11:37:42: Received MQTT message on 'zigbee2mqtt/new_group/set/scene_add' with data '{
        "ID": 206,
        "transition_time": 15
}'
debug 2023-12-03 11:37:42: Publishing 'set' 'scene_add' to 'new_group'
info  2023-12-03 11:37:43: Successfully added scene
```

**Comment by Koenkk** [comment]
Found the issue!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by bfayers** [comment]
Just swapped onto the dev branch which says its using 16.0.2 in the about section but I'm still seeing this behaviour when attempting to add a scene over mqtt, but adding scenes in the webui works.

It does seem to be somewhat storing scenes sent over mqtt despite the error message shown in the webui because it's respecting the transition times if I create it over MQTT, see the error message, then create it in the webui too...

**Comment by Koenkk** [comment]
Found another issue, fixed it!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by bfayers** [comment]
> Found another issue, fixed it!

All good here now

**Comment by Koenkk** [comment]
@robertwigley should be fixed now.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by jerrm** [comment]
> Is there a guide on how to temporarily move to the Edge version of the add-on without losing any settings?

1. Stop the Release add-on
2. Disable Start on boot for the Release add-on
3. Install the Edge add-on
4. Duplicate the HA add-on Configuration tab from Release add-on into the Edge add-on.  I generally choose the edit in yaml option, and just cut/paste everything in one block.
5. Enable Edge Start on boot
6. Enable Edge Show in sidebar
7. Start the edge addon

**Comment by jjc092** [comment]
Not sure if this is related, but I'm getting this error on the latest dev version.

```
{
  "scene_add": {
    "ID": 0,
    "transition": 1
  }
}
```

```
error 2023-12-10 17:57:40: Publish 'set' 'scene_add' to 'Master Bedroom Bedside Lamp' failed: 'Error: Command 0x1c34f1fffe540a26/1 genScenes.add({"groupid":0,"sceneid":0,"scenename":"","commandTransitionTime":1,"extensionfieldsets":[]}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Parameter 'transtime' is missing)'
```

**Comment by gdgib** [comment]
For anyone else who needs an immediate fix and is running Z2M as an HA add-on...

1. Stop your copy of the Z2M add-on, and disable "start on boot"
2. Go to the terminal and run `cd addons && wget https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/releases/tag/v1.33.2-1 && unzip v1.33.2-1.zip`
3. Go to the add on-store and click the triple dots in the top right, then update repositories, then *wait*
4. Reload the add on store, and you should see a local section with the Z2M add on (and edge, etc, etc).  Install this one, it's the one you just downloaded above
5. Go to the configuration tab of the one you disabled, show the config as YAML and copy it to the one you just installed
6. Set the "start on boot" and other options of the downgraded version you just installed.

This should let you enjoy the older version until this bug is fixed.  When you're ready, you'll want to stop and uninstall the local version, and maybe delete the download.  Then re-enable the version from the normal store, of course.

Thanks @Koenkk for the truly excellent software, godspeed with the bugs.

**Comment by Koenkk** [comment]
Issue with `transtime` on latest dev is solved now.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
