### ISSUE TITLE
Aqara H1M switches not reporting state

### ISSUE THREAD

**Issue by dkras** [Koenkk/zigbee2mqtt#20549]
### What happened?

I have just installed roughly 100 of new Aqara H1M switches in the new house. I am adding all of them to Home Assistant via Z2M. They are all added correctly and I can control them just fine via HA frontend.
However, I have two serious issues and they may be connected, hence I open a single ticket:
1. When I physically press a switch button, the state does not populate into HA. As a result all necessary automation don't work.
2. After a period of time the switches that had been added start blinking red, which according to Aqara docs mean they lost ZigBee network. At the same time I can continue controlling them via HA and the reported lqi is fairly high (above 100).

### What did you expect to happen?

1. Switches report change of state into Z2M and HA frontend
2. Switches don't lose ZigBee network.

### How to reproduce it (minimal and precise)

1. Press the button, observe no change of state in Z2M. 
2. Add the switch to Z2M, wait for 15-30 minutes, observe the switch blink red.

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20210120

### Adapter

USB stick

**Comment by daserra23** [comment]
I also have this issue with Domoticz and zigbee2mqtt. At first I thought it was Domoticz. All works fine with 1.34 although I dare not try to change decoupled/control relay setting as it seems that is causing issues with anything above 1.33.
Only 7 switches here but they are all the light switches in my house, your place must be massive !

**Comment by verticalsoft** [comment]
With that many aqara switches I'd get an aqara hub and connect all of them to the aqara hub, don't worry as the aqara hub shows up in home assistant as a home kit device which can be controlled locally via home assistant.

When you add a device to the aqara hub it's automatically exposed to home assistant... One caviat is that not all the properties are available.

I've some aqara light switches and while the states are reported as well as button presses the energy consumption is not exposed. Obviously you can see the energy consumption in the aqara app.

Everything happens instantly just like it does through zbee2mqtt.

Since my network has become unstable over the last versions of ZigBee2mqtt I'm tempted to move all my Aqara devices over to my currently empty aqara M2 hub which I generally use to update firmwares.

Dave

**Comment by dkras** [comment]
> With that many aqara switches I'd get an aqara hub and connect all of them to the aqara hub, don't worry as the aqara hub shows up in home assistant as a home kit device which can be controlled locally via home assistant.
> 
> When you add a device to the aqara hub it's automatically exposed to home assistant... One caviat is that not all the properties are available.
> 
> I've some aqara light switches and while the states are reported as well as button presses the energy consumption is not exposed. Obviously you can see the energy consumption in the aqara app.
> 
> Everything happens instantly just like it does through zbee2mqtt.
> 
> Since my network has become unstable over the last versions of ZigBee2mqtt I'm tempted to move all my Aqara devices over to my currently empty aqara M2 hub which I generally use to update firmwares.
> 
> Dave

I am running few Aqara hubs: G3 cameras. The devices themselves are good but they don't bridge H1M switches to HA neither via Homekit, nor Matter.

In either case, my personal preference is to have fewer transition points at this size of ZigBee installation.

I will hope the Z2M team will fix the issue or recommend a workaround.

**Comment by verticalsoft** [comment]
Bless you sir, I would love z2m to be stable but I'm finding it's progressively getting worse.

I'm constantly getting devices going unavailable and chasing my tail getting things back online.

I really appreciate the community effort but constantly running into issues it becoming increasingly frustrating.

I guess it only takes a rouge device to cause issues which is why I tend to pay extra for the better devices.

I wish you well in your quest .....

**Comment by daserra23** [comment]
I can't say I have had any worsening major performance issues with zigbee2mqtt apart from a few glitches with the non-standard Aqara stuff but nothing to worry about. I've found it consistently one of the most reliable components of my system.

**Comment by Koenkk** [comment]
@dkras your coordinator firmware is too old and does not properly support newer xiaomi devices, upgrade it and re-pair the device.

**Comment by dkras** [comment]
I can confirm that after updating the firmware to the latest version 20230507 I was able to re-pair the devices and they now work as expected.
I no longer observe either of the two issues I had reported.

@Koenkk Thank you for the right suggestion!
