### ISSUE TITLE
has cc2652r better range?

### ISSUE THREAD

**Issue by guitar9** [Koenkk/zigbee2mqtt#2066]
Has somebody tried cc2652r?
Has it a better range then cc2531?
Is it worth to switch to cc2652r?
There were some issues: see here: https://e2e.ti.com/support/wireless-connectivity/zigbee-and-thread/f/158/t/794106

Could they be solved?
I have some stability problems with cc2531... I am looking for a alternative

**Comment by lolorc** [comment]
I've been an early adopter, I'm pretty sure it still has bugs.
The most important bug to me was I had my z2m systemd service file to stop the daemon, use uhubctl to power cycle my cc2652r, then restart it every 7h. This problem is gone for me with the latest unofficiall firmware. This evening I decided to move my important devices to cc2652r+herdsman/dev. (some of them were still using a more stable network with cc2530+cc2591)
fingers crossed !
My fear for now is, will I have to repair my devices if I power cycle or upgrade the firmware of my cc2652r. Time will tell :)

concerning range, it's definitely better !
I guess I'm going to give two cc2531, one cc2530+cc2591 and one cc2538+cc2592 to some friends sooner or later :-)

**Comment by Koenkk** [comment]
Yes the antenna on the CC2652R development board (the only thing you can buy for now) is better.

However the main reason to switch to the CC2652R is the improved performance and memory (allowing for more devices).

Note that this device is officially not supported by zigbee2mqtt yet, hopefully soon: https://github.com/Koenkk/zigbee2mqtt/issues/1429#issuecomment-535437377

I will close this for now, lets keep CC2652R discussion here: #1429
