### ISSUE TITLE
Xiaomi WSDCGQ11LM - No negative values accepted for Calibration Values

### ISSUE THREAD

**Issue by patrex0304** [Koenkk/zigbee2mqtt#20793]
### What happened?

I tried to change the Humidity Calibration through the interface (front end) under specific settings. I cannot set negative values for any of the calibration values (Temperature, Humidity, Pressure). It worked in the past, but now its not working anymore. If i stop z2m and change the settings in device.yaml to a negative value and start z2m again, the negative value seems to be accepted. 

### What did you expect to happen?

Accept negative values for calibration.

### How to reproduce it (minimal and precise)

Go into Xiaomi WSDCGQ11LM on Dashboard, then Settings (specific), change like Humidity calibration to negative value.

### Zigbee2MQTT version

1.35.1-1

### Adapter firmware version

20211217

### Adapter

Electrolama zig-a-zig-ah!

### Setup

Add-on on HomeAssistant OS

**Comment by siandco** [comment]
I think your issue is with the frontend rather than Z2M itself.
The frontend doesn't allow you to use the '-' key in fields, however there is a workaround.
On the far right of the input you'll spin widget, use this to set the negative value and then click into the input to enter any decimal value (i.e. .4) then click on another field to make sure the value is saved.

As the frontend is not maintained by @koenkk I recommend you an issue with that developer for it at:  [https://github.com/nurikk/zigbee2mqtt-frontend](https://github.com/nurikk/zigbee2mqtt-frontend)
