### ISSUE TITLE
Binding SONOFF ZBMINI with EssentielB EB-E27-G95-CCT-FV

### ISSUE THREAD

**Issue by ulysserevient** [Koenkk/zigbee2mqtt#20844]
### What happened?

I'm trying to bind a SONOFF ZBMINI with 4 EssentielB EB-E27-G95-CCT-FV include in a group, but it does nothing !
I'm able to bind this group with a button EssentielB EB-SB-1B, it works fine.

If I try to bind the ZBMINI with a single light, no cluster appear ! Can't bind !

### What did you expect to happen?

I would like to switch the 4 lights ON/OFF with the ZBMINI button.

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

0.6.151

### Adapter

Conbee II

### Setup

Docker container

**Comment by wastez** [comment]
This is working on my zbmini without problems. The only difference is the adapter. Mine is an ezsp. So the problem seems not to be in z2m itself, maybe in the library which used is used by z2m to control your stick. 
But I’m quite sure this is a own project. (On ezsp it is zigbee herdsman)
For your adapter I had to research don’t needed to know it until now.
