### ISSUE TITLE
[Feature request]: add friendly name to group member objects: zigbee2mqtt/bridge/groups

### ISSUE THREAD

**Issue by schwalbe13** [Koenkk/zigbee2mqtt#20865]
### Is your feature request related to a problem? Please describe

Based on the data coming from the MQTT topic: "zigbee2mqtt/bridge/groups", I want to add a device with its friendly name to a group, or remove it. This is currently not possible, because the member objects only contain the ieee_address.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/34183709/18ac5d56-4d70-4f42-ab15-e54582534a92)

### Describe the solution you'd like

Add to those member objects the friendly_name of the device.

### Describe alternatives you've considered

In Node-Red, combining the information from "zigbee2mqtt/bridge/groups" and "zigbee2mqtt/bridge/devices"

### Additional context

![image](https://github.com/Koenkk/zigbee2mqtt/assets/34183709/de3fa697-40c0-49c5-a366-a8a626f8e31b)

**Comment by danieledwardgeorgehitchcock** [comment]
I think this may be quite difficult to implement as Groups are a function of a Zigbee network and are much more than logical buckets for device organisation - Z2M just provides functionality / wrappers around this.

If a devices friendly name is used, this would require the Z2M group function to enumerate device friendly names to extract the IEEE address so that it can be added via Zigbee commands.

What if a Device friendly name were to change? Zigbee2MQTT would have to have a mechanism for tracking the friendly names / changes with IEEE addresses to be able to also ensure that the group is correctly administered and no devices are orphaned.
