### ISSUE TITLE
Device Stuck in pair loop

### ISSUE THREAD

**Issue by drannou** [Koenkk/zigbee2mqtt#21497]
### What happened?

During a full re-pair of my 40+ devices (due to instability), I discover that I cannot repair some devices.
Most of my devices can re-pair with the coordinator, but some are stuck in pair process, with led blinking

For example: Legrand cable outlet can pair successfully, I can start to get information, but the device led does not stop blinking, and the device disconnect after seconds.
I have the same with ewelink relay (led never stop blinking)
It's like if devices were waiting for a final ACK from coordinator and never get it.

Informations:
Z2m: [1.35.3](commit: [fe0742a])
Coordinator: EZSP v12 (7.3.1.0 build 176)

Test done : delete coordinator_backup.json  database.db  database.db.backup, repair the strict minimum to be able to pair the Legrand device, same issue

### What did you expect to happen?

Device should stop blinking at the end of the pair process, and should not disconnect

### How to reproduce it (minimal and precise)

repair devices

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

7.3.1.0 build 176

### Adapter

EZSP v12

### Setup

HA with Z2m on orangepi Zero 3

### Debug log

I attach the debug trace, finishing in a crash of z2m

[Uploading debug.log…]()

**Comment by drannou** [comment]
I may have found why it's not more stable:
I have all routers that are in the "missing_routers"
After removing ALL devices, and adding only one router, I direcly see it on the missing routers:
`Zigbee2MQTT:info  2024-02-20 22:37:17: MQTT publish: topic 'zigbee2mqtt/bridge/response/coordinator_check', payload '{"data":{"missing_routers":[{"friendly_name":"0xa4c138e52af808ce","ieee_address":"0xa4c138e52af808ce"}]},"status":"ok"}'`
now the question is why...

**Comment by gbroll** [comment]
I think this is the same [issue](https://github.com/Koenkk/zigbee2mqtt/issues/21363) as I have. I have problems with IKEA bulbs and LEDVANCE outlets, which keeps resetting after pairing. For the IKEA lights, it was possible to stop the reset by cutting power immediately after successful interview, but that doesn't work for the ledvance outlets. 
We are running different zigbee adapters (I have an old conbee) which I guess suggests that the problem is not related to the adapter but further up the stack. 

#21363

**Comment by Xavinooo** [comment]
I also have issues to pair legrand devices. I went back to 1.32.0 to pair them...

**Comment by drannou** [comment]
Find a way to make it pair, I saw it in another thread where you need to stop Z2M when the device has been discovered.
It's a little bit pita, but it works.
May be we should fix the documentation (at least, or fix the bug :p )

**Comment by Koenkk** [comment]
Could have been fixed by https://github.com/Koenkk/zigbee-herdsman/pull/938 which is available in the  [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) 

If not, I suggest to try the [new driver](https://github.com/Koenkk/zigbee2mqtt/discussions/21462)

**Comment by sjorge** [comment]
> Could have been fixed by [Koenkk/zigbee-herdsman#938](https://github.com/Koenkk/zigbee-herdsman/pull/938) which is available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
> 
> If not, I suggest to try the [new driver](https://github.com/Koenkk/zigbee2mqtt/discussions/21462)

Seeing similar issues with a z-stack coordinator, but I'm just blaming it on legrand being very picky. As it never really worked well before anyway. I am able to pair it with the september z2m release though. But it just breaks when upgrading again and I gave up.

Because the device is very hard to debug as I essentially have to cut the entire power to the house to reset mine (which euhm, well doesn't do well for the server running z2m).

**Comment by sjorge** [comment]
This is related to https://github.com/Koenkk/zigbee-herdsman/issues/979, until this is fixed you can theoretically manually comment the readResponse coming from inside zh. I've tried this and then the device pairs again.
