### ISSUE TITLE
XHS2-UE contact sensor battery drain

### ISSUE THREAD

**Issue by russilker** [Koenkk/zigbee2mqtt#21490]
### What happened?

I moved from ZHA to Z2M a few years ago, and since then my XHS2-UE contact sensors (nearly 20 of them) drain within a month or two (or sometimes even within a few weeks) when they used to last a year or more. Other contact sensors from other manufacturers do not have this issue.

I have tried the following over the years:
- Different batteries from different manufacturers and stores
- Positioning magnet closer to contact sensor
- Moving coordinator within 10 feet of contact sensor
- Changing Zigbee channel (currently 24)
- Adding Zigbee routers
- Changing coordinator from Conbee II to Sonoff ZBDongle-E
- Changing host machine from an AMD thin client to an Intel thin client (both x86 docker container on Ubuntu server)
- Updating Sonoff coordinator firmware to latest
- Significantly lowering Powercfg and Temperature reporting intervals
- Unbinding Powercfg and Temperature clusters completely, leaving only genPollCtrl
- Updating z2m and trying dev releases

### What did you expect to happen?

For the battery to last a while

### How to reproduce it (minimal and precise)

Purchase an XHS2-UE contact sensor and use it with z2m

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

7.3.1.0 build 176

### Adapter

Sonoff ZBDongle-E 

### Setup

Docker container on an x86 thin client

**Comment by Cjkeenan** [comment]
I have noticed this issue as well and as a result I have migrated away from these devices since the batteries are so expensive. It really sucks because these sensors are low profile and can be found for DIRT CHEAP on eBay so I had high hopes for them.

**Comment by rwarner** [comment]
Hey guys thanks for creating this issue a long time ago. I recently ran into this same problem after migrating from ZHA to zigbee2mqtt. I went from having these sensors easily last past 6 months (which was still a bit short), to now having them last approximately just a week or two which was insane.

I think I might have a PR I can introduce that fixes the problem after analyzing the codebases for ZHA and Z2M. I also tried all the things that the original OP listed and none of them worked.

Going on about a week+ now with things holding steady compared to before. Will give it some time and hopefully introduce a PR in reference to this. I was mainly driven, because I have over 30+ of these devices and in no way do I want to take them all down.

**Comment by rwarner** [comment]
Excellent, the PR got merged in for the battery drain fix (merged into `v26.100.0`): https://github.com/Koenkk/zigbee-herdsman-converters/pull/12985

> Root cause: `longPollInterval` ships at 8 qs (2 s), causing 43,200 MAC polls/day. ZHA sets it to 24 qs (6 s) during pairing (14,400/day) — the 3× difference is the entire battery drain story. The fix adds a `configure()` step that calls `setLongPollInterval(24)` via cluster command 0x02 (it's read-only as an attribute), plus an `onEvent` handler to reapply after battery swaps.

@Koenkk would you be able to reopen and close this as fixed, or add a resolution label? Hope you don't mind me pinging you.
