### ISSUE TITLE
3 x Hue Bulbs showing as unsupported when 7 others work

### ISSUE THREAD

**Issue by benflux** [Koenkk/zigbee2mqtt#21742]
### What happened?

I've paired (and re-paired) 3 of the 10 bulbs I've installed and they are still showing as unsupported.

### Zigbee2MQTT version

1.36.0-1

### Adapter firmware version

20220219

### Adapter

Electolama zzh!

### Setup

Home Assistant Blue as an Addon

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/14549248/log.txt)

**Comment by srett** [comment]
A lot of routing problems according to the log. Since the bulbs are active devices that act as routers, this might temporarily happen if you add them all in rapid succession. Also, if you put those bulbs behind physical switches that disconnect the bulbs occasionally, the network would have to restructure to find new routes to some devices. While zigbee is supposed to handle this, if you frequently turn on and off bulbs, this will inevitably lead to problems. Give it some time to settle and then try again.
