### ISSUE TITLE
availability_whitelist ?

### ISSUE THREAD

**Issue by lolorc** [Koenkk/zigbee2mqtt#2204]
do you think it would also make sense to have an advanced param "availability_whitelist" ?

I still have one bulb behind a real switch, it would be easier to whitelist one device instead of blacklisting all existing routers and the new ones to come.

**Comment by Kryzek** [comment]
Had really silent day at work and had some spare time, I came up with this: https://github.com/Kryzek/zigbee2mqtt/commit/18b9c29f9c5b422f56f6e27715eb23ee8fe3f00c

I also need availability only for some devices not for all of them - one does not give report updates periodically and the other is behind real switch. As stated, it would be easier to list those devices that would need availability checks instead of blacklisting all others.

I have not tested this yet since I'm not home - but maybe @Koenkk could check if you see something that is totally broken?
