### ISSUE TITLE
Aqara door sensor stopped working.

### ISSUE THREAD

**Issue by Xan8** [Koenkk/zigbee2mqtt#2212]
# Bug Report
## What happened
I had the aqara door sensor working but one day just stopped.
I restarted the sensor (by pressing the button 10 sec). Then I activated "allow devices to join" and it paired. 
Now, it is connected (it appears on the log of the add-on, on zigbee map and the sensor blinks twice when I press it) but the sensor (on integrations) doesn't change the state, it stays always close. When I open or close the door nothing is shown on the add-on log
## Debug Info
zigbee2mqtt version: 1.6.0

**Comment by knoer** [comment]
I am also running 1.6.0 and had the same happen to me a couple of days ago.
My (currently only) door sensor is the farthest endpoint in my network, and has been reporting a rather low link quality to start with (>20 according to homeassistant)
The temperature at my location has been slowly dropping the last few weeks, and the sensor is installed at an unheated location, so this might also be a factor.

Just started reading up on this today, but it seems there are strong arguments for updating to the latest version (1.7.1) as Koenkk has put a lot of work into enhancing communication with Xiaomi/aqara devices since 1.6.0.

I will update to the latest version before troubleshooting the device or zigbee network.

Check comments on the latest [releases](https://github.com/Koenkk/zigbee2mqtt/releases)
