### ISSUE TITLE
Failed to whitelist device

### ISSUE THREAD

**Issue by fatemeh76m** [Koenkk/zigbee2mqtt#2222]
# Bug Report
## Debug Info
zigbee2mqtt version:
CC253X firmware version:

**Comment by fatemeh76m** [comment]
Using topic zigbee2mqtt/bridge/config/whitelist and sending device friendly_name as payload always results in "failed to whitelist <friendly_name>", but in the configuration.yaml file the friendly_name can be seen in the whitelist.
what is the possible problem?

![whitelist](https://user-images.githubusercontent.com/36724286/67693913-c3c04580-f9b7-11e9-83b6-535a1cd93048.jpg)
Is the device added to the whitelist or not? If it is added, why other devices which are not in whitelist can join to network?

**Comment by Koenkk** [comment]
Can you try with latest zigbee2mqtt dev?

**Comment by fatemeh76m** [comment]
The code I'm working on it, is for one month ago. Have you changed anything in whitelist since then?

**Comment by Koenkk** [comment]
I guess the whitelisting fails because it is already whitelisted. can you share your `configuration.yaml`?

**Comment by Arminhosseini** [comment]
Hi, I have this problem too but if we assume you are right white list does not work as I expected because in zigbee2mqtt topics you mentioned when a device whitelisted other devices will be removed but this not happened for me. and in your code, there is an if condition that when a white list is not empty if we connecting any other devices that are not whitelisted coordinator should remove it but it's not happening
because however my whitelisted device in conf.yaml is not empty consider as null and continue to add device.

**Comment by Arminhosseini** [comment]
another thing is that when I whitelist a new device that I didn't whitelist this error will show again.
and what is the latest dev?
thank's for your reply.

**Comment by Koenkk** [comment]
@Arminhosseini please provide debug logs and your `configuration.yaml` when this problems occurs.

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```
