### ISSUE TITLE
total freeze of pi3 on starting 

### ISSUE THREAD

**Issue by jonesMeUp** [Koenkk/zigbee2mqtt#22881]
### What happened?

In 9/10 tries zigbee2mqtt freezes my pi3 right after  ... "RTS/CTS config is off, enabling flow control."
If it starts (via _npm start_), then i can use it and can pair my 2 Ikea Waterleak sensors. Stopping and starting z2m again is no problem.
But when i reboot the raspi, _npm start_ freeze it again.

- The serial port and the whole z2m folders are writeable by user pi.
- I tried several USB cords and all USB-Ports of the raspi.
- I tried several positions of the dongle, near at the raspi and far away
- No log file is written on a freeze.
- On all tries only the dongle and the power cord is connected to the pi.
- It happens with ember and ezsp.
- My raspi pico with a 433Mhz sender connected to serial port (echo "sendRf(674647)" > /dev/ttyACM0) has no problems with my raspi3 running on bookworm. 
- I tried /dev/ttyACM0 and /dev/serial/by-id/........

I have used z2m about 2 month before i updated the raspi to the latest raspian with all updates.
The first reboots made no problems, but now its frustrating.
I updated the dongle after the first freezes, but it didn't change anything. 

_npm test_ shows no problems even before a freezing "npm start"

What can I do to squeeze an error message out of z2m instead of a freeze?
Thanks for your time
jones

### What did you expect to happen?

An error message instead of a full crashed computer

### How to reproduce it (minimal and precise)

Reboot raspi on a working config

### Zigbee2MQTT version

1.37.0 - 1.38.0 (ember) 1.37.0 - 1.37.1 (ezsp)

### Adapter firmware version

7.4.2 [GA] (for ember) and for ezsp the last version shown on https://darkxst.github.io/silabs-firmware-builder/

### Adapter

ZBDongle-E

### Setup

plain z2m on Raspi3b with fhem

### Debug log

**no log on freezed raspi, here is a log of a running z2m**

[2024-05-31 21:51:07] info: 	z2m: Logging to console, file (filename: log.log)
[2024-05-31 21:51:07] info: 	z2m: Starting Zigbee2MQTT version 1.37.1 (commit #cda867a)
[2024-05-31 21:51:07] info: 	z2m: Starting zigbee-herdsman (0.46.6)
[2024-05-31 21:51:08] info: 	zh:ember: ======== Ember Adapter Starting ========
[2024-05-31 21:51:08] info: 	zh:ember:ezsp: ======== EZSP starting ========
[2024-05-31 21:51:08] info: 	zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-05-31 21:51:08] info: 	zh:ember:uart:ash: RTS/CTS config is off, enabling software flow control.
[2024-05-31 21:51:08] info: 	zh:ember:uart:ash: Serial port opened
[2024-05-31 21:51:08] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-05-31 21:51:09] info: 	zh:ember:uart:ash: ======== ASH connected ========
[2024-05-31 21:51:09] info: 	zh:ember:uart:ash: ======== ASH started ========
[2024-05-31 21:51:09] info: 	zh:ember:ezsp: ======== EZSP started ========
[2024-05-31 21:51:10] info: 	zh:ember: [STACK STATUS] Network up.
[2024-05-31 21:51:10] info: 	zh:ember: [INIT TC] NCP network matches config.
[2024-05-31 21:51:10] info: 	zh:ember: [CONCENTRATOR] Started source route discovery. 1248ms until next broadcast.
[2024-05-31 21:51:10] info: 	zh:controller: Wrote coordinator backup to '/opt/zigbee2mqtt/data/coordinator_backup.json'
[2024-05-31 21:51:10] info: 	z2m: zigbee-herdsman started (resumed)
[2024-05-31 21:51:10] info: 	z2m: Coordinator firmware version: '{"meta":{"build":0,"ezsp":13,"major":7,"minor":4,"patch":2,"revision":"7.4.2 [GA]","special":0,"type":170},"type":"EmberZNet"}'
[2024-05-31 21:51:10] info: 	z2m: Currently 0 devices are joined:
[2024-05-31 21:51:10] warning: 	z2m: `permit_join` set to  `true` in configuration.yaml.
[2024-05-31 21:51:10] warning: 	z2m: Allowing new devices to join.
[2024-05-31 21:51:10] warning: 	z2m: Set `permit_join` to `false` once you joined all devices.
[2024-05-31 21:51:10] info: 	z2m: Zigbee: allowing new devices to join.
[2024-05-31 21:51:10] info: 	zh:ember: [STACK STATUS] Network opened.
[2024-05-31 21:51:10] info: 	z2m: Connecting to MQTT server at mqtt://localhost
[2024-05-31 21:51:10] info: 	z2m: Connected to MQTT server
[2024-05-31 21:51:10] info: 	z2m: Zigbee2MQTT started!
[2024-05-31 21:53:21] info: 	z2m: Disconnecting from MQTT server
[2024-05-31 21:53:21] info: 	z2m: Stopping zigbee-herdsman...
[2024-05-31 21:53:21] info: 	zh:controller: Wrote coordinator backup to '/opt/zigbee2mqtt/data/coordinator_backup.json'
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash: ASH COUNTERS since last clear:
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   Total frames: RX=76, TX=143
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   Cancelled   : RX=0, TX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   DATA frames : RX=75, TX=67
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   DATA bytes  : RX=794, TX=731
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   Retry frames: RX=0, TX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   ACK frames  : RX=0, TX=75
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   NAK frames  : RX=0, TX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   nRdy frames : RX=0, TX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   CRC errors      : RX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   Comm errors     : RX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   Length < minimum: RX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   Length > maximum: RX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   Bad controls    : RX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   Bad lengths     : RX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   Bad ACK numbers : RX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   Out of buffers  : RX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   Retry dupes     : RX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   Out of sequence : RX=0
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash:   ACK timeouts    : RX=0
[2024-05-31 21:53:21] info: 	zh:ember: [STACK STATUS] Network closed.
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash: Port closed. Error? no
[2024-05-31 21:53:21] info: 	zh:ember:uart:ash: ======== ASH stopped ========
[2024-05-31 21:53:21] info: 	zh:ember:ezsp: ======== EZSP stopped ========
[2024-05-31 21:53:21] info: 	zh:ember: ======== Ember Adapter Stopped ========
[2024-05-31 21:53:21] info: 	z2m: Stopped zigbee-herdsman
[2024-05-31 21:53:21] info: 	z2m: Stopped Zigbee2MQTT

**Comment by Nerivec** [comment]
From the logs, seems like it's starting properly _when it starts_. So I guess there must be something messing with it outside of Z2M.
Did you try plugging the adapter in a powered USB hub (a hub with an external power adapter to avoid drawing from the PI)?

**Comment by jonesMeUp** [comment]
thx for your answer.
no, i don't have a powered USB hub.
But why it was running about 2 month without any problems?

**Comment by Nerivec** [comment]
The update could have change internal power settings. It could also be the power adapter of the PI showing signs of trouble.
I'm no PI expert though, could be something else entirely, but power is often a source of weird issues on the PI...

**Comment by jonesMeUp** [comment]
Ok, i will buy a powered USB and keep you informed.
Thx, again

**Comment by nono20004** [comment]
Hello I have the same problem with zwave2mqtt have update your raspberry firmware ? If you have update, downgrade your raspberry pi 3 b model and your problème solved.
Sorry for my bad English

**Comment by jonesMeUp** [comment]
@nono20004 thx, yes i have the latest firmware on my pi. i can`t wait to test your hint (when i am back home in the night or tomorrow).
@Nerivec the powered usb-switch will arrive in about 3 days, then i will test it with both firmawares.

**Comment by nono20004** [comment]
Ok your are welcome
I wait your final result

**Comment by jonesMeUp** [comment]
So... you are both right:

1. its not a z2m problem
2. raspi is the enemy

I tested a bunch of firmware verisons and thats the result:
![Pi3_ZBDongle-E__test](https://github.com/Koenkk/zigbee2mqtt/assets/109303551/b6eff133-346c-4cc8-8541-4a5556fbbee2)

**All** firmwares above 6.1.77 didnt't work.
I leave this issue open until i checked the last rpi firmware with an aktive USB-Hub.
This should help desperate raspi users to fix the problem. 

Without your help i didn't know where to search, because the dongle says max 100mA and Raspi3b says a sum of 1,2A is given to USB, so i took this as a fact and searched for days on my z2m settings, USB-Cords, dongle position, etc and also killed a 32**GB** SD-Card which was degraded to a 30**MB** Card, after cutting power on each try, while green LED says disc activity forever.

**Comment by nono20004** [comment]
Hello thank you for your response.
I wish that USB hub solve the problem but for me with zwave aotec gen 5 I didn't
Good luck

**Comment by JacekKac** [comment]
@jonesMeUp how did you downgrade pi firmware?

**Comment by JacekKac** [comment]
ok i did a rpi-update to the newst firmware and it's working ok, in the meantime i disabled bt to save energy (not sure if this is necessary

**Comment by jonesMeUp** [comment]
For all that need an info how to update:
On the picture above, you see the correct file (6.1.77) on the right you can copy the hash.
then sudo rpi-update _hash_ example for 6.1.77
`sudo rpi-update 5fc4f643d2e9c5aa972828705a902d184527ae3f`

@JacekKac  all firmwares > 6.1.77 didn't work for me. make 1 or 2 reboot and look if it still works

**Comment by jonesMeUp** [comment]
With my new active USB-Hub i have tested 2 of the newer firmwares and all worked well.
As the `max_usb_current=1` is meanwhile ignored by the raspi, i can see 2 solutions:

1. downgrade the raspi tp 6.1.77
2. use an aktive USB-Hub

**Comment by jonesMeUp** [comment]
update:
the problem seems to be solved in the upcoming 6.7.y kernel
[patch info](https://github.com/raspberrypi/linux/pull/5775)

**Comment by Fougues** [comment]
Hi,
I have the same problem as you. where do you go to do the update: rpi-update ?
or do you have to type this the rpi-update to update?

Thanks a lot

**Comment by Fougues** [comment]
my raspberry runs under HAOS

**Comment by clauso** [comment]
You have to type in the command on the command line. if there is no rpi-update, then you need to install it first `sudo apt install rpi-update`.
Disclaimer: I have never used HAOS, so I cannot tell you, how it works there.

**Comment by Fougues** [comment]
Thanks 
 But there is no command line on HAOS

**Comment by Fougues** [comment]
do you think that version 2 of Zigbee2mqtt corrected the problem?

has anyone tried with the new version

**Comment by jonesMeUp** [comment]
again, it's not a Zigbee2mqtt problem, it's a linux kernel problem (broken usb-power delivery).
don't know anything about haos, but you have to ask there for help to switch to a working kernel version.

**Comment by uowis** [comment]
Why same kernel working on ZHA ?
Haos don't permit to change kernel so we only have the solution to wait and Believe Haos switch quick in working kernel version.

**Comment by Fougues** [comment]
Helo,

HAOS developers should be informed who are in principle very responsive.  Do you know how to inform them?
THANKS

**Comment by bennydiamond** [comment]
Thank you I was going crazy on this. `rpi-update 5fc4f643d2e9c5aa972828705a902d184527ae3f` command did the trick.

Here's my setup
Raspberry Pi 3B
Powered from a 3A 5V switching regulator through Pi's GPIO header. Very low ripple validated with a scope.
OS: DietPi 9.10.0, kernel 5.15.0. Latest release as of 2025-02-19.
ZBDongle-E attached through a 30cm USB2.0 extension cable
Wired Ethernet, Wifi/BT disabled

Zigbee2MQTT was initially installed as a Docker container but as I was having freeze issues, I tried a bare metal install. Installing it natively on host would not solve the freeze issue.
Adding a 30 seconds pre-start delay to zigbee2mqtt systemd unit wouldn't solve freeze issues.
Currently rocking a bare metal install.

I also had the same issue with Raspberry Pi OS 64-Bit previously. I thought it might be an OS issue and that's why I decided to go for DietPi. Both OSes gave me the same issues.

I'm very happy to have stumbled on this issue.

Here's what fixed it. As other mentioned running the following command to downgrade your firmware works.

```rpi-update 5fc4f643d2e9c5aa972828705a902d184527ae3f```

I selected yes on both warning prompts. The one about boot partition size (irrelevant as it concerns Pi4 and Pi5 only) as well as the one telling you it's a bad idea to invoke `rpi-update` without being told to do so.

Once finished, I rebooted and since then, no more freezes.

**Comment by jorgedeand** [comment]
> Thanks But there is no command line on HAOS

I'm also running on HAOS. I found that you can downgrade to a HAOS version to a one that has a lower linux kernel version than the working one. For mi in RPi3B, HAOS 12.0 works like a charm. Then wait to update HAOS when finally includes kernel 6.7+ for your system.

In order to downgrade HAOS version I did the following:
In the addon File editor: in Settings/Execute shell command
`ha os update --version 12.0`

**Comment by JacekKac** [comment]
can sombody confirm if is it fixed? i run into a hangup once again after upgrading to newest kernel not sure if this was the reason but i can boot without the dongle connected.

**Comment by Bummvoll** [comment]
I would also second the question - running into similar issues now on HA OS 16.1

Is this related to the same old cause?

**Comment by pbasista** [comment]
For what it is worth, I am also experiencing freezing of the entire Raspberry Pi 3 Model B Rev 1.2 since recently. It is reproducible every time while starting zigbee2mqtt with a Sonoff USB dongle adapter (not sure which version exactly) and a known good configuration that used to work on the same hardware with the same adapter before. It seems like it started happening after a software update.

I am running Arch Linux ARM with Linux kernel 6.12.47-1-rpi on armv7l architecture.

I am wondering why this issue keeps reoccurring with the newer Linux kernels. Perhaps it is indeed caused by some USB power delivery issue which was not actually fixed properly the last time.

Edit: Also for what it is worth, the same adapter with the same firmware on the same device with the same power source works correctly and does not freeze at all when the operating system is Arch Linux ARM with Linux kernel 6.16.7-1-aarch64-ARCH on aarch64 architecture.

It appears like the issue occurs with the vendor-provided Linux kernels but not with the mainline ones.

**Comment by CreatureFear** [comment]
I think I experienced issue here. It was driving me crazy.

The whole story : 
    I upgraded my old HA OS from 12 to HAOS 16.2 with all the plugins  (Z2M v1.40 to Z2M v2.6.2) and then my RPI kept crashing everytime Z2M was starting.
    When I looked at the Z2M logs the RPI hangs just after the log message.
    ` info: z2m: Starting zigbee-herdsman (6.1.5)

So I tried a few things: 
    - I downgraded from HAOS 16.2 to 15.2 as chatgpt suggested lots of PI3B+ experienced problems with the newer versions, more resource intensive, that caused out of memory issues
    - I downdgraded to Z2M 1.40 as i found that the latest version wasn't working with the dongle's old firmware.
    - I upgraded my Sonoff Dongle E's firmware to 7.4+ and switched from ezsp to ember adapter. That was causing Z2M to fail at startup but wasn't enough. 
    - Then changed my power supply to a 5V-5A psu and it worked once (by some strange magic) so I thought it was a PSU problem but then i had issues again
    - then I tried some tweaks in Z2M's configuration.yaml  as chatgpt suggested I had a "brown-out" due to a voltage drop when the Sonoff dongle EFR32MG21 chip was initializing at the  zigbee-herdsman startup.
  
I tried all kinds of solutions to because I was conviced HAOS 16.2 would cause other issues, preventing my HA to start. 
But after all, I found this topic. and figured that it was a Linux Kernel problem between haos 12 (that i was using) and (15.2) 

Finally, I put my last hope in the fact that maybe the Linux Kernel v6.12.43 used in HA OS 16.2 would fix the issue, and that my Pi3B+ would still run HomeAssistant without crashing due to resource issues

What almost worked ( Edit : As I wrote in a later post, this might be due to a slightly different startup sequence, where i had disconnected the dongle prior to launching Z2M) : 

- I tried once again HAOS 16.2 
- flashing my dongle to v7.4+ and configuring "ember" adapter in Z2M
- (and for a sanity check)  I completely uninstalled Z2M and deleted config directly before trying again as I wanted to have a vanilla addon config, because I wasn't sure the rollback I did wasn't causing issues.

Edit : After a reboot and an upgrade from HA Core 2025.10.2 to HA Core 2025.10.3, I can't start Z2M cleanly anymore. I rolled back to 2025.10.2 but it desn't make it work...I don't know what it do besides  using my new RPI5 that I intended to keep for another project...

**Comment by jorgedeand** [comment]
I gave up and bought a SLZB-06 to use it via PoE, though I hadn't have time to try it yet.  I also wanted to switch from the RPi3B to a RPi4 and do a fresh install of everything.

Before that, I will try updating the firmware of my TI LAUNCHXL-CC26X2R1 and then update the OS version to see if that fixes the problem for me too. I'll keep you updated ASAP.

**Comment by pbasista** [comment]
> I don't know what it do

I would suggest to use the mainline Linux kernel. From my experience, it works correctly there.

The disadvantage is that not every advertised Raspberry Pi 3 feature works out of the box with the current mainline Linux kernels. A notable example is hardware accelerated video decoding and encoding. But as long as you do not need that and plan on using the Raspberry Pi e.g. as a Home Assistant server, it should probably be fine.

For instance the Arch Linux ARM offers a Raspberry Pi 3 image with the mainline Linux kernel. It uses the U-Boot bootloader and therefore things need to be configured slightly differently than what is common with images provided by the Raspberry Pi Foundation. For instance, editing `/boot/config.txt` has no effect and the U-Boot configuration needs to be edited instead to provide correct boot parameters to the Linux kernel. As long as you are okay with using that, it should be a fair option to consider, in my opinion.

**Comment by jonesMeUp** [comment]
I used the older kernel version since i installed a new trixie with no problems, so i went never in problems again and can't say anything about haos.
but did you try this:
`Freeze ab Kernel 6.5 → behoben ab Kernel 6.7, Workaround per dtoverlay=dwc2,dr_mode=host oder durch Deaktivieren von hciuart in älteren Kerneln.`

**Comment by CreatureFear** [comment]
Thanks for the feedbacks
Yes, downgrading to the older kernel version is the best bet, as you guys recommended it earlier.

For those looking for another solution while running the latest HA OS version, I found this workaround.
https://github.com/raspberrypi/linux/issues/6172#issuecomment-2311707242

Works for my setup :  
- RPi 3B+ 
- HA OS 16.2 (`uname -a` returns kernel  6.12.34-haos-raspi) 
- HA Core 2025.10.3
- HA Supervisor 2025.10.0

I figured that might be a related issue to mine which is : 
=> Startup of Zigbee2MQTT crashing the Pi 3B+ when my Sonoff Zigbee Dongle E plugged in.

Workaround steps : 
- stop z2m add-on and don't let it start at HA start
- unplug the dongle
- restart host
- wait some minutes after restart
- plug the dongle
- start z2m

It's an annoying process, but I can handle it for now. I'm not restarting my HA very often.

On a side note, he're maybe a lead for a fix ( I'm am by no means a Linux guru) :
  This problem seems to imply a USB driver  "[default dwc_otg driver which causes a complete system freeze](https://github.com/raspberrypi/linux/issues/6172), with watchdog restarting the device shortly after." 
  
  I asked Ai and it suggested to disable it with these steps 
  edit `cat /proc/cmdline.txt`
  and add  these commands  `dwc_otg.fiq_fsm_enable=0 dwc_otg.fiq_enable=0` 
 It didn't solve the problem, but who knows? Maybe an expert knows what to do with that info.
