### ISSUE TITLE
GS SRHMP-I1 not working properly

### ISSUE THREAD

**Issue by baradetsky** [Koenkk/zigbee2mqtt#22917]
### What happened?

The GS SRHMP-I1 siren doesn't seem to be working properly (https://www.zigbee2mqtt.io/devices/SRHMP-I1.html)
I cant select the mode, level, or strobe cycle\level in the Z2M user interface, it only works in one single mode (emergency mode, maximum level). HA, when paired, sees only the battery and linkquality. Through the "siren" class the device could not be configured - its not working at all. The device only works through the service: mqtt.publish:
payload_on: '{"warning": {"duration": 600, "mode": "emergency", "strobe": true}}'
Please help

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

20210320

### Adapter

20210320

### Setup

HA Supervised / Docker / Debian 12

**Comment by vertos7** [comment]
The problem is the same with the GS SRHMP-I1 siren. When paired, HA sees only the battery and the quality of the connection.
![Захват45](https://github.com/user-attachments/assets/6d9dd8b3-695d-49ac-a209-20eab5bf72b2)
![Захват46](https://github.com/user-attachments/assets/5c2b6b16-14f6-46b2-bf0e-260494c81dec)
![Захват44](https://github.com/user-attachments/assets/83b68aee-01df-4825-a748-a6481fd35214)
