### ISSUE TITLE
[update device support]: Futurehome Thermostat

### ISSUE THREAD

**Issue by ChillZwix** [Koenkk/zigbee2mqtt#23139]
### Link

Futurehome Thermostat does support power measurement now, and does pull in the Futurehome app with HUB, but missing in M2Z.  https://www.zigbee2mqtt.io/devices/TS0601_futurehome_thermostat.html

### Database entry

None

### Comments

Futurehome Thermostat does support power measurement now, and does pull in the Futurehome app with HUB, but missing in M2Z.

OTA from Futurehome support? 

### External definition

```shell
Add power
```

**Comment by PapsMan-No** [comment]
Is there any chance that this functionality could be added for the TS0601 based Futurehome Termostat?
The energy consumption data is exposed to the Futurehome hub via Zigbee, but since Futurehome went bankrupt and changed ownership in the middle of 2025, using the Futurehome hub requires a monthly subscription. Since that time I am no longer able to regulate energy consumption at home in a good way, because three of our main energy consumers at home are floor heatings regulated through this device.
Would be absolutely splendid if polling the existing power measurement value could be added for this device!

**Comment by PapsMan-No** [comment]
<3
