### ISSUE TITLE
BUG - [TS130F] calibration_time not writable

### ISSUE THREAD

**Issue by thibp** [Koenkk/zigbee2mqtt#23212]
### What happened?

I have an issue on latest-dev branch, which is not present on 1.38.0 (docker).
The device _TZ3000_1dd0d5yi which is using TS130F template, has calibration_time in read_only mode and cannot be set.
If we try to set it via mqtt, we got a converter error.

### Zigbee2MQTT version

latest-dev

### Adapter firmware version

20211114

### Adapter

zStack3x0

### Setup

Docker, MQTT, Home Assistant

**Comment by murtas** [comment]
Some motors may, depending on their size, weight and wear, take longer to open than to close. The calibration_time is often used to adjust for the difference open/close times. 

The upgrade of zigbee2mqtt from v1.38.0 to v1.39.0 broke my automations.

I think the issue was introduced in https://github.com/Koenkk/zigbee-herdsman-converters/commit/940dffe7739b2cb10f4e024dc8401b39c8307488 _(change from ea.state.ALL to ea.STATE)_
