### ISSUE TITLE
Integration problem : Legrand 067776(A) module

### ISSUE THREAD

**Issue by apages2** [Koenkk/zigbee2mqtt#23681]
### What happened?

Good morning,

I have a problem with the integration of the Legrand 067776(A) module.

when I physically press the button (up, down, stop), the feedback Z2M receives is always "action": "stopped".

z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Physique Volet Bureau', payload '{"action":"stopped","calibration_mode":"classic_nllv","color_mode":"xy","cover_mode":{"calibration":false,"led":false,"maintenance":false,"reversed":false},"device":{"applicationVersion":0,"dateCode":" \u000020221202\u0000\u0000\u0000\u0000\u0000","friendlyName":"Physique Volet Bureau","hardwareVersion":1,"ieeeAddr":"0x0040ceb","manufacturerID":4129,"manufacturerName":" Legrand","model":"067776A","networkAddress":54843,"powerSource":"Mains (single phase)","softwareBuildID":"003d","stackVersion":66,"type":"Router","zclVersion":2},"led_if_on":"OFF","led_in_dark":"OFF","linkquality":255,"position":50,"state":"OPEN","tilt":100,"update":{"installed_version":4015615,"latest_version":4015615,"state":"idle"},"update_available":false}'

While on the Legand app, the state looks different depending on the button.

Likewise, when I click on a Z2M action, nothing is sent to the Zigbee network (while it is when I click on the identity button).

Finally, there doesn't seem to be a "group" cluster in toZigbee. is this normal?

Best Regard

### What did you expect to happen?

I should receive an action like open, close, stop

### Zigbee2MQTT version

1.39.0

### Adapter firmware version

0x26780700

### Adapter

ConBee2

### Setup

Add-on Z2M on ODROID+jeedom

### Debug log

z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Physique Volet Bureau', payload '{"action":"stopped","calibration_mode":"classic_nllv","color_mode":"xy","cover_mode":{"calibration":false,"led":false,"maintenance":false,"reversed":false},"device":{"applicationVersion":0,"dateCode":" \u000020221202\u0000\u0000\u0000\u0000\u0000","friendlyName":"Physique Volet Bureau","hardwareVersion":1,"ieeeAddr":"0x0040ceb","manufacturerID":4129,"manufacturerName":" Legrand","model":"067776A","networkAddress":54843,"powerSource":"Mains (single phase)","softwareBuildID":"003d","stackVersion":66,"type":"Router","zclVersion":2},"led_if_on":"OFF","led_in_dark":"OFF","linkquality":255,"position":50,"state":"OPEN","tilt":100,"update":{"installed_version":4015615,"latest_version":4015615,"state":"idle"},"update_available":false}'

**Comment by apages2** [comment]
@FabianMangold

**Comment by FabianMangold** [comment]
Hi @apages2,



I'd have to check how my own devices behave, but for a start, do you have "HomeAssistant legacy triggers" enabled ?
If i remember correctly, those seem to interfere with the status. Please disable those should they be enabled, and let me know the outcome.



Fabian

**Comment by apages2** [comment]
Hello

 

I don't use homeassistant, but jeedom, so I don't have homeassistant integration activated

 

Best regards

 

De : FabianMangold ***@***.***> 
Envoyé : jeudi 22 août 2024 08:42
À : Koenkk/zigbee2mqtt ***@***.***>
Cc : apages2 ***@***.***>; Mention ***@***.***>
Objet : Re: [Koenkk/zigbee2mqtt] Integration problem : Legrand 067776(A) module (Issue #23681)

 

Hi @apages2,



I'd have to check how my own devices behave, but for a start, do you have "HomeAssistant legacy triggers" enabled ?
If i remember correctly, those seem to interfere with the status. Please disable those should they be enabled, and let me know the outcome.



Fabian

**Comment by apages2** [comment]
hello @FabianMangold 

were you able to check that the shutters were working? 

in particular the operation of the cluster group for this type of equipment, because I cannot control other shutters from 1 general shutter switch, as is the case with lighting switches for example

Best regards

**Comment by FabianMangold** [comment]
Hi @apages2 ,

I am sorry, unfortunately I have very little time lately, and i mostly far from the devices, which makes testing complicated!

Regarding the status, you are right, those do not work correctly at all. If i remember correctly, they have never worked flawlessly. If the Legrand app reports them correctly, we should be able to reproduce this too.
Could you please report how the switch behaves, i.e. what gets reported in the app when the roller goes up or down, gets stopped, when pressing the button (long / short) ?
The behavior might be somewhat different depending on the calibration mode, but since I don't have access to the Legrand App to compare, I'd appreciate if you could try to summarize the behaviour your switch(es) expose.

Regarding the group, I don't really know! I group the switches on higher level (not Zigbee) via automation, hence i've never paid attention.
Due to limited time at the moment, not sure if anyone else could take a look at this part of the issue ?

Thanks for your understanding.
Best,
Fabian

**Comment by apages2** [comment]
[https://github.com/Koenkk/zigbee-herdsman-converters/pull/7992](url)
