### ISSUE TITLE
When I control the Zigbee device, MQTT will send 2 command messages, which will cause the problem that some dimmable lamps suddenly go off after being turned on. 

### ISSUE THREAD

**Issue by yuanxin32323** [Koenkk/zigbee2mqtt#23794]
### What happened?

All along, my Zigbee lamps have occasionally had the situation where they suddenly go off after being controlled to turn on, occurring once or twice every day. This experience is very bad. Later, I monitored the MQTT messages and found that each command of the control device was repeatedly issued twice.
 By calling the services "turn_on" and "turn_off" of HomeAssistant, MQTT would receive 2 commands. 
By calling the service "toggle" of HomeAssistant, MQTT would receive 3 commands. Repeated commands have little impact on switch-type devices, but the impact on dimmable lamps is fatal, resulting in the situation where they suddenly go off after being turned on. 

![image](https://github.com/user-attachments/assets/9e92f209-41d2-458f-8761-42d239f89776)
![image](https://github.com/user-attachments/assets/33c002ee-8023-40a3-b9da-3decc3fc6c8f)

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

 20221226

### Adapter

CC2652P

### Setup

x86-64

**Comment by frag-duino** [comment]
I'm experiencing the same problem since the update to 1.40.0 yesterday:
Every message is being sent two times, which makes toggeling lights annoying:

![twice1](https://github.com/user-attachments/assets/2e3842c5-73a3-4214-ac41-75af6f2f89e6)
![twice2](https://github.com/user-attachments/assets/ba649da7-87b8-4505-bf92-036cb82419cc)
![twice3](https://github.com/user-attachments/assets/90db3edb-5f13-4a03-86d6-e299f2fff2d0)

I'm using:
Zigbee2MQTT version
[1.40.0] commit: 6fa1dabe
Coordinator type: ConBee2/RaspBee2
Coordinator revision: 0x26780700
Openhabian with openhab 4.2.1

**Comment by frag-duino** [comment]
Still facing the same problem with 1.40.1.
Found a workaround: Set a debounce of 0.1
