### ISSUE TITLE
OXT T263 left the network when multiple push a button

### ISSUE THREAD

**Issue by mateusz-jaworski** [Koenkk/zigbee2mqtt#23908]
### What happened?

I use home assistant version 2024.9.0 with Zigbee2mqtt in 1.40.1-1 and Sonoff usb dongle coordinatoor. With one device OXT T263 (3way zigbee relay), when multiple click button, this device left the network. I triend change connect switch to other line, without result. I need to turn on discover new devices to rejoin switch device

### How to reproduce it (minimal and precise)

Add OXT T263 to Z2M and connect switch without voltage to any lines, and click it multiple times i couple seconds.

### Zigbee2MQTT version

1.40.1

### Adapter firmware version

20210708

### Adapter

Sonoff Zigbee 3.0 USB Dongle plus

### Setup

HomeAssistant basen on OTA virtualmachine, device name "Ogrod"

### Debug log

[z2m logs.txt](https://github.com/user-attachments/files/16922808/z2m.logs.txt)
Device name 'Ogrod'

**Comment by feixm1** [comment]
Just to give some clue to the reporter of this issue and others reaching this topic. This is expected behavior and not connected to the Zigbee2Mqtt.

When switching the OXT switch input multiple times (I think 5) in a short interval, the device switches itself into pairing mode. This behavior is hard coded in the OXT device and cannot be changed.
