### ISSUE TITLE
Integrate Xiaomi MiJia Honeywell smoke detector in alarm system?

### ISSUE THREAD

**Issue by Smarti15** [Koenkk/zigbee2mqtt#240]
Hello, is it possible to integrate the Xiaomi MiJia Honeywell smoke detector into an alarm system. So if alarm is triggered, the smoke detector should also beep. At the moment I can not integrate the smoke alarm (integrated via the MiHome adapter) into the alarm system in the ioBroker because I do not have access to the alarm. Would be great if that's possible.

**Comment by Koenkk** [comment]
Its not possible to control the alarm manually.

**Comment by Smarti15** [comment]
Oh well, but thanks for the quick answer.

**Comment by tb-killa** [comment]
With original hub (Controller) you could trigger the Alarm.

**Comment by Koenkk** [comment]
@tb-killa interesting would be indeed nice if we could also do this

**Comment by tb-killa** [comment]
For this we have to sniff needing Information with original Controller and maybe we find the needing Code. I Google for it to check if groovy Code is availabel But didnt find it. Only test Button Code who could be implement. Sadly doesnt in Touch with smoke detector and Controller (gateway)

**Comment by tb-killa** [comment]
I´v found some more interessted code segments and informations:
https://github.com/athombv/homey/issues/2005
https://github.com/bspranger/Xiaomi/issues/59
https://pastebin.com/59rUTJKv

As it seems to be that the remote control for alarm isn´t available anymore, because i didn´t find informations about them in the system of a friend of mine who gave me short access to his system.
Have to search deeper, maybe we could get them working.

**Comment by Baseje** [comment]
Any progress?

Would be nice!

**Comment by tb-killa** [comment]
We should close this because actually there is no known way to remote trigger Alarm.

**Comment by tb-killa** [comment]
This seems to be no more available.
If i found some more Informations i will reopen.

**Comment by Smarti15** [comment]
Okay, that would be really great, if you could use the smoke alarm simultaneously as an auditory alarm sound. That concludes the post.

**Comment by AnhDuc85** [comment]
Any chance to set the density level for JTYJ-GD-01LM/BW?

**Comment by tb-killa** [comment]
@AnhDuc85 Actually i don´t know ... because of lack of device themselve.
But i figure out that it seems to be posible to trigger the alarm by the use of the ``IAS WD`` Cluster ..
Sadly this seems to be some special stuff and actually i see that ``IAS`` themselve isn´t fully implemented on zigbee shepherd. 
Heimann Siren seems to be also remote enableable like mentioned with ``IAS WD`` ...

look at this: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/404#issuecomment-384163525 there seems to be some more sort of siren who could be remote triggered ....

**Comment by sascha777** [comment]
I am also looking for a way of using my Mijia smoke detectors as an alarm.
Did someone managed to set smoke density or trigger the alarm or the self test?
