### ISSUE TITLE
Tuya ZG-227Z _TZE200_a8sdabtg reports battery always 100%

### ISSUE THREAD

**Issue by mleone87** [Koenkk/zigbee2mqtt#24120]
### What happened?

I have 5 devices of this kind, all of them always report 100% battery. 3 out of 5 stopped working silently because the battery went to 2600mV or similar.

Database
`{"id":19,"type":"EndDevice","ieeeAddr":"0xa4c138ea88053713","nwkAddr":8781,"manufId":4417,"manufName":"_TZE200_a8sdabtg","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":770,"inClusterList":[0,3,57346,61184,60928,57344,1,1026,1029],"outClusterList":[3,57346,61184,60928,57344,1],"clusters":{"genBasic":{"attributes":{"manufacturerName":"_TZE200_a8sdabtg","zclVersion":3,"appVersion":131,"modelId":"TS0601","powerSource":3}},"msTemperatureMeasurement":{"attributes":{"measuredValue":2210}},"msRelativeHumidity":{"attributes":{"measuredValue":6420}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":131,"stackVersion":2,"hwVersion":1,"swBuildId":"0122052017","zclVersion":3,"interviewCompleted":true,"meta":{"configured":217189513},"lastSeen":1727434811460}`

### What did you expect to happen?

Battery should report at least an estimation

### How to reproduce it (minimal and precise)

Just use this device and see

### Zigbee2MQTT version

1.40.1

### Adapter firmware version

20230507

### Adapter

Zdongle-E

### Setup

Docker

**Comment by pmpbpl** [comment]
Same here.
Firmware: 1.40.2
Hardware: zStack3x0 20230507

**Comment by mleone87** [comment]
`"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}}`

the battery report seems skewed

**Comment by Koenkk** [comment]
The number needs to be divided by 2, so 200 = 100% battery

**Comment by mleone87** [comment]
PR submitted

**Comment by nephrotranz** [comment]
Unfortunately I would like to reopen this thread.

I also own three of these devices and they all showed a battery level of 100% since 23rd of January 2024 until the update to Z2M 2.0.0.
After the update the battery levels of all three devices suddenly went down to 50% and - although I read the release note -  I found this a bit suspicious.

Because of that I put a brand new battery into one of the devices and waited 12 hours now but the battery level is still at 50%. At the same time, because I was curious, i did put the old battery from this device into a Hue dimmer v1 and this one went up from 34% to 100% within a few hours.

**So battery level really is still at 100% after nearly one year.**

In the database.db my devices also show a voltage value which is 29 or 30 for all three batteries. As 3 V is the voltage of a CR2450 battery at 100% that also shows that they are measuring correctly.

Additionally I put one of the thermometers into our freezer last August and the battery level went down to 10% when it was at approx. -19°C for a fews days, so it was definitely working.

I can only imagine that @mleone87 had some faulty devices or something like that.
