### ISSUE TITLE
Device disconnection on Ember network

### ISSUE THREAD

**Issue by Belox86** [Koenkk/zigbee2mqtt#24253]
### What happened?

Tuya Device TS0004 ([MHCOZY TYWB 4ch-RF](https://www.zigbee2mqtt.io/devices/TYWB_4ch-RF.html#mhcozy-tywb-4ch-rf)) disconnect/kicked out from the network.
Coordinator is a SONOFF Dongle-E using ember driver.
Stopping the addon Z2M, detaching the coordinator, then after few minutes, plug and restast addon does not solve.

Device is 1m away from a Sonoff Dongle-E with router FW.

### Zigbee2MQTT version

1.40.1-dev (commit #d3de77d)

### Adapter firmware version

0.7.4

### Adapter

SONOFF Dongle-E

### Setup

Add-on on HomeAssistant on a Pi4

### Debug log

i attach here the full log of two weeks and what is in my opinion the relevant part regarding the disconnection.
Particularly, the device that disconnect from the network is the 'Multi Switch Ingresso'; what it seems to happen is the following (see relevant_log.log):
1. ROUTE_ERROR_NON_TREE_LINK_FAILURE for "25425" (former address of  'Multi Switch Ingresso')
2. device reconnect(not sure)? (event "type":"device_announce")
3. ROUTE_ERROR_ADDRESS_CONFLICT for "25425", Corresponding devices kicked from the network.
4. Device rejoin with address "21490" ?
5. ROUTE_ERROR_ADDRESS_CONFLICT for "21490", Corresponding devices kicked from the network.
6. Device fails to reconnect and is not able to rejoin the netwrok.

[log.log](https://github.com/user-attachments/files/17278529/log.log)
[relevant_log.log](https://github.com/user-attachments/files/17278530/relevant_log.log)

**Comment by Nerivec** [comment]
Looks like some devices are misbehaving (the conflict is handled by the network, Z2M has no say in it, it can only "witness" it).
Can you confirm the issue is still present:
- after updating to 1.40.2?
- after re-flashing the 7.4.4 firmware?

Assuming you have a recent `coordinator_backup.json`, you could also try to force the adapter to [leave the network with Ember ZLI](https://github.com/Nerivec/ember-zli/wiki/Stack#leave-network). It will force Z2M to restore the backup on next start, which hopefully clears the mess of network addresses you currently seem to be experiencing.
