### ISSUE TITLE
Changing enable/disable status of devices not possible in GUI

### ISSUE THREAD

**Issue by OJBender** [Koenkk/zigbee2mqtt#24810]
### What happened?

Unchecking a devices' "disabled" button reverts the button back to disabled. 
It is that "Christmas Lights" function described in the [documentation](https://www.zigbee2mqtt.io/guide/configuration/devices-groups.html#common-device-options). The work-around: Seek devices.yaml and delete the lines
<img width="359" alt="Screenshot 2024-11-18 at 09 37 06" src="https://github.com/user-attachments/assets/4cb9c35b-9932-41bd-b367-e990349523ba">
 'disabled: true' for the devices in scope. 

### What did you expect to happen?

Unchecking "disabled" should re-enable the device. 

### How to reproduce it (minimal and precise)

Click on a disabled device
Select the 5th tab "Settings"
Uncheck the the "disabled" box
The box re-activates after a few seconds

### Zigbee2MQTT version

1.41.0

### Adapter firmware version

20240716

### Adapter

SLZB-06P7

### Setup

barebone intel lenovo

**Comment by Great-Chart** [comment]
There is a good demonstration of this issue within https://github.com/nurikk/zigbee2mqtt-frontend/issues/2135
Additionally a GUI workaround (press enter immediately AFTER selecting the tick-box) and I think it's more within "frontend" (managed by others) rather than explicitly within Z2M itself.

It's seemingly a known issue and no doubt more parties re-connecting seasonal lights / switches etc may get some traction here.
But for others finding these posts refer to the workaround referenced in the above link
