### ISSUE TITLE
Deletion of old log directories

### ISSUE THREAD

**Issue by spudwebb** [Koenkk/zigbee2mqtt#25256]
### What happened?

I have a lot of log directories in data/log. I see a `cleanup` method in the logger class that seems to only keep the 10 most recent directories but it doesn't seem to be called anywhere. What is the expected behavior? Is there a way to limit the number of log directories to keep?

https://github.com/Koenkk/zigbee2mqtt/blob/bc6eccf6152c4cd91e75309f7ea0b8ad4e8835d4/lib/util/logger.ts#L222-L239

### Zigbee2MQTT version

1.40.2

### Adapter firmware version

7.4.3

### Adapter

Sonoff Dongle-E

### Setup

Z2M running from HomeSeer ZigbeePlus plugin on Windows PC

**Comment by Koenkk** [comment]
fixed in https://github.com/Koenkk/zigbee2mqtt/pull/25282

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now. Note that the dev branch currently contains **breaking changes**, see https://github.com/Koenkk/zigbee2mqtt/discussions/24198
