### ISSUE TITLE
support new coordinator 

### ISSUE THREAD

**Issue by zhapwey** [Koenkk/zigbee2mqtt#3307]
hi,

At the cost of texas zigbee 3.0 chips, is there a chance to support the NXP5189 chips?
I don't know if this is possible but I would like to know?

Best Regards,

**Comment by Koenkk** [comment]
In order to add support for new adapters, it has to be added to zigbee-herdsman (the library where zigbee2mqtt is based on). Recently this has been done for the Deconz (Conbee) adapter. The following interface has to be implemented in order to do this: https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/adapter.ts
