### ISSUE TITLE
No converter available for 'LLKZMK11LM'

### ISSUE THREAD

**Issue by iStitch07** [Koenkk/zigbee2mqtt#3503]
Hello. In debug mode in z2m log logged this message:

```
zigbee2mqtt:debug 2020-05-06 22:46:51: No converter available for 'LLKZMK11LM' with cluster 'genTime' and type 'read' and data '["time"]'
```

Its not bug, because LLKZMK11LM working fine, but maybe we lost some features? :)

**Comment by Koenkk** [comment]
`genTime` messages are already handled by zigbee-herdsman (the underlying zigbee library), therefore they don't have to be handled anymore in zigbee2mqtt. In order to avoid further confusion I disabled the `No converter available..` logging for these messages. Available in the latest dev branch.

Thanks!
