### ISSUE TITLE
Terncy PP01

### ISSUE THREAD

**Issue by Suppv** [Koenkk/zigbee2mqtt#3591]
Zigbee multi-functional button Terncy PP01
have a 2 occupancy sensor, and its triggered to "on" and not reset to "off" 

after a timeout is required to reset the motion sensor.

**Comment by max-te** [comment]
The problem is that https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L4155-L4193 does not set up a timeout for the occupancy, like https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L489-L508 does.
We should probably do something along the lines of https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L4927-L4934

I'll try to set something up and send a pull request there.
