### ISSUE TITLE
zigbee2mqtt service don't start

### ISSUE THREAD

**Issue by tuga49** [Koenkk/zigbee2mqtt#3635]
Hi. I'm facing a problem with zigbee2mqtt. The CC is detected, but I cant start the service. Here is my log: 

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.13.0~prestart: zigbee2mqtt@1.13.0
6 info lifecycle zigbee2mqtt@1.13.0~start: zigbee2mqtt@1.13.0
7 verbose lifecycle zigbee2mqtt@1.13.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.13.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/zigbee2mqtt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle zigbee2mqtt@1.13.0~start: CWD: /opt/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.13.0~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.13.0~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.13.0~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.13.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid zigbee2mqtt@1.13.0
15 verbose cwd /opt/zigbee2mqtt
16 verbose Linux 4.15.0-101-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.13.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.13.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

Can anyone help me solve this? Thank's

**Comment by doenietzomoeilijk** [comment]
I have the same issue, for me it popped up after updating to the newest release. A reboot of the host solves it, for a while. It's been less than 24hrs since the last reboot and for some reason it stopped responding again. Attempting to restart the container gives an infinite loop of the service being started and crapping out with the above message.

I'm running zigbee2mqtt from a Docker container on a Raspi 4 4GB. Things have been running peachy for ages before this problem started. I'll keep an eye on timing and see if I can find anything in the systemlog when I find it unresponsive again.
