### ISSUE TITLE
Is ConBee, 2.4 GHz ZigBee USB ZigBee gateway supported

### ISSUE THREAD

**Issue by ghasemikasra39** [Koenkk/zigbee2mqtt#400]
I wanted to know whether or not, other gateways such as [ConBee, 2.4 GHz ZigBee USB ZigBee gateway](https://www.amazon.com/NEW-gateway-compact-certified-operating/dp/B01FDWOIHK/ref=lp_15057818011_1_1?srs=15057818011&ie=UTF8&qid=1537600916&sr=8-1) can be used instead of the CC2531 USB sniffer.
If it is possible, what configuration must be done ?

**Comment by ptvoinfo** [comment]
Currently, only TexasInstruments chips are supported.

**Comment by ghasemikasra39** [comment]
Where can I find the supported devices ? (alternatives to the CC2531 USB sniffer)

**Comment by ryanbeaton** [comment]
https://github.com/Koenkk/zigbee2mqtt/wiki/Supported-sniffer-devices

**Comment by ghasemikasra39** [comment]
Thank you for your answers. I have one more question:

**Comment by WagnerBeccard** [comment]
@ghasemikasra39 https://github.com/Koenkk/zigbee2mqtt/blob/master/README.md

Zigbee2mqtt ist a mqtt Bridge. 
It collects the zigbee messages and publishes mqtt messages to work with open source projects.

**Comment by ciotlosm** [comment]
If you plan to go offtopic with the discussion, might be worth renaming the issue or closing this an opening a new one. It helps people make sense of the issue list ;)

**Comment by yamlCase** [comment]
> https://github.com/Koenkk/zigbee2mqtt/wiki/Supported-sniffer-devices

updated link to supported devices @ryanbeaton 
https://www.zigbee2mqtt.io/information/supported_devices.html

**Comment by BuhtigithuB** [comment]
Hi,

ZHA support ConBee2 dongle with help of Zigpy (https://github.com/zigpy/zigpy-deconz), can we make zigbee2mqtt support ConBee2 with help of that library? Since zigbee2mqtt seems to have a lot of traction and support a lot of devices (in particular ST218 : https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/ST218.md which zigbee2mqtt appears to be the only home assistant compatible ressource to support)

I could help in bringning in the support of ConBee2, but I will need help to do so...

Thanks

re-open

**Comment by Koenkk** [comment]
@BudBundi dresden itself is already working on this (https://github.com/Koenkk/zigbee-herdsman/issues/72)

**Comment by BudBundi** [comment]
@Koenkk thank you for answering me a question I never ask ;)

I wish you a healthy start into the New Year.
