### ISSUE TITLE
Setting scene or multiple lights from HA fails

### ISSUE THREAD

**Issue by sknsean** [Koenkk/zigbee2mqtt#407]
Setting lights one by one goes fine, but all off or setting a  scene, some of the commands does not set a light.

I have attached some logs. (Hope that helps)
https://paste.pound-python.org/show/1CoXwOFcmnbAhy3HlFhJ/

**Comment by Koenkk** [comment]
I think this is caused because of too many messages at one time.

**Comment by sknsean** [comment]
Yes exactly my thoughts :+1: 
I haven't looked at the code, but is there a FIFO we could and a small delay between the transmissions?
I'm setting 5 bulbs in a scene

**Comment by Koenkk** [comment]
Yes, that's the thing that should be added.

**Comment by keigezellig** [comment]
I have (maybe) a related problem. I have 10 IKEA bulbs and sometimes when i try to switch them all on/off at the same time through HA, not all bulbs react correctly (some stay on or some stay off)
This sometimes also happens when switching on/off an individual bulb. When i look at the zigbee2mqtt log  i see that the command is sent, but there is no reply that it's turned on/off.
This happens randomly.

**Comment by kiucheng** [comment]
I have the same issue with grouping 3 trådfri bulb together. I would say 80% of the time it works but sometime it leaves one bulb untouched. I got around with not using group in HA but adding 1 second delay in the automation. I hope there will be some kind of queuing mechanisms in zigbee2mqtt

**Comment by Koenkk** [comment]
@kiucheng this is one of the features of 0.2.0: https://github.com/Koenkk/zigbee2mqtt/releases/tag/0.2.0 (https://github.com/Koenkk/zigbee2mqtt/issues/529)

**Comment by kiucheng** [comment]
Thanks! Does it mean this issue can be close now?

**Comment by Koenkk** [comment]
Yes, thanks @kiucheng

**Comment by sknsean** [comment]
Thanks will test
