### ISSUE TITLE
Hue Dimmer returns brightness as 255

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#4163]
# Bug Report
## What happened
Recently the we conclude that the range for brightness was 0-254, and most bulbs seems to have been fixed to reflect this (yay) but looks like the Hue Dimmer still returns 255 as max.

```
{"brightness":255,"counter":1,"linkquality":84,"update":{"progress":6.67,"remaining":2665,"state":"updating"}}
```

Other remotes might be effect, but my ikea remote seem fine as they emit brightness_up/down/stop events instead.

## What did you expect to happen
This to also be 254

## How to reproduce it (minimal and precise)
Pair a Hue Dimmer and set the 

## Debug Info
Zigbee2MQTT version: 1.14.3-dev (9f15511)
Adapter hardware: CC2531
Adapter firmware version: `{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20200728,"transportrev":2},"type":"zStack12"}`

**Comment by MattWestb** [comment]
I think you is meaning the RWL021 its one mixed LL and HA device.
Its having the dimmer endpoint as LL and reporting ZCL 1 = not ZB3.
And its having one HA endpoint as HA simple sensor.
Its don't have GP basic endpoint = not ZB3.

If it was one ZB3 device is suld not reporting any Level or On/Off.
Its one "10 Dimmer switch" device if looking in the ZB3 appendix "ZigBee Lighting & Occupancy  Device Specification Version 1.0 " and controller devices in ZB3 shall not reporting any attributes (battery / system status attributes is on the ZB3 power cluster) only lights and sensors shall do attribute reporting.

And its not only 255 (0xfe) that is forbidden its also 0 (0x00).

>27.4.1.1 Attributes 
 For devices implemented according to this specification, the CurrentLevel attribute SHALL be 
 interpreted as follows: 
  A value of 0x00 SHALL not be used. 
  A value of 0x01 SHALL indicate the minimum level that can be attained on a device. 
  A value of 0xfe SHALL indicate the maximum level that can be attained on a device. 
  A value of 0xff SHALL represent an undefined value. 
  All other values are application specific gradations from the minimum to the maximum level. 

But back to your dimmer switch. Is one Philips HUE as my and its certified as one LL product and the standard is "HUE" but its working well.
And very likely all of your IKEA lights is ZB3 certified (if not having one old RGBWW and some old drives) so 1-254 is the range for attribute reporting as ZB3 light devices.

**Comment by sjorge** [comment]
Oops I made a type in the title, my Hue Dimmer is actually returning a max of 255!

It’s a 324131092621 in my case

**Comment by Koenkk** [comment]
Should be fixed.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by sjorge** [comment]
Updated this morning, still have the issue:
```
{"action":"on-press","battery":100,"brightness":255,"counter":1,"duration":0,"linkquality":52,"update":{"state":"idle"}}
{"action":"down-hold-release","battery":100,"brightness":145.1,"counter":1,"duration":1.986,"linkquality":47,"update":{"state":"idle"}}
{"action":"up-press","battery":100,"brightness":241.1,"counter":2,"duration":0,"linkquality":47,"update":{"state":"idle"}}
{"action":"off-press","battery":100,"brightness":255,"counter":1,"duration":0,"linkquality":47,"update":{"state":"idle"}}
```

**Comment by Koenkk** [comment]
Thinking about it a bit more, I'm not sure if we should do this. 255 is often considered the max brightness, while it may be in sync with Zigbee2MQTT max brightness, it ins't when for example controlling non zigbee lights with this and when controlling bulbs via Zigbee2MQTT with this it's only a cosmetic issue since setting brightness 255 works fine. 

@MattWestb in https://github.com/Koenkk/zigbee-herdsman-converters/commit/8d19093618851e13ea1f502e8b0b6eddb8c3fdef#commitcomment-41705651 you mentioned some docs, can you provide a better pointer to it/screenshots? I'm unable to locate them.

**Comment by MattWestb** [comment]
Is the originale from zigbeealliance OK ?

https://zigbeealliance.org/wp-content/uploads/2019/11/docs-15-0014-05-0plo-Lighting-OccupancyDevice-Specification-V1.0.pdf

**Comment by Koenkk** [comment]
@MattWestb I think so, what paragraph should I look at?

**Comment by MattWestb** [comment]
27.4.1.1 Attributes

**Comment by Koenkk** [comment]
![image](https://user-images.githubusercontent.com/2892853/91095739-1fea0980-e65d-11ea-803e-1c19407d7ff0.png)

I don't understand your point, according to this 0xFF (255) = undefined and 0xFE (254) = max brightness

**Comment by MattWestb** [comment]
You should trading "1 Introduction" first for understanding how to imprenting it as one appendix to ZB3s ZCL.

Yes and 0x00 is not use = forbidden

**Comment by Koenkk** [comment]
@MattWestb note that this is actually not send to bulbs, is just a reference value to be used in automations, therefore I think strictly complying to the ZCL standards make no sense in this case. Not providing a 0 is not feasible, since sending brightness 0 to Zigbee2MQTT means turn this bulb off, users would not be able to durn bulbs off anymore using this brightness value.

**Comment by MattWestb** [comment]
I think that is the intention of the "restricted" values. The interpretation should normally be done in the other end in the HA system and Z2M is more or less only one piped transport from the device and the HA system. If the HA system its interpreting  0x0ff as undefined or falsely as maximal level its one falcy thing in the HA system.
The values is the current light level that the device (light) is reporting to the coordinator.
The Hue dimmer switch should not reporting any value (is one "23 Non-color controller") or then 0xff because it can knowing what level the bounded device (lights) have if then have being changed from other controller or coordinator.
But as i have saying its LL (no ZCL) and not ZB3 (with ZCL) if looking on the certificate (latest dated 2016) so more or less pre ZB3.

Back to the 255 is used by one device (light) that don't knowing the level of the light and reporting the attribute the the coordinator = OK (if its possible that the device do not knowing it or not). 
The HA system should imprinting it as unknown light level.
Then back to my comments. Way "deleting" the 255 then the HA system is needing it for knowing the status of the light device ?
Its the same with 0 its the HA system that shall (not) imprinting as the light is off if not imprenting the on/off cluster attribute report (that i think its the right way and ignoring the 0 light level).

**Comment by Koenkk** [comment]
@MattWestb the brightness is not sent by the hue dimmer, it's a mocked value based upon certain commands being received: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L3057

**Comment by MattWestb** [comment]
OK. Then the range is 1-254 and the HA system can't (hopefully) making it wrong with 0 or 255.
