### ISSUE TITLE
Multiple Reports Of Same Topic From Sonoff BASICZBR3 Devices

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [Koenkk/zigbee2mqtt#4527]
## What happened
When reporting is enabled, I receive singular reports for each of my endpoints, apart from Sonoff devices which seem to report the same attributes multiple times. I don't see a way of being able to debounce reporting in the config.

## What did you expect to happen
A singular report to be sent to the MQTT topic for each report attribute of the Sonoff devices

## How to reproduce it (minimal and precise)
Have Sonoff devices (BASICZBR3) on a Zigbee2MQTT network, and have reporting enabled in the config

## Debug info
Zigbee2MQTT version: 1.115.0-Dev
Adapter hardware: CC26X2R1
Log messages:
```
Zigbee2MQTT:debug 2020-10-02 09:35:54: Received Zigbee message from 'Bedroom Table Lamp', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-10-02 09:35:54: Received Zigbee message from 'Bedroom Table Lamp', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-10-02 09:35:54: Received Zigbee message from 'Bedroom Table Lamp', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-10-02 09:35:54: Received Zigbee message from 'Bedroom Table Lamp', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2020-10-02 09:35:54: Received Zigbee message from 'Bedroom Table Lamp', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
```

**Comment by Koenkk** [comment]
This is expected behaviour and was implemented in https://github.com/Koenkk/zigbee2mqtt/issues/3687. The switch reports the same message multiple times and Zigbee2MQTT ignores the duplicate report. The duplicity is detected based on the transaction sequence number in the Zigbee messages. It's not normal for a device to transmit a message multiple times with the same transaction sequence number, in fact only some Sonoff devices to this.
