### ISSUE TITLE
Müller Licht MLI-404011: Scene keys not working

### ISSUE THREAD

**Issue by renne** [Koenkk/zigbee2mqtt#4730]
## What happened
MLI-404011 is paired with zigbee2mqtt, binding endpoint 1 of the MLI-404011 to zigbee2mqtt group 6.
Power/standby-, color-, color-temp and brightness buttons work if the all devices group on the MLI-404011 is selected.
The scene buttons do not produce any MQTT commands/log output. If the remote is switched to one of it's device groups MQTT commands contain "action_group":7, "action_group":8 or "action_group":9 and the MQTT commands show pressed scene buttons, but no binding possible.

## What did you expect to happen
zigbee2mqtt should configure 4 endpoints (one per group on the remote) and handle pressed scene buttons of all remote groups.

## How to reproduce it (minimal and precise)
1) Pair MLI-404011 with zigbee2mqtt
2) Bind endpoint 1 to a zigbee2mqtt group (there is only one endpoint)
3) Press the scene buttons in all four groups of the MLI-404011

## Debug info
Zigbee2MQTT version: GIT update from  about one hour ago
Adapter hardware: CC26X2R1 (slaesh)
Adapter firmware version: zStack3x0

**Comment by grostim** [comment]
Well,

I see two issues in one here:

- First , you report that there should be 4 endpoints configured by Z2M.
I'm not an expert but i guess this is related to the remote firmware. 
The remote shows up as on endpoint.
The group binded to the endpoint is for the "3 leds" mode.
Led1 is automatically configure with the group with the next id.
led2 the next one
etc...
If you don't manually change the binding, the remote is binded by default with groups 16387 to 16390

This is not very convenient (especially if you have several remote of this model in your house and that you want to a partial overlapping of the groups controlled between two remotes; but i think there is nothing Z2M can do about it.


-Second , you have noticed that the scene events are not reported for the first group (with 3 leds) of the remote.
I have noticed the same.
For me the scene events are well reported for the 3 other groups.

This may be caused by the remote or by Z2M. I don't have taken the time to investigate for the time being.

**Comment by renne** [comment]
Bump
