### ISSUE TITLE
Xiaomi WSDCGQ11LM excessive battery usage

### ISSUE THREAD

**Issue by embcla** [Koenkk/zigbee2mqtt#5499]
## What happened
Installed zigbee2mqtt in HA yesterday, in 24h the battery of my Xiaomi WSDCGQ11LM went from 100% to 74%

## What did you expect to happen
I have another 7 such sensors hooked to a phoscon addon on another HA instance for 3 months, all of them above 80%.
## How to reproduce it (minimal and precise)
I'm not sure, I suspect there is a higher polling rate that's draining the battery.
## Debug info
Zigbee2MQTT version: 1.16.2.2
Adapter hardware: Conbee II
Adapter firmware version: 26660700

##Additional Info
All my sensors connected to an HA instance running the phoscon module show this kind of graph
![image](https://user-images.githubusercontent.com/54371771/103445600-b5824f00-4c76-11eb-8e84-7ca50a5081b5.png)

While the sensor connected to zigbee2mqtt shows the following
![image](https://user-images.githubusercontent.com/54371771/103445606-d0ed5a00-4c76-11eb-971a-47500b67e198.png)

I notice the datapoints are much more dense than my other sensors, hence my supposition of excessive polling

**Comment by Boia11** [comment]
Hi, I had this problem with a RTCGQ11LM ... the battery drain was caused by loop of sending occupancy.
I solve with removing and replacing the battery and re-pairing device (removing device)

**Comment by Koenkk** [comment]
Unlikely this is due to a z2m issue.

> I suspect there is a higher polling rate that's draining the battery.

This sensor is never polled (it doesn't even support it), the sensor reports when necessary.

**Comment by embcla** [comment]
Interesting point

As all the others exhibit exactly the same behaviour, I will try this one sensor on the other instance.
If it's the sensor, it will keep doing the same.

**Comment by pedroke** [comment]
I noticed exactly the same problem with my WSDCGQ11LM. In the past it reported much less frequently. Now it reports every change of temperature or humidity in 0.1C steps.. In the past it was I think in 0.5C steps.. I didn't change anything.. maybe just updated z2m.. So I'm not sure if it's coincidence. I cannot see anything suspicious in z2m code.. so I'm really not sure. But since also others noticed such problem.. It really have some dramatic impact on battery life... Isn't there any default reporting setting which has been changed recently or something like that which would be common for all devices and hidden somewhere?

**Comment by maxi1134** [comment]
> WSDCGQ11LM


Hey there!
Have you ever found a solution?

**Comment by MahrWe** [comment]
I had two of these for years, I remember the first battery change being like two years into using them. 

Now I changed the batteries on both three times in the past months, first i thought i had a bad batch of batteries.

I put of the z2m updates for a while, back then i had no availability for any devices.
