### ISSUE TITLE
Polling intervall

### ISSUE THREAD

**Issue by krfa1** [Koenkk/zigbee2mqtt#597]
Hello,
zigbee2mqtt provide an update information of device more often than some other device. All of them are running the same model, etc... It is not possible to schedule the intervall

**Comment by Koenkk** [comment]
zigbee2mqtt doesnt poll, it depends on how often the device sends data.

**Comment by krfa1** [comment]
Is there a way to set this kind of setting to the device itself using zigbee2mqtt? It appears my device are set not the same way. I'm mainly using Xiaomi Smart Temperature and Humidity sensor and Xiaomi Smart Plug?

**Comment by joaquinvacas** [comment]
Know this issue is closed, but what does Z2M do when you press the "update" button on each device?

![Screenshot_20240123-184053](https://github.com/Koenkk/zigbee2mqtt/assets/4403750/40ba71a1-5baa-4182-a774-7ce85d554f53)

As some of my devices turn on using the push button but won't update on Z2M unless I press that update button.

Is there any way of invoking that update to act like a poll? For example, to make an automation for those weird-acting devices.
