### ISSUE TITLE
Hue Tap Switch compatibility?

### ISSUE THREAD

**Issue by thibaultmol** [Koenkk/zigbee2mqtt#619]
The Hue Tap Switch doesn't seem to be supported. The nice thing about that device, is that it doesn't require batteries, it completely functions of the kinetic energy of your button press.

https://www2.meethue.com/en-us/p/hue-tap-switch/046677473365

(I don't have one, so I can't test it)

**Comment by Koenkk** [comment]
I've somebody has it, we can try adding support for it.

**Comment by TjBen** [comment]
I have one and I would like to use it with Zigbee2mqtt. Now it has some restrictions from hue, like only select 3 rooms and only change hue lights. I know I can solve the first restriction with another app but the second one is probably more difficult...

I’m using hassOS and I’ve installed the add on. What do you need from me to add support?

Ps. More people should buy the tap. I’m using it as central device for multiple rooms downstairs. It looks nice and the kinetic energy is always a good story :p

**Comment by SalkinDK** [comment]
@TjBen 
Any progress? i just got one myself and would like to help out to get it supported.
Anything i can do?

**Comment by TjBen** [comment]
I tried to follow this guide: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
but without success ...

I'm afraid that because of the low power of the device that it uses a different kind of zigbee signal. When I try to put the hue tap in pairing mode (>10 s on button 1) I don't see anything in the zigbee2mqtt log. With the hue app I had to press button 3 for more then 10 seconds to connect to the app.

I'm now using the Hue API but it's not that fast. And sometimes you have to press 2 times...

more info:
https://www.zigbee.org/zigbee-for-developers/zigbee-pro/

@SalkinDK: You can try follow the guide, maybe I'm doing something wrong. 
@Koenkk:  Does Zigbee2Mqtt support Zigbee Light Link Protocol and ZigBee Green Power-protocol?

**Comment by SalkinDK** [comment]
@TjBen 
I unfortunally had the same experience, nothing is showing up in the log when trying to pair.

**Comment by Koenkk** [comment]
Zigbee light link is supported, green power not. But as all the other Hue remotes can be paired, I find it strange that this once cannot.

Are you sure that the Hue Zigbee network is down? (remove all bulbs and hub from AC).

**Comment by SalkinDK** [comment]
I dont have a hue hub running here. so there isnt another zigbee network.

**Comment by Koenkk** [comment]
Green power has been introduced in Zigbee 3.0 so first #211 has to be finished.

**Comment by thibaultmol** [comment]
Seems like a nice amount of progress was made on the last mentioned issue here. so I wonder if it actually works now already (but is just a bit unstable still)

**Comment by WhistleMaster** [comment]
Any news regarding the support of Hue Tap with zigbee2mqtt ?

**Comment by WhistleMaster** [comment]
@Koenkk Any news regarding the support of Hue Tap with zigbee2mqtt ?

**Comment by Koenkk** [comment]
@whistlemaster no, I dont have this device.

**Comment by WhistleMaster** [comment]
I have a few of them, I can help, tell me what you would need !

**Comment by Koenkk** [comment]
Reading https://github.com/Koenkk/zigbee2mqtt/issues/619#issuecomment-450145033 this would require zigbee 3.0 (green power) support, Im currently working on this.

**Comment by electrofloat** [comment]
Can we reopen this issue? There's already a downloadable zigbee 3 firmware, maybe someone can test it to see if it works?

**Comment by WhistleMaster** [comment]
I tried recently with the new 3.0 firmware, no luck unfortunately.

**Comment by Koenkk** [comment]
First green power support has to be added (https://github.com/Koenkk/zigbee-herdsman/issues/22)
