### ISSUE TITLE
Philips Hue Bulb + Power Outage

### ISSUE THREAD

**Issue by rocksolid2018** [Koenkk/zigbee2mqtt#679]
Firstly, thank you for this is great project. 
I have Philips hue model 9290011370., works great with CC2531 stick
the issue is power outage causes the bulb to lose all previous settings and I need to setup them all over. 
Not sure i missed something while setting up

Running latest Hassio with Zigbee2mqtt addon 0.2.0. 
Any help appreciated.

**Comment by Koenkk** [comment]
You mean you need to repair the bulb after a power outage?

**Comment by Koenkk** [comment]
That is the behavior of the bulb which is implemented in the software running on the bulb.

Zigbee2mqtt has no influence on this.

**Comment by ppetru** [comment]
Philips apparently just implemented this: https://www.androidpolice.com/2018/12/13/latest-philips-hue-app-update-finally-adds-power-on-behavior/

I'm guessing that to update the bulb firmware we'll need to reset each bulb, associate it with a Hue bulb, upgrade, then reset again and move it back to zigbee2mqtt. Annoying but hopefully a one time thing.

I wonder if there'll be a way to figure out how to configure the power on behavior through zigbee2mqtt afterwards, so that the same back and forth doesn't need to happen every time one wants to change it...

**Comment by danpowell88** [comment]
Zigbee2mqtt doesnt seem to poll my lights when they lose power and turn back on and then the mqtt topic doesnt know the light has turned back on, has anyone else experienced this?

**Comment by amondit** [comment]
Philips says that this feature is only available for gen2 hue (square) bridges and not gen1 (round) ones . Also when you set this up on the hue app (with a gen2 bridge), you can choose between 2 power-on behaviours for the bulbs : 
- reset the bulb to max brightness, default temp
- reset the bulb to last value
My guess is that the last value is stored on the bridge, and at power-on the bulb waits for the bridge to be online and queries it for last data before turning the light on.

**Comment by Koenkk** [comment]
@CapitanCatarro you can use https://github.com/Koenkk/zigbee2mqtt/issues/775 to accomplish this
