### ISSUE TITLE
brightness_percent setable but not reported

### ISSUE THREAD

**Issue by id628** [Koenkk/zigbee2mqtt#6874]
When I set the experimental "output: attribute" setting, I can set brightness by percentage via topic/item/set/brightness_percentage, but it is not reported back as topic/item/brightness_percentage, causing the requirement to convert only when receiving an update.

## Describe the solution you'd like
Add topic/item/brightness_percentage to go with topic/item/set/brightness_percentage

**Comment by sjorge** [comment]
It's because brightness_percentage converts 0-100 to the zigbee range of 0-254 and sets the normal brightness value.

So the it's the `brightness` attribute that gets reported back after setting it.

https://github.com/Koenkk/zigbee-herdsman-converters/blob/2391038a4cc7042038d5f8442cb635e370c2cd81/converters/toZigbee.js#L652
```node
else if (message.hasOwnProperty('brightness_percent')) brightness = Math.round(Number(message.brightness_percent) * 2.55);
```
