### ISSUE TITLE
Eurotronic SPZB0001 not working properly.

### ISSUE THREAD

**Issue by rengaboy** [Koenkk/zigbee2mqtt#7385]
According to this page - https://www.zigbee2mqtt.io/devices/SPZB0001.html, there is running_state value, but when i try to get it, hothing happening, and i got error in my log.
`Publish 'get' 'running_state' to 'eurotronic_kitchen' failed: 'Error: Read 0x00158d00053d2ba0/1 hvacThermostat(["runningState"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'`

Also, when i try to change  system_mode value, it is changing, but in values it is always stays in "auto" state.

**Comment by CodeFinder2** [comment]
Can confirm this issue. Realized for some weeks now and was hoping that recent z2m v1.18.3 fixes this but it does not. Also tested this from HA (via add-on) using `homeassistant.turn_off` and `climate.turn_off` and it worked in a previous version (I think it was 1.18.0 or 1.18.1 but not completely sure). Also tried it via the "Dashboard" and neither "Running State" (remains "N/A") nor "System Mode" (remains on "auto") changes.

Would be happy to get a fix for this as this heavily affects my automations and causes heating devices to not turn off (wasting energy). :see_no_evil:

**Comment by mcmatti** [comment]
I know that the fw for these devices are buggy and they fail
over time. 
https://github.com/EUROTRONIC-Technology/Spirit-ZigBee
Maybe this is the reason, dont know.

**Comment by CodeFinder2** [comment]
Hm, yeah thanks for your idea. Honestly, I don't think so because all of my 5 devices have the same problem (literally from one day to another) and they are not having the same fw version.

**Comment by kaykoch** [comment]
I got the same warnings, as I descriped here: 
- https://github.com/Koenkk/zigbee2mqtt/issues/6995#issuecomment-831234263
- https://github.com/Koenkk/zigbee2mqtt/issues/4571#issuecomment-829948789

I guess following: (Z2M: zigbee2mqtt Add-On)

1. HA throws Warnings for a missing variable since April (?) Update.
2. Z2M does not send all possible values (no default values)
3. Z2M does not send some variables any more (Eurotronic SPZB0001, "system_mode")
4. If you set these values in states.json, you have default values, so no Warning. But no Update (->3)

Maybe, someone can confirm these ideas.

**Comment by Papnaas** [comment]
I have some major problems with the device from 1.18.2 onwards, too. Not sure, if it has the same reason, so forgive me, if I am extending your issue here.

I made a simple setup in Node-RED sending {"eurotronic_host_flags": {"mirror_display": true}} and {"eurotronic_host_flags": {"mirror_display": false}} to control the display setup. 

With v1.18.1 everything works as expected, every time I toggle, I receive a message from the TRV reporting the new state of the flags:
`Zigbee2MQTT:info  2021-05-30 21:49:42: MQTT publish: topic 'zigbee2mqtt/EUROTRONIC Heizungsventil Keller', payload '{"battery":100,"current_heating_setpoint":23,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":true,"window_open":false},"linkquality":69,"local_temperature":20.96,"pi_heating_demand":57}'`

`Zigbee2MQTT:info  2021-05-30 21:49:43: MQTT publish: topic 'zigbee2mqtt/EUROTRONIC Heizungsventil Keller', payload '{"battery":100,"current_heating_setpoint":23,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"linkquality":66,"local_temperature":20.96,"pi_heating_demand":57}'
`

With v1.18.2 or v1.18.3, I receive hardly any message at all and if I do, the flags are always 'false'. However, the TRV reacts to the toggle and mirros the display.

Any ideas?

**Comment by rengaboy** [comment]
So is anyone has had some success with this issue?
