### ISSUE TITLE
Failed (SRSP - AF - dataRequest after 6000ms)

### ISSUE THREAD

**Issue by Krolik1988** [Koenkk/zigbee2mqtt#7593]
Hello, have some problems with Z2M.

System = Home asistan OS + Zigbee2mqtt Edge
'Зал Свет на кухню' and 'Ванна свет' = EcoDim	Eco-Dim.07
'Coordinator' = [RF TO USB (CC2530 CC2591) ](https://www.aliexpress.com/item/1005001587860129.html?spm=a2g0s.9042311.0.0.27424c4dsKs93c)
usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0 -> ../../ttyUSB0

Zigbee2MQTT:error 2021-05-25 13:07:57: Failed to execute LQI for 'Coordinator'
Zigbee2MQTT:error 2021-05-25 13:08:15: Failed to execute LQI for 'Зал Свет на кухню'
Zigbee2MQTT:error 2021-05-25 13:08:33: Failed to execute LQI for 'Ванна свет'

Zigbee2MQTT:error 2021-05-25 13:11:57: Publish 'set' 'state' to 'Ванна свет' failed: 'Error: Command 0x086bd7fffe5d33cc/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'

Zigbee2MQTT:error 2021-05-25 13:12:03: Publish 'set' 'state' to 'Зал Свет на кухню' failed: 'Error: Command 0x086bd7fffe5f149d/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'

Helps only USB replugin. Of course can make something like cron, to do it automaticly, but wants to have it work well.

**Comment by Koenkk** [comment]
This is due to point 2 of https://www.zigbee2mqtt.io/information/FAQ.html#error-srsp---sys---ping-after-6000ms (your coordinator is not powerful enough). Try using the [source routing firmware](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing). If that doesn't help update to a more powerful stick: https://www.zigbee2mqtt.io/getting_started/what_do_i_need.html#supported-zigbee-adapter
