### ISSUE TITLE
Wrong Paulmann Lamp discovered via Auto-discovery

### ISSUE THREAD

**Issue by BenJordan23** [Koenkk/zigbee2mqtt#7850]
## What happened
I paired my Paulmann 93999 (https://www.zigbee2mqtt.io/devices/93999.html) device with the permit join button (home assistant addon). The pairing worked but zigbee2mqtt thinks it is the Paulmann 798.15 lamp (https://www.zigbee2mqtt.io/devices/798.15.html#paulmann-798.15) .

## What did you expect to happen
Zigbee2mqtt would recognize the Paulmann 93999 zigbee controller as a Paulmann 93999.

## How to reproduce it (minimal and precise)
Try pairing a Paulmann 93999 zigbee controller 

## Debug info
Zigbee2MQTT version:  1.19.1
Adapter hardware: CC1352P-2
Adapter firmware version: zStack3x0 20210120

**Comment by antoninblanc** [comment]
Same issue here.

My Paulmann 939.99 is detected as Paulmann 500.45 ; Here is my database.db : 

`{"id":6,"type":"Router","ieeeAddr":"0x00158d000579d282","nwkAddr":3900,"manufId":4151,"manufName":"Paulmann Licht","powerSource":"DC Source","modelId":"500.45","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":257,"inClusterList":[0,4,3,6,8,5,4096,25],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"500.45","manufacturerName":"Paulmann Licht","powerSource":4,"zclVersion":3,"appVersion":12,"stackVersion":1,"hwVersion":1,"dateCode":"20190515","swBuildId":"1400-0001"}},"genOnOff":{"attributes":{"onOff":0}},"genLevelCtrl":{"attributes":{"currentLevel":167}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":12,"stackVersion":1,"hwVersion":1,"dateCode":"20190515","swBuildId":"1400-0001","zclVersion":3,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1649278647433,"defaultSendRequestWhen":"immediate"}
`

I dont know why Zigbee Model isnt `H036-0001` ... maybe it's a manufacturer issue / kind of rebranded product ? If someone can confirm this, I can ask them If there is no way to fix the Zigbee Model, otherwise i assume only way to fix detection is by using some ugly fingerprint ?

For me, it's not a big issue tho. Paulmann 939.99 and 500.45 are both light_on_off devices. Everything works as expected. 

However, for 500.45, the picture is wrong : https://www.zigbee2mqtt.io/devices/500.45.html (I think this picture is for Paulmann 798.15) The right picture for 500.45 is this one https://content.paulmann.com/media/ba/12/03/1618895878/50045ip01.jpg.

Thanks.
