### ISSUE TITLE
HA MQTT integration shows only one entity per device

### ISSUE THREAD

**Issue by nickcheung1000** [Koenkk/zigbee2mqtt#8125]
# Bug Report
## What happened
zigbee2mqtt and HA MQTT integration works. Devices appear in HA MQTT integration. However, there is only one entity created for the device when there are multiple attributes are exposed. The attributes are in the device state but not created as device entities in HA. I have tried to search for a similar issue but could not find any. Any suggestion would be highly appreciated. Thanks. 

![2021-07-25 15_03_33-Configuration - Home Assistant](https://user-images.githubusercontent.com/58393257/126891554-d4e1faac-ef56-41c0-a94a-be94c30118bb.png)
![2021-07-25 15_03_49-Configuration - Home Assistant](https://user-images.githubusercontent.com/58393257/126891559-8c07acc6-54f3-410c-88a2-c5e268520541.png)

## What did you expect to happen
Device attributes are created as entities. 

## Debug Info
Zigbee2MQTT version: 1.20.0-1 
Adapter hardware: CC1352P-2
Adapter firmware version: 
Coordinator type: zStack3x0
Coordinator revision: 20210120
Frontend version: 0.4.29

**Comment by robertalexa** [comment]
I think this is expected behaviour. Those are attributes of your entity and they show up in the attributes. You can still use the entity attributes in Node Red or HA dashboard cards, have a look at this thread for example https://community.home-assistant.io/t/how-to-use-attributes/139154/14

I hope I am not wrong about this being expected behaviour, if anyone knows more please correct me.

**Comment by nickcheung1000** [comment]
Thanks, Robert. 
I upgraded the core to version core-2021.7.4 last night, and now the integration is working as expected. 
<img width="467" alt="2021-08-03 11_34_28-Configuration - Home Assistant" src="https://user-images.githubusercontent.com/58393257/127953781-4416cf6a-90f4-4f52-93e6-696f5352e33d.png">
