### ISSUE TITLE
End devices works not correctly after connection from coordinator to router

### ISSUE THREAD

**Issue by domnich** [Koenkk/zigbee2mqtt#8621]
## What happened
My end devices (2 no neutral wall switches) works not correctly

## What did you expect to happen
My end devices (2 no neutral wall switches) works correctly

## How to reproduce it (minimal and precise)
1) All end devices are connected to coordinator
2) Power off raspberry pi with coordinator for 10 mins
3) Power on raspberry pi with coordinator
4) 2 wall switches and aqara motion sensor are connected to router instead of coordinator. 

Wall switches:
https://www.zigbee2mqtt.io/devices/TS0011.html
and
https://www.zigbee2mqtt.io/devices/TS0012.html

Tested with 2 different routers:
https://www.zigbee2mqtt.io/devices/DIYRuZ_R8_8.html
and
https://www.zigbee2mqtt.io/devices/TS0121_plug.html

After that, it is not possible to control the switches from HA. But if I click on switch manually - switch status updates in Home assistant. The motion sensor works OK.

Error from logs:
Zigbee2MQTT:error 2021-09-03 11:36:58: Publish 'set' 'state' to '0xbc33acfffe5ec832' failed: 'Error: Command 0xbc33acfffe5ec832/1 genOnOff.on({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'Timeout' (9999))'
Zigbee2MQTT:info  2021-09-03 11:36:58: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0xbc33acfffe5ec832' failed: 'Error: Command 0xbc33acfffe5ec832/1 genOnOff.on({}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Data request failed with error: 'Timeout' (9999))'","meta":{"friendly_name":"0xbc33acfffe5ec832"},"type":"zigbee_publish_error"}'

![11](https://user-images.githubusercontent.com/5764719/131976417-053b3bef-5010-483f-897f-38075b89d4d4.png)
![22](https://user-images.githubusercontent.com/5764719/131976445-bd9f91b3-46fb-4afc-8970-fc922267fd75.png)

## Debug info
Zigbee2MQTT version: 1.21.1-1
Adapter hardware: CC2538+CC2592
Adapter firmware version: Coordinator firmware version: '{"meta":{"maintrel":2,"majorrel":2,"minorrel":7,"product":2,"revision":20200211,"transportrev":2},"type":"zStack30x"}'

**Comment by antti365** [comment]
I have a similar situation. I rebooted the server, while the stick was offline for two minutes. Result: several battery-powered Ikea devices (switches and motion sensors) lost contact with the coordinator on the LQI 170 map, but they still work, when pressed, they control the devices. but they do not send reports to z2m every hour, as it was previously configured ... When trying to reconfigure the device in the logs, the error is:

Error Failed to configure 'switch_05', attempt 1 (Error: Bind 0x5c0272fffeb7dce1/1 genOnOff from '901' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (internal/timers.js:554:17) at processTimers (internal/timers.js:497:7))
Info MQTT publish: topic 'Zigbee/bridge/response/device/configure', payload '{"data":{"id":"switch_05"},"error":"Failed to configure (Bind 0x5c0272fffeb7dce1/1 genOnOff from '901' failed (AREQ - ZDO - bindRsp after 10000ms))","status":"error","transaction":"qfhwa-2"}'

It turns out that the network works stably only until the power on the stick is lost? Can the entire network be reconfigured after a power outage?
![2021-09-03 в 13 40 14](https://user-images.githubusercontent.com/6865425/131993635-07af726f-2ee6-4c9c-9b68-0c2a99bf02b6.jpg)
