### ISSUE TITLE
Yale Doorman V2N with Yale Smart Module

### ISSUE THREAD

**Issue by henriklied** [Koenkk/zigbee2mqtt#8771]
I see that Zigbee2MQTT has support for several Yale locks, and I was wondering whether they are interoperable in terms of functionality and how they communicate.

I have a [Yale Doorman V2N](https://www.yalehome.no/Yale/yaledoormanNO/Manualer/Yale%20Doorman/YDV2N-manual-M3639.2015.pdf), and was wondering about buying the [zigbee smart module](https://www.kjell.com/no/produkter/smarte-hjem/smarta-las/yale-doorman-lasemodul-p51272) which works with the [Yale Smart Hub](https://www.kjell.com/no/produkter/smarte-hjem/smarta-las/yale-smart-hub-smarthjem-kontroller-p51271). But I'm obviously not interested in spending $200 on the kit including the hub, since I want to integrate it with Zigbee2MQTT.

The only information I've found about the module is that it states it's encrypted. Does that have anything to say in regards to whether it's possible to integrate into Zigbee2MQTT? Do I need to get the hub in order to sniff enough traffic to make it work with Z2M?

**Comment by danieledwardgeorgehitchcock** [comment]
I am sure that the Zigbee Module could be made to work with Zigbee2MQTT if you were to buy one and post up your logs / device entry for it.

From a curiosity point of view, these modules look like they may share the same form factor as the Smart Living locks which don't have a Zigbee equivalent.

Would there be any chance of maybe setting something up for you to purchase one on my behalf and send to the UK so that I can test this theory? I have paypal...

**Comment by henriklied** [comment]
I'm sure we can work something out, @danieledwardgeorgehitchcock. I've ordered one for myself, and will try to get it working. I can also send you some photos with measurements when I get it. Send me an email @ gmail.com.

**Comment by danieledwardgeorgehitchcock** [comment]
Emailed yesterday.. Hopefully you got it?..

**Comment by henriklied** [comment]
Update here: The Yale Smart Module seems to be using Z-Wave for communication. So that's of no use here.
