### ISSUE TITLE
change network key -> repair devices

### ISSUE THREAD

**Issue by chiefe86** [Koenkk/zigbee2mqtt#916]
Dear all,

I want to change the network key now.

What does it mean to repair the devices afterwards?

What network key is allowed? only numbers? is there a restriction?

Many thanks

**Comment by Koenkk** [comment]
Because the network key changes, the devices cannot communicate with the coordinator, therefore you have to repair all devices.

Only an array of 16 numbers is allowed.

**Comment by chiefe86** [comment]
Thank you for your reply.
How can I repair them? 
Do I have to pair them again, or repair them? Sorry for the confusion...

**Comment by ryanbeaton** [comment]
Yes that term gets quite confusing here. You will need to re-pair (pair again) not repair (as in some fixing).

**Comment by daveyrb** [comment]
`advanced:
  network_key: [7, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 11, 12, 13],`
Should the above have the comma on the end?
If I put that in my config it fails to load if I remove the comma it loads OK. I have yet to add any devices as I have just started setting it up.

**Comment by Koenkk** [comment]
There shouldnt be a comma (otherwise its not valid yaml)

**Comment by h4nc** [comment]
@koenk I also switched changed my network key. 

I also had to delete that comma at the end to be able to set it up. Otherwise I got an error in the zigbee logs. This error pointet to this comma

So instead of 

`advanced: network_key: [7, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 11, 12, 13],`

this: 

`advanced: network_key: [7, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 11, 12, 13],`

Of course with other numbers. Also after saving without comma and rebooting the addon, my yaml now looks like this (not my real code).

<img width="154" alt="bildschirmfoto 2019-01-30 um 17 13 37" src="https://user-images.githubusercontent.com/25117255/51995166-79567a80-24b2-11e9-8947-149908cd3d76.png">


Could you also add the restriction to that network_key to the docs?
Like 

- 16 numbers
- only one or two characters (so 1, 11)? Is 99 allowed? Is 999 allowed?

**Comment by Koenkk** [comment]
@h4nc this is already being worked on: #963 #969

**Comment by Koenkk** [comment]
@h4nc fixed in #963. I assume this can be closed now.
