### ISSUE TITLE
Hue Light 9290022169 does not accept color_temp change while OFF (online with brightness=0)

### ISSUE THREAD

**Issue by mkaut** [Koenkk/zigbee2mqtt#9167]
### Discussed in https://github.com/Koenkk/zigbee2mqtt/discussions/8948

<div type='discussions-op-text'>

<sup>Originally posted by **BigT-CZE** October  1, 2021</sup>
Hello guys, could you please help me? I got couple Hue Lights "Philips 9290022169" at home connected to Zigbee2MQTT obviously. When I try to change color for them, it works only when light's brightness is bigger than 0. Do you know how to change their color, when brightness is 0? I tried to set "color_temp_startup" along with usual "color_temp". I analysed logs and lights are accepting new color value without issue:

info  2021-10-01 21:27:03: MQTT publish: topic 'zigbee2mqtt/friendly_name/color_mode', payload 'color_temp'
info  2021-10-01 21:27:03: MQTT publish: topic 'zigbee2mqtt/friendly_name/update-state', payload 'idle'
info  2021-10-01 21:27:03: MQTT publish: topic 'zigbee2mqtt/friendly_name/state', payload 'OFF'
info  2021-10-01 21:27:03: MQTT publish: topic 'zigbee2mqtt/friendly_name/brightness', payload '0'
info  2021-10-01 21:27:03: MQTT publish: topic 'zigbee2mqtt/friendly_name/color_temp', payload '450'
info  2021-10-01 21:27:03: MQTT publish: topic 'zigbee2mqtt/friendly_name/linkquality', payload '90'

but when I change brightness, their color is still on the previous color, when they had brightness > 0. 

Description of my issue:
1) Light have brightness 50 (something > 0)
2) I change color to 200
3) I change brightness to 0
4) Then I change color to 400
5) and then set brightness back to 200 and color is still the same as in the point 2 and light is reporting color 400 to logs

</div>

**Comment by PaulHamdinger** [comment]
Seeing the same problem here (1.27.0).

I added "hue_power_on_behavior" and "hue_power_on_color" to the mix, just in case those values were affecting outcomes, but I'm seeing the same results.

The way I use them, my Hue lights are always-powered, and I use Hue switches to toggle their state on/off. Throughout the day I adjust the temperature of the lights to match the sun. If I last toggled-on a light at noon and the lights are cool, when I next toggle on the lights at night I expect them to be warm, since I've been updating their colour temperature throughout the day. Unfortunately they come up using their "old" value.

Z2M seems to want to do the correct thing -- it's internal model seems to think the light values have been updated -- so the bug I guess is between the internal model and the light itself.

**Comment by PaulHamdinger** [comment]
A possible solution, from another thread : https://github.com/Koenkk/zigbee2mqtt/issues/13562

@sjorge mentions enabling the "execute_if_off" flag of "color_options" if you have Hue or Trådfri bulbs : https://github.com/Koenkk/zigbee2mqtt/issues/13562#issuecomment-1217712911

I've only tested it a bit so far, but my bulbs are behaving as-expected now. I don't see this option documented anywhere.

Example, to enable to flag :

`mosquitto_pub -t 'zigbee2mqtt/ikea-desk-lamp/set/color_options' -m '{"execute_if_off":true}' -q 2`
