### ISSUE TITLE
FLS/AIRLINK/4 LK Wiser battery button has wrong button response

### ISSUE THREAD

**Issue by taugusti** [Koenkk/zigbee2mqtt#9209]
## What happened
I have paired a LK Wiser 4-way battery button (FLS/AIRLINK/4). Interview is ok. All looks ok.

The problem is that the top and bottom row of buttons behave the same way.
It reports "on_top" on both the top left and bottom left button on the zigbee2mqtt/<id>/action topic
It reports "top_off" on the top and bottom right buttons.

I see the same in both Home assistant and in mqttfx.

![image](https://user-images.githubusercontent.com/15052792/137751122-becf5fba-a254-4a01-8232-93d8062f3c44.png)

Herdsman log: https://pastebin.com/6VDwkGAj

Please let me know if there is a way I can help get the right information for the device implementation

## What did you expect to happen
Top and bottom rows with different responses to clicks

## Debug info
Zigbee2MQTT version: 1.21.2-1 (hass version)
Adapter hardware: CC2652R1
Adapter firmware version: 20210708

**Comment by taugusti** [comment]
Am I the only one with this problem?

**Comment by koburg** [comment]
no this problem still exist I have same device same problem.

**Comment by vinta7** [comment]
I have the same issue with newly paired devices, devices paired long time ago works as they should.

**Comment by poizan42** [comment]
So I have 3 LK Wiser buttons here and one of them have this problem.

The one with the problem has firmware version 002.005.023 R
The working ones both have firmware version 002.005.029 R

This might be the problem right there. I have no idea how to update the firmware though, maybe you need the Wizer gateway?

@Koenkk  Can we reopen this issue?

**Comment by poizan42** [comment]
So I found the solution to this. The firmware version might be the reason for the defaults, but it turns out that it contains the same PCB as the EKO07117 SmartSwitch Push Wireless (https://proff.elko.no/elko-smart/ELKO%20Smart%20System%20User%20Guide/English/ELKO%20Smart%20System%20User%20Guide.pdf), which by default starts out in 1-channel mode.

Someone on the Home Assistant forums figured out how to put it into 2-channel mode without the gateway: https://community.home-assistant.io/t/elko-smart-4-button-switch-setup/425226/2

> I was looking for the same and found this: [Schneider Wiser Remote 1](https://community.home-assistant.io/t/schneider-wiser-remote/407990)
It works perfectly well for me with the Elko smart switch connected with ConBee USB stick. For some reason I had to activate 2-channel mode by pressing button 1 and 4 for 10 seconds.

It may be longer that 10-seconds - I just held the buttons down until the LED flashed red and then became green. That seems to have done the trick, and now I can use all four buttons independently on that switch too.

**Comment by poizan42** [comment]
A small side note for posterity: The buttons I had with the newer firmware version do not react at all to holding down button 1 and 4, so my guess is that it's a leftover from the functionality of the EKO07117, and the LK Wiser 4-way battery button (550D6001) never actually was supposed to have that functionality. That also explains why this isn't in the documentation for the 550D6001.
