### ISSUE TITLE
livolo 2 gang switch turn off issue

### ISSUE THREAD

**Issue by matrosovas** [Koenkk/zigbee2mqtt#9239]
Bug report

## What happened
livolo switch with 2 gangs only turns off one gang when Homebridge Zigbee2MQTT sends "{"state_right":"OFF","state_left":"OFF"}" 

## What did you expect to happen

both gangs turn off

## How to reproduce it (minimal and precise)

turning both gangs on and in home app hitting lighst off sends above payload

## Debug info
Zigbee2MQTT version: 1.21.2
Adapter hardware: CC2652RB 
Adapter firmware version: not sure, flashed with https://slae.sh/projects/cc2652/

**Comment by matrosovas** [comment]
Commenting to get some attention 🙂

**Comment by itavero** [comment]
Just wondering, does a similar problem occur when changing the state to On?

**Comment by matrosovas** [comment]
@itavero Thanks for your input! correct this is the switch and same happens for On as well. hopefully one of those guys can help out :)

**Comment by onixx** [comment]
The same issue occurs with the GE plug in smart dimmer model 45852GE. Brightness and State on is published together and in this case only brightness is taken by device. State is ignored which results in the device not turning on. Republishing state on manually does turn on the device

**Comment by Piscator74** [comment]
I just checked it with MQTT Explorer (to avoid potential problems caused by Homebridge or other domotics system).
And indeed I can confirm that when turning both `state_left` and `state_right` to ON or OFF **at the same time**, you see this behavior. I never set both channels at exactly the same time, so I never had this issue.

I think there can be 2 possible causes. You have to debug `livolo_socket_switch_on_off` in `toZigbee.js` 
1. The current implementation just sends the first command and ignores the second/subsequent command(s) in the same request.
2. The vendor implementation ignores the 2nd command when multiple commands are sent too quickly in succession.

It is open source, so feel free to give it a shot :-)

**Comment by sanychonline** [comment]
I do observe the same issue. I assume the switch itself can't perform parallel toggle actions. May we have a parameter to send delay 1 sec for a second gang?

**Comment by Piscator74** [comment]
That is sort of hard to implement / make a workaround for. Basically, you would need to cache requests and send them later again. And the actual problem is the bad implementation on the device (that is closed source). I think you would even need to have a delay for 2 seconds.
