### ISSUE TITLE
Ubisys D1 light go on when send "state": "OFF"

### ISSUE THREAD

**Issue by Danit2** [Koenkk/zigbee2mqtt#9313]
## What happened

1. i switch the light off locally using the pushbutton.
2. an automation then sends an off command again.
3. the light goes on briefly and then switches off again immediately.

## What did you expect to happen
When the light is off and i send a second off command the light must stay off.

## How to reproduce it (minimal and precise)
Turn off the light over the local pushbotton and then send e MQTT command with "state": "OFF" to the light. 

## Debug info
Zigbee2MQTT version: 1.21.2
Adapter hardware: SMARTLIGHT CC2652P
Adapter firmware version: 20210708

**Comment by felixstorm** [comment]
I just tried this out on my network by sending an off message twice to an ubisys D1 and could not reproduce the behavior you observed - my guess would be that it's some other side effect from the automation causing the light to come on again briefly. 

To diagnose this any further I would need zigbee2mqtt debug logs - would you be able to provide them?

**Comment by Danit2** [comment]
Hallo @felixstorm 

Thanks for your answer.

It only happen when you turn off the Light locally over the pushbutton and then from the automation.

When i send a off coommand twice then nothin happen.

Here the debug log:
[Neues Textdokument (2).txt](https://github.com/Koenkk/zigbee2mqtt/files/7492792/Neues.Textdokument.2.txt)

Hope you find something. 

Thanks for your help.

**Comment by felixstorm** [comment]
@Danit2 Thanks for the log (I assume it's 'Esszimmer_Lampe' we're talking about?). I can see from the logs the behavior you describe: After receiving the OFF command, the device briefly reports onOff=1 and then onOff=0, but unfortunately I have no clue why this happens. I also tried to reproduce it here by manually turning my D1 off and then sending another OFF command through the Home Assistant Service "Light: turn off", but here for me it works as intended.

I have a few ideas, but unfortunately no real solution:
- Could your automation invoke some kind of transition effect or similar to switch off the D1?
- Maybe the state of the D1 does not get synchronized properly with zigbee2mqtt, but reporting generally seems to be ok since the device sends the appropriate attributeReports.

My only idea about how to diagnose this any further would currently be for you to create another log again with more context, i.e. a log that starts with an ON command through the time when you switch the D1 off manually and then until after the OFF command, together with the exact point in time when you switched it off manually in between. Maybe this provides some further clue on what is going on...
