### ISSUE TITLE
Wifi and Zigbee problems

### ISSUE THREAD

**Issue by melad** [Koenkk/zigbee2mqtt#9630]
I had a very strange behavior with my Wifi. Sometimes 1 - 2 times a day it stops responding/responds very slow it acted very strange. This kept till I rebooted my fritz.box. Than everything worked fine again. Till the next time.

I was talking with the support. They could not help me.

Now I changed the Zigbee Channel to 25 than to 24. Since than I do not have problems with my wifi. I did not reboot the router. 
But know I have Problems with my Zigbee. After sometime I get a SRSP - AF - dataRequest after 6000ms error. Bevor everything worked fine.

As I updated to the newest Version 1.22 this happened very fast. I reverted back to 1.19.1 and than it take some time but it happens also.

My fritz.box is running on channel 1.     

Can someone give me hint. What to do ?

## Debug info
Zigbee2MQTT version: 1.19.1
Adapter hardware: cc2652rb
Adapter firmware version: 20210120

**Comment by robertalexa** [comment]
Re-pairing all your zigbee devices is mandatory after changing the zigbee channel.

Personally I highly doubt your zigbee network is impacting your wifi. That is because none of the zigbee devices will have enough power to interfere with your wifi traffic. If anything, wifi is usually what interferes with zigbee, and that is because you will have a much bigger and stronger access point for wifi.

If you are trying to sort out your networks, i recommend you download an android app called Wifi Analyzer. That will show you how much wifi congestion you have around you. Based on that, you will be able to choose the best channel to use for your wifi. After deciding which wifi channel is best for your, you can look into what is the best zigbee channel (basically move away from your wifi channel and try to pick one that overlaps as little intereference from your neighbours wifi)
