### ISSUE TITLE
Home Assistant does not show history for WXKG01LM (Siaomi switch) actions

### ISSUE THREAD

**Issue by Heisenberg2980** [Koenkk/zigbee2mqtt#9763]
## What happened
I have multiple Xiaomi switches (https://www.zigbee2mqtt.io/devices/WXKG01LM.html) and the neither Home Assistant Logbook or History show the actions of the buttons, just the "changed to none" is stored:

![image](https://user-images.githubusercontent.com/58039006/142733181-8bcbe0e2-a9f3-4a61-95c2-e261d7dbeccf.png)

## What did you expect to happen
Home Assistant Logbook or History show the actions for the buttons (single, double, triple, etc...)

## How to reproduce it (minimal and precise)
Just push the buttons and check the entity action to confirm it doesn´t contain the actions

## Debug info
Zigbee2MQTT version: 1.22.0-2
Adapter hardware: CC2652R
Adapter firmware version: Z-Stack_3.x.0

**Comment by danieledwardgeorgehitchcock** [comment]
Hi,

The actions in Zigbee2MQTT aren't stateful, they are event based meaning that an action occurs (such as button press), event fires, then returns to blank / empty / null.

In order to use these as triggers in HomeAssistant, you have to listen for an MQTT event rather than a device state changing.

Please see [here](https://www.zigbee2mqtt.io/guide/faq/#why-is-the-action-property-always-empty) for a further explanation
