### ISSUE TITLE
Error: SRSP - ZDO - mgmtPermitJoinReq after 6000ms

### ISSUE THREAD

**Issue by sanyafifa** [Koenkk/zigbee2mqtt#9777]
Several times a day error: Error: SRSP - ZDO - mgmtPermitJoinReq after 6000ms.
Solution to the problem: turn off turn on stick

![image](https://user-images.githubusercontent.com/49896945/142763464-aca8d223-62db-4f70-8b98-6361b9d152f0.png)

![image](https://user-images.githubusercontent.com/49896945/142763486-2480b272-55dc-4dd6-8fc8-920552f9a644.png)

Coordinator type: CC2531

**Comment by Koenkk** [comment]
This means the CC2531 crashed (common since it is not very powerful), switching to the source routing firmware might help (https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing), if it doesn't consider upgrading to a more powerful adapter: https://www.zigbee2mqtt.io/guide/adapters/#recommended
